library/common/up_axi.v

The Qsys interconnect does not handle the assertion of BVALID on the
same cycle as [A]WREADY. Add a single cycle of delay to prevent
deadlocks.
Similar to:
2817ccdb22b5faf232a73e52fd9578ae89a66c4b
("up_axi: altera can not handle same clock assertion of arready and rvalid")
Signed-off-by: Matthew Fornero <matt.fornero@mathworks.com>

up_axi: Same cycle BVALID/READY fails on Altera

---

library/util_clkdiv/util_clkdiv_ip.tcl

If the output pin is not defined as a clock, some of the Vivado IPI
propagation TCL will error out.
Signed-off-by: Matt Fornero <matt.fornero@mathworks.com>

util_clkdiv: Register output port as a clock

---

library/scripts/adi_env.tcl
projects/scripts/adi_env.tcl

If the ADI_HDL_DIR or ADI_PHDL_DIR are set on Windows platforms, an
invalid TCL character (e.g. backslash) may be used as a file separator,
causing issues with the build / library scripts.
Normalize the paths before using them as global TCL variables.

adi_env: Normalize environment variables

---

library/common/axi_streaming_dma_rx_fifo.vhd

Hi,
this is a fix to a nasty issue found while using the axi_i2s_adi IP on ZynqMP UltraScale+.
The axi_i2s_adi is used to capture from I2S and feed it to a Xilinx AXI DMA via an AXI4 stream. But even setting correct values of `PERIOD_LEN_REG` (e.g. 7, see [this blog post](https://ez.analog.com/message/313405-axi-i2s-s2mm-tlast-issue-on-zynq-ultrascale#comment-313585)), the `m_axis_tlast` output toggles at random intervals and much less often than expected.
This seems be due to an excessive decrementing of `period_count`. This patch fixed the problem for me by adding an `if rising_edge(m_axis_aclk)` so that `period_count` and `m_axis_tlast` toggle only on the clock rising edge.

axi_streaming_dma_rx_fifo: fix period_count clock and TLAST

---

library/axi_dmac/axi_dmac_ip.tcl

Bundle the TLAST signal in with the other AXIS slave signals to enable
easier connection between AXIS devices that use TLAST
Signed-off-by: Matt Fornero <matt.fornero@mathworks.com>

axi_dmac: Include TLAST in AXIS slave port

---

projects/fmcomms5/zc702/system_top.v
projects/fmcomms5/zc706/system_top.v
projects/fmcomms5/zcu102/system_top.v

Fixes the following warnings:
[Synth 8-2611] redeclaration of ansi port txnrx_0 is not allowed
[Synth 8-2611] redeclaration of ansi port enable_0 is not allowed
[Synth 8-2611] redeclaration of ansi port enable_1 is not allowed
[Synth 8-2611] redeclaration of ansi port txnrx_1 is not allowed
This is a leftover of commit 1c23cf46216a ("all: Update verilog files to
verilog-2001").

fmcomms5: Remove wire that are redeclarations of ports

---

library/scripts/library.mk
projects/scripts/project-xilinx.mk

Currently the IP component dependency in the Makefile system is the Vivado
project file. The project file is only a intermediary product in producing
the IP component definition file.
If building the component definition file fails or the process is aborted
half way through it is possible that the Vivado project file for the IP
component exists, but the IP component definition file does not.
In this case there will be no attempt to build the IP component definition
file when building a project that has a dependency on the IP component.
Building the project will fail in this case.
To avoid this update the Makefile rules so that the IP component definition
file is used as the dependency. In this case the IP component will be
re-build if the component definition file does not exist, even if …

Makefile: Change IP component dependency to component definition file

---

library/axi_ad9250/axi_ad9250_hw.tcl
library/axi_ad9671/axi_ad9671_hw.tcl
library/axi_ad9680/axi_ad9680_hw.tcl
library/axi_generic_adc/Makefile
library/axi_generic_adc/axi_generic_adc_ip.tcl
library/axi_mc_controller/Makefile
library/axi_mc_controller/axi_mc_controller_ip.tcl
library/axi_mc_current_monitor/Makefile
library/axi_mc_current_monitor/axi_mc_current_monitor_ip.tcl
library/axi_mc_speed/Makefile
library/axi_mc_speed/axi_mc_speed_ip.tcl
projects/daq2/a10gx/Makefile
projects/daq2/a10soc/Makefile
projects/daq3/a10gx/Makefile
projects/fmcjesdadc1/a10gx/Makefile
projects/fmcjesdadc1/a10soc/Makefile
projects/usdrx1/a10gx/Makefile

Some IP core have files in their file list for common modules that are not
used by the IP itself. Remove those.

library: Remove unreferenced files from IP file lists

---

library/jesd204/tb/loopback_tb.v

The jesd204_rx instantiation contained a port that did not exist. (phy_ready)

jesd204:tb: Fix the loopback_tb test bench

---

library/common/ad_datafmt.v
library/common/ad_sysref_gen.v
library/util_dacfifo/util_dacfifo.v

Most of these probably shouldn't even be warnings. But fixing them makes it easier to filter through the noise when looking for warnings that point out actual issues.

Fix a few simple warnings generated by Quartus

---

library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_hw.tcl
library/axi_dmac/axi_dmac_ip.tcl

Exposed AXI3 interface on the Intel version of the IP for UI and feature consistency.
Some of the signals that are defined as optional in the AMBA standard
are marked as mandatory in Qsys in case of AXI3. Because of this such signals
were added to the interface of the DMAC and driven with default values.
For Xilinx in order to keep existing behavior the newly added signals
are hidden from the interface.
New parameters are added to define the width of the AXI transaction IDs;
these are hidden from the UI; We can add them to the UI if the fixed size
of the IDs will cause port incompatibility issues.

axi_dmac: AXI3 support on Intel qsys

---

library/scripts/adi_ip.tcl

This commit fixes the following warning from the IP packaging flow:
"[IP_Flow 19-801] The last file in file group "Synthesis" should be an HDL file:
"axi_dmac_constr.ttcl".  During generation the IP Flow uses the last file to
determine library and other information when generating the top wrapper file.
If possible, please make sure that non-HDL files are located earlier in the list
of files for this file group."
Having the ttcl or other non HDL file at the end of the file group causes issues
when the project preferred language is set to VHDL. Since the synthesis file group
is set to "xilinx_anylanguagesynthesis" the tool tries to guess the type of wrapper
to be generated for that IP based on the last file from the file group.
If the file is non HDL then he defaults to the preferred …

adi_ip.tcl: reorder synthesis files in the file group

---

library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_hw.tcl
library/axi_dmac/bd/bd.tcl
library/axi_dmac/request_arb.v

Two commits to make sure that we do not accidentally setup the core in a configuration that will generate bursts that are longer than the system can handle.

AXI-DMAC burst length verification

---

library/axi_dmac/request_arb.v

When the source and destination bus widths don't match a resize block is
inserted on the side of the narrower bus. This resize block can contain
partial data.
To ensure that there is no residual partial data is left in the resize
block after a transfer shutdown the resize block is reset when the DMA is
disabled.
Currently this is implemented by tying the reset signal of the resize block
to the enable signal of the DMA. This enable signal is only a indicator
though that the DMA should shutdown. For a proper shutdown outstanding
transactions still need to be completed.
The data that is in the resize block might be required to complete those
transactions. So performing the reset when the enable signal goes low can
lead to a situation where the DMA tries to complete a transaction but can't
do …

axi_dmac: Fix bus resize block reset

---

library/altera/adi_jesd204/adi_jesd204_hw.tcl
library/altera/jesd204_phy/jesd204_phy_glue.v
library/altera/jesd204_phy/jesd204_phy_glue_hw.tcl
library/altera/jesd204_phy/jesd204_phy_hw.tcl
library/jesd204/jesd204_soft_pcs_rx/jesd204_soft_pcs_rx.v
library/jesd204/jesd204_soft_pcs_rx/jesd204_soft_pcs_rx_hw.tcl
library/jesd204/jesd204_soft_pcs_tx/jesd204_soft_pcs_tx.v
library/jesd204/jesd204_soft_pcs_tx/jesd204_soft_pcs_tx_hw.tcl
library/jesd204/tb/soft_pcs_loopback_tb.v
library/xilinx/util_adxcvr/util_adxcvr.v
library/xilinx/util_adxcvr/util_adxcvr_xch.v

Some designs choose to swap the polarity on the JESD204 lanes. This means negative pin of the converter transceiver is connected to the positive pin of the FPGA transceiver and vice versa. One reason for this is layout constraints where the positive and negative traces otherwise have to cross each other.
Such a link will work fine from a electrical perspective, but all bits will be inverted. This series adds a configuration parameter to the link layer component to flip the polarity and undo the inversion that is caused by the electrical wiring.
Since this will typically only affect some of the lanes the configuration parameter is supplied as a mask that allows to select this for each lane individually.

Add support for JESD204 lane polarity inversion

---

library/jesd204/axi_jesd204_common/jesd204_up_common.v
library/jesd204/axi_jesd204_rx/axi_jesd204_rx.v
library/jesd204/axi_jesd204_rx/axi_jesd204_rx_hw.tcl
library/jesd204/axi_jesd204_rx/axi_jesd204_rx_ip.tcl
library/jesd204/interfaces/interfaces_ip.tcl
library/jesd204/jesd204_rx/jesd204_rx.v
library/jesd204/jesd204_rx/jesd204_rx_ctrl.v
library/jesd204/jesd204_rx/jesd204_rx_hw.tcl
library/jesd204/jesd204_rx/jesd204_rx_ip.tcl
library/jesd204/jesd204_rx_static_config/jesd204_rx_static_config.v
library/jesd204/scripts/jesd204.tcl
library/jesd204/tb/axi_jesd204_rx_regmap_tb.v
library/jesd204/tb/rx_tb.v

A multi-link is a link where multiple converter devices are connected to a single logic device (FPGA). All links involved in a multi-link are synchronous and established at the same time. For an RX link, this means that the SYNC signal needs to be propagated from the FPGA to each converter.
Dynamic multi-link support must allow selecting which converter devices on the multi-link the SYNC signal is propagated too. This is useful when depending on the use case profile some converter devices are supposed to be disabled.
Add the cfg_links_disable[0x081] register for multi-link control and propagate its value to the RX FSM.

Multi-link Rx JESD204

---

library/jesd204/axi_jesd204_common/jesd204_up_common.v
library/jesd204/axi_jesd204_tx/axi_jesd204_tx.v
library/jesd204/axi_jesd204_tx/axi_jesd204_tx_constr.sdc
library/jesd204/axi_jesd204_tx/axi_jesd204_tx_constr.xdc
library/jesd204/axi_jesd204_tx/axi_jesd204_tx_hw.tcl
library/jesd204/axi_jesd204_tx/axi_jesd204_tx_ip.tcl
library/jesd204/axi_jesd204_tx/jesd204_up_tx.v
library/jesd204/interfaces/interfaces_ip.tcl
library/jesd204/jesd204_tx/jesd204_tx.v
library/jesd204/jesd204_tx/jesd204_tx_ctrl.v
library/jesd204/jesd204_tx/jesd204_tx_hw.tcl
library/jesd204/jesd204_tx/jesd204_tx_ip.tcl
library/jesd204/jesd204_tx_static_config/jesd204_tx_static_config.v
library/jesd204/scripts/jesd204.tcl
library/jesd204/tb/axi_jesd204_tx_regmap_tb.v
library/jesd204/tb/loopback_tb.v
library/jesd204/tb/tx_tb.v

A multi-link is a link where multiple converter devices are connected to a single logic device (FPGA). All links involved in a multi-link are synchronous and established at the same time. For a TX link, this means that the FPGA receives multiple SYNC signals, one for each link. The state machine of the TX link peripheral must combine those SYNC signals into a single SYNC signal that is asserted when either of the external SYNC signals is asserted.
Dynamic multi-link support must allow selecting to which converter devices on the multi-link the SYNC signal is propagated too. This is useful when depending on the use case profile some converter devices are supposed to be disabled.
Add the cfg_links_disable[0x081] register for multi-link control and propagate its value to the TX FSM.

Multi-link Tx JESD204

---

library/jesd204/axi_jesd204_rx/axi_jesd204_rx.v
library/jesd204/axi_jesd204_rx/axi_jesd204_rx_constr.sdc
library/jesd204/axi_jesd204_rx/axi_jesd204_rx_hw.tcl
library/jesd204/axi_jesd204_rx/axi_jesd204_rx_ip.tcl
library/jesd204/axi_jesd204_rx/jesd204_up_rx.v
library/jesd204/axi_jesd204_rx/jesd204_up_rx_lane.v
library/jesd204/interfaces/interfaces_ip.tcl
library/jesd204/jesd204_rx/jesd204_rx.v
library/jesd204/jesd204_rx/jesd204_rx_hw.tcl
library/jesd204/jesd204_rx/jesd204_rx_ip.tcl
library/jesd204/jesd204_rx/jesd204_rx_lane.v
library/jesd204/tb/axi_jesd204_rx_regmap_tb.v
library/jesd204/tb/rx_lane_tb.v
library/jesd204/tb/rx_tb.v

Added 32 bit error countr per lane, register 0x308 + lane*0x20
On the control part,register 0x244 added a counter reset and counter mask
Bit 0 resets the counter if set to 1
Bit 8 masks the disparity errors, when set to 0
Bit 9 masks the not in table errors when set to 0
Bit 10 masks the unexpected k errors
At this point, the unexpected K errors are counted when a character other than k28 is detected
The counter starts adding the errors when the CGS phase is complete

jesd204: Add RX error statistics

---

projects/adrv9009/common/adrv9009_bd.tcl
projects/adrv9009/zcu102/system_bd.tcl

Moved XCVR related connections to HP0, where the HP shares the MUX with the Video DMA
HP1 and HP2 are used for RX OS and RX DMAs, sharing the MUX. Usually they shouldn't run at the same time.
HP3 is used for TX DMA, sharing the MUX with the FPD DMA controller
All HPx and DMA buswidths have been increased to 128 bits
The HPx-DMA clock has been increased to 300 MHz
DAC FIFO address size has been increased to 17

adrv9009: Improved data throughput and DAC FIFO size

---

projects/fmcomms5/zc702/system_top.v
projects/fmcomms5/zc706/system_top.v
projects/fmcomms5/zcu102/system_top.v

In the system top of the FMCOMMS5 projects, there are several GPIO lines, which
can not find in the constraint file, respectively gpio_open_15_15,
gpio_open_44_44 and gpio_45_45.
These are floating GPIO pins, as their names suggest. Delete all these wires and update IOBUF instances.

fmcomms5: Clean up GPIO connections on system top

---

projects/daq2/a10gx/system_project.tcl
projects/daq3/a10gx/system_project.tcl

There are a random timing violations on the A10GX board using the DAQ3 and DAQ2 projects.
Setting the synthesis/implementation strategy to "HIGH PERFORMANCE EFFORT" increases the success rate of the timing closure significantly.

daq2|3: Set up OPTIMIZATION_MODE to improve timing

---

library/util_cdc/sync_bits.v
library/util_cdc/sync_event.v
library/util_cdc/sync_gray.v

Some parts of the util_cdc library rely on dead logic elimination to remove
unused logic. Unfortunately with newer Vivado versions this results in
warnings about unused sequential elements being removed. Like:
WARNING: [Synth 8-6014] Unused sequential element cdc_sync_stage1_reg was removed.
To avoid this encase the logic in generate blocks that makes sure they are
not generated when not needed.

util_cdc: Silence warnings about unused sequential logic

---

library/util_dacfifo/util_dacfifo.v

The DMAC implementation guarantees that the expression `dma_valid &
dma_xfer_req` is always identical to just dma_valid.
When generating the util_dacfifo dma_wren_s signal the optimizer doesn't know
of this though and hence will route both signals into the LUT that drives
the write enable for the BRAMs.
Simplify the expression by removing dma_xfer_req from it. Considering this
can be a fairly high fan-out net and is typically the bottleneck for the
util_dacfifo timing this helps to improve the timing.

util_dacfifo: Reduce logic on high fan-out dma_wren_s signal

---

library/xilinx/axi_dacfifo/axi_dacfifo_address_buffer.v
library/xilinx/axi_dacfifo/axi_dacfifo_rd.v

This showed up as a warning when building the ADRV9371 project. The issue should also be present in the hdl_2018_r1 branch, but I haven't seen any reports yet that it does not work. So I'm not sure what is going on. @Csomi can you have a look?
https://ez.analog.com/message/349999-arria10-ad9371-iiopushbuffer-always-gives-cyclic-transmit-behavior#comment-350324 might be related.
My understanding is that this would result that we keep on reading from address 0x0 instead of incrementing the address.

Fix AXI dacfifo

---

projects/adrv9009/common/adrv9009_bd.tcl
projects/adrv9009/zcu102/system_bd.tcl

ADRV9009 throughput related changes. Increase DMAs store-and-forward size and dma_clk to maximum possible frequency for the HP ports.

Adrv9009 throughput

---

library/axi_dmac/axi_dmac_constr.sdc

The timing exceptions for the debug paths are currently a bit to broad and
can include paths that should not have an exception.
All the debug signals are coming from the i_request_arb instance, so
include that in the match to avoid false positives.
For most projects this wont have been a problem since there is usually a
fair amount of slack on the paths that were affected by this. But in
projects with high utilization this might result in undefined behavior.
I checked some projects and didn't find any where the this caused paths that were longer that they should have been, but we probably still want to add to add this to the release branch.

axi_dmac: Be more specific about debug register timing exceptions

---

projects/scripts/adi_tquest.tcl

In addition to setup and hold also check recovery and removal, they are
just as important.

adi_tquest.tcl: Check recovery and and removal timing

---

library/xilinx/axi_dacfifo/axi_dacfifo.v
library/xilinx/axi_dacfifo/axi_dacfifo_address_buffer.v
library/xilinx/axi_dacfifo/axi_dacfifo_rd.v
library/xilinx/axi_dacfifo/axi_dacfifo_wr.v

Currently the axi_dacfifo does not work correctly if the data is not aligned to the bus width of the AXI memory mapped interface of the DDR controller. (a few samples are lost in each cycle)

Fix DAC FIFO data alignment

---

library/axi_dmac/axi_dmac_hw.tcl
projects/adrv9371x/common/adrv9371x_qsys.tcl
projects/daq2/common/daq2_qsys.tcl
projects/daq3/common/daq3_qsys.tcl

This change adds the TLAST signal to the AXI streaming interface
of the source side for Intel targets.
Xilinx based designs already have this since the tlast is part of the
interface definition.
In order to make the signal optional and let the tool connect a
default value to the it, the USE_TLAST_SRC/DEST parameter is
added to the configuration UI. This conditions the tlast port on
the interface of the DMAC.
Xilinx handles the optional signals much better so the parameter
is not required there.

axi_dmac: add tlast to the axis interface for Intel

---

library/axi_dmac/axi_dmac_constr.ttcl

The constraint referred to registers which got renamed,
causing critical warnings.

axi_dmac: Remove unused constraint

---

library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_burst_memory.v
library/axi_dmac/axi_dmac_hw.tcl
library/axi_dmac/axi_dmac_ip.tcl
library/axi_dmac/axi_dmac_transfer.v
library/axi_dmac/request_arb.v

This change adds a diagnostic interface to the DMAC core.
The interface exposes internal information about the core,
information which can't be exposed through AXI registers
due the latency and update rate.
Such information is the fullness of the internal buffer.
For this is exposed in bursts and is driven from the destination
clock domain, as this is reflected in its name.
The signal has a fixed size and is dimensioned by
taking in account the supported maximum number of bursts of 128.

axi_dmac: diagnostic interface in bursts

---

library/axi_dmac/2d_transfer.v
library/axi_dmac/axi_dmac_transfer.v

The index on MSB of addresses was set to 31,
but the width of address in the axi_dmac depends on a parameter.
The mismatch causes issues in the Xilinx simulator which does not extends the
narrower width signal with zeros, instead the wider signal gets 'Z' on its MSBs.
When the address was incremented with the stride it became 'X' due the uninitialized
MSBs.

axi_dmac: fix 2d transfer address width

---

library/axi_dmac/2d_transfer.v
library/axi_dmac/axi_dmac_transfer.v

In MM2S applications like video DMA it is useful to mark the end of the stream
with the TLAST.
The change enables the generation of the TLAST on the last beat of the
last row of the 2d transfer.

axi_dmac: TLAST support for 2d transfers

---

projects/scripts/adi_board.tcl

Two new features for the ad_xcvrcon helper function
* Be able to specify a dedicated device clock. This is necessary for deterministic latency setups
* Be able to provide sparse lane mappings. This is necessary if a design uses more than one transceiver quad, but at least two transceivers quads are not fully used. E.g. 4 lanes with 2 lanes in one quad each.

adi_board.tcl: ad_xcvrcon updates

---

library/axi_dmac/bd/bd.tcl

The round function from tcl is a rounding to nearest. Using it in address
width calculation produces incorrect values.
e.g.
round(log(0xAF000000)/log(2)) will produce 31 instead of 32
The fix is to replace the rounding function with ceiling that guarantees
rounding up.

axi_dmac: fix address width detection

---

library/jesd204/jesd204_rx/Makefile
library/jesd204/jesd204_rx/jesd204_rx_constr.ttcl
library/jesd204/jesd204_rx/jesd204_rx_ip.tcl
library/jesd204/jesd204_tx/Makefile
library/jesd204/jesd204_tx/jesd204_tx_constr.ttcl
library/jesd204/jesd204_tx/jesd204_tx_ip.tcl

In case when the SYSREF is connected to an FPGA IO which has a limitation
on the IOB register IN_FF clock line and the required ref clock is high
we can't use the IOB registers.
e.g. the max clock rate on zcu102 HP IO FF is 312MHz but ref clock is 375MHz;
If IOB is used in this case a pulse width violation is reported.
This change makes the IOB placement selectable in such case or
for targets which don't require class 1 operation.
This could be used also when other primitives are instantiated to capture the SYSREF and IOB would 
cause critical warnings.

jesd204_rx/tx: make SYSREF IOB placement optional

---

library/axi_hdmi_tx/axi_hdmi_tx.v
library/axi_hdmi_tx/axi_hdmi_tx_ip.tcl
projects/adrv9361z7035/common/ccfmc_bd.tcl
projects/common/mitx045/mitx045_system_bd.tcl
projects/common/zc702/zc702_system_bd.tcl
projects/common/zc706/zc706_system_bd.tcl
projects/common/zed/zed_system_bd.tcl
projects/imageon/common/imageon_bd.tcl

Update all carriers/projects bd for configurable video interface:
- common zc702, zc706, zed
- adrv9361z7035/ccfmc_lvds
- imageon

axi_hdmi_tx: Added INTERFACE parameter for selecting the interface type

---

library/jesd204/tb/axi_jesd204_rx_regmap_tb.v
library/jesd204/tb/loopback_tb.v

Currently two of the JESD204 testbenches fail. Not because the IP is broken, but because the testbenches have not been updated with support for the latest features.
Fix them.

jesd204 testbench updates

---

projects/fmcadc5/common/fmcadc5_bd.tcl
projects/fmcadc5/vc707/system_project.tcl

The SYSREF for RX is generated internally,
disable the IOB attribute from it to avoid critical warnings.

fmcadc5: remove SYSREF from IOB

---

library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl
projects/ad9172_fmc_ebz/common/ad9172_fmc_ebz_bd.tcl
projects/ad9172_fmc_ebz/zcu102/Makefile
projects/ad9172_fmc_ebz/zcu102/system_bd.tcl
projects/ad9172_fmc_ebz/zcu102/system_constr.xdc
projects/ad9172_fmc_ebz/zcu102/system_project.tcl
projects/ad9172_fmc_ebz/zcu102/system_top.v

Add support for the AD9172-FMC-EBZ connected to the ZCU102
development kit.

Initial support for AD9172 on ZCU102

---

projects/scripts/adi_board.tcl

Just one VCC or GND xlconstant will be generated for each width. This
way we can avoid having a lot of xlconstant instances with the same
configuration.

Update the VCC/GND instance generation

---

library/common/ad_mem_asym.v
library/util_adcfifo/util_adcfifo.v
library/xilinx/axi_adcfifo/axi_adcfifo_dma.v
library/xilinx/axi_dacfifo/axi_dacfifo_rd.v
library/xilinx/axi_dacfifo/axi_dacfifo_wr.v
library/xilinx/axi_dacfifo/util_dacfifo_bypass.v

These modification should not change the basic functionality of the module. It's just a refactoring to support more asymmetric ratios.
Because the read interface got a read enable port too, update all the ad_mem_asym instances.

Improve the implementation of the asymmetric RAM

---

projects/scripts/adi_project.tcl

In Vivado there is a limit for the number of warnings and errors which are displayed by the tool for a particular error or warning; the default value of this limit is 100. 
This commit overrides the default given limit to 2000.

scripts/adi_xilinx_msg.tcl: Overrides the default msg limit to 2000

---

projects/scripts/adi_tquest.tcl

If the analysis type is not defined the report_timing command will run just a setup analysis.
Run an analysis report for all the four analysis type.

adi_tquest: Improve the timing report

---

library/altera/common/up_rst_constr.sdc

The ad_rst module's SDC constraint have some invalid paths. Because of it all Intel design's timing failed.
This patch should fix this issue.

ad_rst: Fix constraints for Intel designs

---

projects/scripts/adi_board.tcl

Add support for specifying a set of parameter value pairs when
instantiating an IP core to the ad_ip_instance command. This has the
convenience of not having to repeatedly call ad_ip_parameter with the name
of the core that got just created for each parameter that needs to be set.
It is also useful for cases where some parameters have mutually exclusive
values and both (or more) have to be set at the same time.
This also slightly speeds things up. Whenever a parameter is changed the
core needs to be updated and post configuration scripts might run. When
setting all parameters at the same time this only happens once instead of
once for each parameter.
For example the following sequence
ad_ip_instance axi_dmac axi_ad9136_dma
ad_ip_parameter axi_ad9136_dma CONFIG.DMA_TYPE_SRC 0 …

adi_board.tcl: ad_ip_instance: Add support for specifying IP parameters

---

projects/adrv9361z7035/common/adrv9361z7035_bd.tcl
projects/adrv9364z7020/common/adrv9364z7020_bd.tcl
projects/fmcomms2/common/fmcomms2_bd.tcl
projects/fmcomms5/common/fmcomms5_bd.tcl
projects/usrpe31x/system_bd.tcl

Fix warnining regarding SYNC_TRANSFER_START parameter which doesn't
apply when axi_dmac is configured for the tx path.

adrv936x, fmcomms2/5, usrpe31x: Fix warning on the dac path

---

library/util_adcfifo/Makefile
library/util_adcfifo/util_adcfifo.v
library/util_adcfifo/util_adcfifo_hw.tcl
library/util_adcfifo/util_adcfifo_ip.tcl

This improvement will solve a couple of [DRC REQP-1839] warning: The RAMB36E1 has an input control pin  which is driven by a register that has an active asychronous set or reset. This may cause corruption of the memory contents and/or read values when the set/reset is asserted and is not analyzed by the default static timing analysis. It is suggested to eliminate the use of a set/reset to registers driving this RAMB pin or else use a synchronous reset in which the assertion of the reset is timed by default.

util_adcfifo: Synchronize the ad_rst and use it as a synchronous reset

---

projects/adrv9371x/kcu105/system_bd.tcl
projects/adrv9371x/zcu102/system_bd.tcl
projects/daq2/kc705/system_bd.tcl
projects/daq2/kcu105/system_bd.tcl
projects/daq2/vc707/system_bd.tcl
projects/daq2/zc706/system_bd.tcl
projects/daq2/zcu102/system_bd.tcl
projects/daq3/kcu105/system_bd.tcl
projects/daq3/zc706/system_bd.tcl
projects/daq3/zcu102/system_bd.tcl
projects/fmcadc2/vc707/system_bd.tcl
projects/fmcadc5/vc707/system_bd.tcl

The affected projects are (with new depths):
- FMCADC2/VC707 - 16Mb
- FMCADC5/VC707 - 16Mb
- DAQ2/ZC706  - ADC@1GB and DAC@8Mb
- DAQ2/KC705  - ADC@4Mb and DAC@4Mb
- DAQ2/VC707  - ADC@8Mb and DAC@8Mb
- DAQ2/KCU105 - ADC@4Mb and DAC@4Mb
- DAQ2/ZCU102 - ADC@8Mb and DAC@8Mb
- DAQ3/ZC706  - ADC@1GB and DAC@8Mb
- DAQ3/KCU105 - ADC@4Mb and DAC@4Mb
- DAQ3/ZCU102 - ADC@8Mb and DAC@8Mb
- ADRV9371x/KCU105 - DAC@8Mb
- ADRV9371x/ZCU102 - DAC@16Mb

Maximize the depth of each internal adc|dac_fifo instance

---

library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_hw.tcl

The buffers inside the interconnect are sized based on maximum burst sizes
the masters can produce.
For AXI4 the max burst size is 128 but for these projects for the
default burst size of 128 bytes the DMACs are creating only burst of 8 or
16 beats depending on the bus width (128bits and 64 bits respectively).
These burst sizes can fit in the AXI3 protocol where the max burst
length is 16. Therefore the interconnect will be reduced.
The observed reduction is around 4 Mb of block RAM per project.
Another benefit is a better timing closure,
since these buffers reside in the DDR3 clock domain.

daq2/daq3/9371: Use AXI3 for DMAC in Intel projects

---

library/scripts/adi_ip_alt.tcl

The DISPLAY_NAME of a module is supposed to be a short human readable
description of the IP core.
Currently this is set to the name of the IP, which already has its own
property called NAME.
This causes Platform Designer to display the descriptive labels if the IP
core basically as "$ip_core_name ($ip_core_name)".
The value that all current user of ad_ip_create pass for the description
parameter matches this criteria (And not so much the requirements for the
actual DESCRIPTION property).
Change things, so that the DISPLAY_NAME property is set to what is
currently passed as the description parameter.

adi_ip_alt: ad_ip_create: Use 'description' for the DISPLAY_NAME propery

---

library/common/ad_dds_2.v

If DDS_DW is equal to DDS_D_DW there is no signal truncation and
consequentially no rounding should be performed. But the check whether
rounding should be performed currently is for if DDS_DW is less or equal to
DDS_D_DW.
When both are equal C_T_WIDTH is 0. This results in the expression
'{(C_T_WIDTH){dds_data_int[DDS_D_DW-1]}};' being a 0 width signal. This is
not legal Verilog, but both the Intel and Xilinx tools seem to accept it
nevertheless.
But the iverilog simulation tools generates the following error:
ad_dds_2.v:102: error: Concatenation repeat may not be zero in this context.
Xilinx Vivado also generates the following warning:
WARNING: [Synth 8-693] zero replication count - replication ignored [ad_dds_2.v:102]
Change the condition so that truncation is only performed when DDS_DW …

ad_dds_2: Don't try to round if signal is not truncated

---

library/jesd204/axi_jesd204_tx/axi_jesd204_tx_constr.xdc

The constraint for the synchronizer that synchronizes the sync_status
signal of the link only works correctly for the first link. For other links
no timing exception is applied, which leads to timing failures.
Fix this by using a wildcard constraint for the synchronizer reg number.

axi_jesd204_tx: Fix multi-link constraints

---

.gitignore

The system_db folder is autogenerated and contains all the files that are
generated by the Platform Designer tool.
The extension for Intel binary bitstreams is rbf.
Add both of those to the .gitignore since they should not be under version
control and just end up as clutter in `git status` otherwise.

Add generated files for Intel projects to .gitignore

---

projects/motcon2_fmc/common/motcon2_fmc_bd.tcl
projects/motcon2_fmc/zed/system_top.v

- refclk and refclk_rst were used for ethernet IDELAY, but are not needed anymore
- muxaddr_out pins overlap with regular GPIOs in the Zed base design. The XADC mux GPIOs can be controlled through that. Cusomters that want to directly control the pins through XADC IP must modify the design

motcon2_fmc: Remove muxaddr_out, refclk and refclk_rst from system_bd

---

library/axi_dmac/2d_transfer.v
library/axi_dmac/Makefile
library/axi_dmac/address_generator.v
library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_burst_memory.v
library/axi_dmac/axi_dmac_constr.sdc
library/axi_dmac/axi_dmac_constr.ttcl
library/axi_dmac/axi_dmac_hw.tcl
library/axi_dmac/axi_dmac_ip.tcl
library/axi_dmac/axi_dmac_regmap.v
library/axi_dmac/axi_dmac_regmap_request.v
library/axi_dmac/axi_dmac_resize_src.v
library/axi_dmac/axi_dmac_response_manager.v
library/axi_dmac/axi_dmac_transfer.v
library/axi_dmac/data_mover.v
library/axi_dmac/dest_axi_mm.v
library/axi_dmac/dest_axi_stream.v
library/axi_dmac/request_arb.v
library/axi_dmac/request_generator.v
library/axi_dmac/src_axi_mm.v
library/axi_dmac/src_axi_stream.v
library/axi_dmac/src_fifo_inf.v
library/axi_dmac/tb/dma_read_shutdown_tb
library/axi_dmac/tb/dma_read_tb
library/axi_dmac/tb/dma_write_shutdown_tb
library/axi_dmac/tb/dma_write_shutdown_tb.v
library/axi_dmac/tb/dma_write_tb
library/axi_dmac/tb/dma_write_tb.v
library/axi_dmac/tb/regmap_tb
library/axi_dmac/tb/regmap_tb.v

Simulation validation:
Component level testbeches (all pass except the regmap test)
System level testbench covers:
-     single segment partial transfers
-     multisegment partial transfers
-    single segment partial 2D transfers
-    transfer length reporting (1D and 2D)
Hardware validation for regression:
-   DAQ2 - ZC706
-   ADRV9371 - ZC706
-   ADRV9371 - A10GX
Compile only validation for regression: 
all ADI projects

Initial version of DMAC early abort (TLAST handling)

---

library/xilinx/axi_adcfifo/axi_adcfifo_constr.xdc

Used IS_SEQUENTIAL instead of PRIMITVE_SUBGROUP==flop to identify ff related constraints

axi_adcfifo: Fix constraints to apply also to Ultrascale devices

---

projects/scripts/adi_board.tcl

Each individual link of a multi-link has its own sync signal. The top level
sync port that is created by the ad_xcvrcon function is always a single bit
single though.
This results in only the sync signal of the first link being routed while
others are ignored.
To fix this make sure that for multi-link setups the sync port is a vector
port with the width equal to the number of links.
Tested on DAQ2 with NUM_LINKS=1 and on AD9144-FMC-EBZ with NUM_LINKS=2

adi_board.tcl: ad_xcvrcon: Fix width of sync port for multi-link setups

---

library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_regmap.v
library/axi_dmac/data_mover.v

This change will fix the transfer start synchronization mechanism used
in the AXIS streaming and FIFO source interfaces.

axi_dmac: fix transfer start synchronization

---

library/axi_hdmi_tx/axi_hdmi_tx_ip.tcl
projects/adrv9361z7035/common/ccfmc_bd.tcl
projects/common/zc702/zc702_system_bd.tcl
projects/common/zc706/zc706_system_bd.tcl
projects/common/zed/zed_system_bd.tcl

Combine the ready, valid, data and tlast signals in a s_axis interface.
Update for all projects.
Build tested on:
adv7511/zed,zc702/zc706 and adrv9361_z7035/ccfmc.
Run test on adv7511/zc702

Streaming interface for hdmi tx

---

projects/fmcomms2/zc702/system_project.tcl

When we improve timing by modifying the implementation strategies,
the general rule of thumb is "less is always more".
Timing did not fail in synthesis, so we leaving the synthesis
strategy in default.
After several parallel runs with various strategies, the
"Performance_Explore" strategy gave the best result for
implementation.

fmcomms2/zc702: Modify implementation strategy to Performance Exlpore

---

library/axi_ad9144/Makefile
library/axi_ad9144/axi_ad9144_hw.tcl
library/axi_ad9152/Makefile
library/axi_ad9152/axi_ad9152_hw.tcl
library/common/ad_perfect_shuffle.v
library/jesd204/ad_ip_jesd204_tpl_dac/Makefile
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_framer.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_hw.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl

The perfect shuffle is a common operation in data processing. Add a shared
module that implements this operation.
Having this in a shared module rather than open-coding every instance makes
sure that there are clear and well defined semantics associated with the
operation that are the same each time. This should ease review, maintenance and
understanding of the code.
As a first user in this series the JESD204 DAC framer module is updated to use this helper module.
Build and runtime tested on ZC706+DAQ2.

Add perfect shuffle module

---

library/util_dacfifo/util_dacfifo_bypass.v
library/util_dacfifo/util_dacfifo_constr.xdc

Few clean up commits to solve a critical warning generated by a wrongly defined constraint in the util_dacfifo_constr.xdc .

Fix util dacfifo constraints

---

library/axi_ad9361/axi_ad9361_ip.tcl

By default inferred output reset signals have an active low polarity. The
axi_ad9361 rst output signal is active high though. Currently when
connecting it to a input reset with active high polarity will generate an
error in IPI.
Fix this by explicitly marking the polarity of the rst signal as active
high.

axi_ad9361: Mark rst output as active high

---

library/xilinx/common/ad_data_clk.v
library/xilinx/common/ad_data_in.v
library/xilinx/common/ad_data_out.v
library/xilinx/common/ad_mmcm_drp.v
library/xilinx/common/ad_serdes_in.v
library/xilinx/common/ad_serdes_out.v

These primitives are not used or supported by the newer versions of Vivado.
This is the first step in the process of adding a generic encoding for vendor device series and families.

Remove all Xilinx 6 series primitives

---

library/axi_dmac/tb/run_tb.sh

Add support for Vivado's simulator. By default the run script is using
the Icarus simulator.
If the user want to switch to another simulator, it can be explicitly
specify the required simulator tool in the SIMULATOR variable.
Currently, beside Icarus, Modelsim (SIMULATOR="modelsim") and Vivado's
xsim (SIMULATOR="xsim") is supported.

axi_dmac/tb: Add support for xsim

---

library/altera/adi_jesd204/Makefile
library/altera/adi_jesd204/adi_jesd204_glue.v
library/altera/adi_jesd204/adi_jesd204_glue_hw.tcl
library/altera/adi_jesd204/adi_jesd204_hw.tcl
library/altera/jesd204_phy/jesd204_phy_glue_hw.tcl
library/altera/jesd204_phy/jesd204_phy_hw.tcl

On Arria10 there are 6 transceivers in a single bank. If more than 6
transceivers are used these will end up in multiple banks.
The ATX PLL can directly connect to the transceivers in the same bank
through the 1x clock network. To connect to transceivers in another bank it
has to go through a master clock generation block (MCGB) and the xN clock
network.
Add support for instantiating the MCGB if more than 6 lanes are used. In
this case the first 6 transceivers will still have a direct connection to
the PLL while all other transceivers will be clocked by the MCGB.
Note that this requires that the first 6 transceivers are all in the same
bank.
This has been tested with Arria10 SoC Dev Kit and the AD9136-FMC-EBZ and AD9172-FMC-EBZ on Linux.

altera: adi_jesd204: Add support for more than 6 transmit lanes

---

library/axi_dmac/axi_dmac_resize_dest.v
library/axi_dmac/axi_dmac_response_manager.v
library/axi_dmac/request_arb.v
library/axi_dmac/src_fifo_inf.v
library/axi_dmac/tb/dma_read_shutdown_tb.v
library/axi_dmac/tb/dma_read_tb.v
library/axi_dmac/tb/dma_write_shutdown_tb
library/axi_dmac/tb/dma_write_shutdown_tb.v
library/axi_dmac/tb/dma_write_tb
library/axi_dmac/tb/dma_write_tb.v
library/axi_dmac/tb/regmap_tb.v
library/axi_dmac/tb/run_tb.sh

A set of small cleanup patches that fix mostly cosmetic issues with the DMAC core.
This is on top of dev_dma_unaligned_mm.

DMA cleanups

---

projects/scripts/adi_make.tcl
projects/scripts/adi_make_boot_bin.tcl

This is an attempt to ease the life of Windows users (Xilinx), that for some reason can't use GNU make or shell scripts to build the BOOT.BIN
Documentation: https://wiki.analog.com/resources/fpga/docs/build#xilinx_auto_tcl_build

Add adi make(build) scripts

---

library/axi_dmac/bd/bd.tcl

Current implementation does not supports updated versions of Vivado
e.g. 2017.4.1 or 2018.2.1
This fix ignores the update number from the version checking.

axi_dmac: patch version checking

---

projects/adrv9371x/common/adrv9371x_bd.tcl
projects/adrv9371x/kcu105/Makefile
projects/adrv9371x/zc706/Makefile
projects/adrv9371x/zcu102/Makefile

Use the generic TPLs for a better scalability to ease lane number reductions.
Tested on ZC706

adrv9371: use generic TPL

---

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_regmap.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v

Software reads the chanmax register. The TPL for both ADCs and DACs has a variable number of channels. The register should report that correctly.

ad_ip_jesd204_tpl: Fix chanmax reporting for both ADC and DAC

---

library/common/up_adc_common.v
library/common/up_dac_common.v
library/jesd204/ad_ip_jesd204_tpl_adc/Makefile
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc.v
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_ip.tcl
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_regmap.v
library/jesd204/ad_ip_jesd204_tpl_common/up_tpl_common.v
library/jesd204/ad_ip_jesd204_tpl_dac/Makefile
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v

This change will allow software to identify the available JESD framer/deframer setting from the transport layer. 
Tested on ZC706 - AD9317

Expose JESD parameters as registers

---

library/util_axis_fifo/util_axis_fifo.v

The FIFO functions in 'first fall through' mode, adjust the FIFO level generation so it take into account the valid data which sits on the bus, waiting for the sink ready signal.

util_axis_fifo: Fix the FIFO level generation in ASYNC mode

---

library/xilinx/util_adxcvr/util_adxcvr.v
library/xilinx/util_adxcvr/util_adxcvr_xch.v
library/xilinx/util_adxcvr/util_adxcvr_xcm.v

Added Initial support for QPLL1.
The DAQ2/ADRV9009 on ZCU102 were tested with the default software and the HDL changes are backwards compatible.

util_adxcvr: Initial commit for QPLL1 support (GTH3 and GTH4)

---

library/axi_adc_trigger/axi_adc_trigger.v

The old threshold comparison was on unsigned numbers.
The ADC data is 4 sign extension bits and 12 data bits.
One of the problems was that before the comparison only bit 16 was inverted from the ADC and limit data.
The second problem was that for a pass-through condition, only data greater or smaller then the limit was taken into consideration. In the case that data is equal with the limit, the trigger condition will be acknowledged one clock cycle after the actual pass through.
Furthermore, using a two's complement comparison on fewer bits will give better resource utilization.
Tested on m2k rev C.

M2k adc trigger fix

---

library/common/up_dac_common.v

Patch the typo introduced in a previous commit while attempting the
address space reduction.
Tested on: FmComms2 + Zc706

up_dac_common: fix address decoding

---

library/axi_rd_wr_combiner/axi_rd_wr_combiner.v

The DMAC is relying on the rlast signal that marks the end of a burst.
Tested on : M2K

axi_rd_wr_combiner: Add rlast to the AXI MM interface

---

projects/scripts/adi_board.tcl

In the current form, when connecting a master to the HP ports all
available slave address spaces are mapped to the master (DDR_*, PCIE*, OCM,
QSPI)
Let the PL masters have access only to the DDR_LOW and DDR_HIGH address
spaces to avoid unnecessary resource usage and increase timing margin.

scripts/adi_board.tcl: fix HP address mappings for ZynqMP

---

library/axi_i2s_adi/axi_i2s_adi_ip.tcl

ip now sets the xdc to late so that the timing constraints are set in the correct context

axi_i2s_adi: fixed xdc

---

projects/common/kcu105/kcu105_system_bd.tcl
projects/m2k/common/m2k_bd.tcl
projects/pluto/system_bd.tcl
projects/scripts/adi_board.tcl

Replace memory axi_interconnect with axi_smartconnect IP. VCU118 high speed designs only work with the smartconnect IP

Axi smartconnect

---

.gitignore
Makefile
library/axi_adc_decimate/Makefile
library/axi_adc_decimate/axi_adc_decimate_ip.tcl
library/axi_mc_controller/Makefile
library/axi_mc_controller/axi_mc_controller_constr.xdc
library/axi_mc_controller/axi_mc_controller_ip.tcl
library/axi_mc_current_monitor/Makefile
library/axi_mc_current_monitor/axi_mc_current_monitor_constr.xdc
library/axi_mc_current_monitor/axi_mc_current_monitor_ip.tcl
library/jesd204/axi_jesd204_rx/Makefile
library/jesd204/axi_jesd204_rx/axi_jesd204_rx_ip.tcl
library/jesd204/axi_jesd204_rx/axi_jesd204_rx_ooc.ttcl
library/jesd204/axi_jesd204_tx/Makefile
library/jesd204/axi_jesd204_tx/axi_jesd204_tx_ip.tcl
library/jesd204/axi_jesd204_tx/axi_jesd204_tx_ooc.ttcl
library/util_clkdiv/Makefile
library/util_clkdiv/util_clkdiv_ip.tcl
library/util_clkdiv/util_clkdiv_ooc.ttcl
library/util_dacfifo/Makefile
library/util_dacfifo/util_dacfifo_ip.tcl
library/util_dacfifo/util_dacfifo_ooc.ttcl
projects/motcon2_fmc/zed/system_constr.xdc
projects/scripts/adi_project.tcl
projects/scripts/project-xilinx.mk

**Add support for OOC synthesis flow** through ADI_USE_OOC_SYNTHESIS environment variable 
Add common IP cache support to reuse synthesis results from one project to another
Usage:
from command line set any value to the ADI_USE_OOC_SYNTHESIS variable
e.g. export ADI_USE_OOC_SYNTHESIS=y
Tested:
All Xilinx projects compiled with Vivado 2018.2
**Add support for incremental compilation** 
Usage: 
on  a previously built project run make with the following option:
make MODE=incr

OOC synthesis flow support

---

library/axi_ad5766/axi_ad5766.v
library/axi_dmac/axi_dmac_burst_memory.v
library/axi_dmac/axi_dmac_reset_manager.v
library/axi_dmac/request_arb.v
library/jesd204/axi_jesd204_rx/jesd204_up_ilas_mem.v
library/jesd204/axi_jesd204_rx/jesd204_up_rx_lane.v
library/jesd204/axi_jesd204_tx/jesd204_up_tx.v
library/jesd204/jesd204_tx/jesd204_tx_ctrl.v
library/spi_engine/spi_engine_offload/spi_engine_offload.v
library/util_axis_fifo/address_gray.v
library/util_axis_fifo/util_axis_fifo.v
library/util_cdc/sync_bits.v
library/util_cdc/sync_data.v
library/util_cdc/sync_event.v

Added changes from Nicholas Pillitteri njpillitteri@gmail.com (pull request #259) to simplify the merge, without the need for a rebase on his pull request

sync_bits: Change I/O names of wires "in" and "out" for VHDL users

---

projects/scripts/project-xilinx.mk

Clear the reference checkpoint if the incremental compilation is not
selected through the make option. Other case the scripts will silently
use the reference.dcp checkpoint if that exists.

scripts: patch incremental compile

---

library/axi_dmac/axi_dmac_ip.tcl

The interrupt controller from Microblaze based projects requires that
all its inputs have attributes which define the sensitivity of the
interrupt line. Other case it defaults to EDGE_RISING which is not the
case for DMAC, leading to incorrect interrupt reporting and handling in
case of such projects.
Tested on 
VCU118 : dual_ad9208

axi_dmac: infer interrupt line for Xilinx projects

---

projects/common/zc706/zc706_plddr3_adcfifo_bd.tcl
projects/common/zc706/zc706_plddr3_dacfifo_bd.tcl

The AXI_ADDRESS_LIMIT parameter will define the high address of the interface. The ZC706 has a 1Gbyte DDR3 on the PL side. Modify the address limit, so we can use the overall size of the memory.

PL DDR3 size is 1Gbyte

---

projects/scripts/adi_project.tcl

fixed timing paths evaluation where no timing paths would lead to a failure to export the .hdf

scripts: updated adi_project.tcl

---

library/jesd204/scripts/jesd204.tcl

When only one converter is used there is no need for concatenation and
slicer cores. In that case the TPL will connect to port 0 from the
application layer.
Tested with: AD9172

TPL wrapper support for one converter

---

projects/scripts/adi_project.tcl

Look for undefined clocks which do not show up in the timing summary
therefore can lead to silent failures.
If clocks are not defined they are not analyzed during the timing
checks.

scripts:adi_project.tcl: add check for missing clock definitions

---

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_hw.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_hw.tcl

When TPLs are directly instantiated in QSYS they fail to build due dependency issues. 
Tested with AD9172+A10SoC

jesd204:tpl: add missing dependencies for Intel

---

projects/scripts/adi_project.tcl
projects/scripts/adi_project_alt.tcl

Allow the top level files to have parameters.
Pass the parameters from system_project.tcl to the Vivado/Quartus project and
to the block design scripts through ad_project_params variable.
Usage:
1. create a project with a list of parameters:
adi_project_xilinx  my_project [list PARAM_A PARAM_A_VALUE PARAM_B PARAM_B_VALUE]
or
adi_project_altera  my_project [list PARAM_A PARAM_A_VALUE PARAM_B PARAM_B_VALUE]
2. access the parameter in QSYS or block design through the $ad_project_params variable
e.g
set PARAM_A $ad_project_params(PARAM_A)
set PARAM_B $ad_project_params(PARAM_B)
3. In system_top.v use PARAM_A and PARAM_B as parameters/generics
**Example project:** https://github.com/analogdevicesinc/hdl/tree/dev_ad9136_fmc/projects/dac_fmc_ebz

Top levels with parameters

---

projects/scripts/adi_project.tcl

Since we parse the output of a command it is likely to break in the
future if the format of the sting changes. Create a warning for that case.
Required by some of the ZCU102 projects which currently fail to build.

scripts/adi_project.tcl: make search for undefined clocks more robust

---

projects/common/zc702/zc702_system_bd.tcl
projects/common/zc706/zc706_system_bd.tcl
projects/common/zed/zed_system_bd.tcl

The SYNC_TRANSFER_START parameter is disabled in this configuration
of the axi_dmac, trying to set the parameter will generate a warning.

common zed, zc702 and zc706: Remove parameter assignment

---

projects/pluto/system_bd.tcl

After the commit that removed the interconnects from HP ports
in order to reduce utilization; the directly connected DMAs were not
assigned to a specific range and address.
This change adds back the address and offset.
Tested on Pluto.

pluto: Fix the adc/dac dma mapping to to ps7 S_AXI_HP1/S_AXI_HP2

---

projects/adrv9009/common/adrv9009_bd.tcl
projects/adrv9371x/common/adrv9371x_bd.tcl
projects/scripts/adi_board.tcl

Delete deprecated proc called ad_reconct. In order to do this, we had to fix two ad_xcvrcon process call in the adrv9371x and adrv9009 block design.

Clean adi_board.tcl

---

library/axi_fmcadc5_sync/axi_fmcadc5_sync_constr.xdc
projects/adrv9361z7035/common/ccfmc_constr.xdc
projects/common/ac701/ac701_system_constr.xdc
projects/common/kc705/kc705_system_constr.xdc
projects/common/kcu105/kcu105_system_constr.xdc
projects/common/vc707/vc707_system_constr.xdc
projects/common/vcu118/vcu118_system_constr.xdc
projects/common/zc702/zc702_system_constr.xdc
projects/common/zc706/zc706_system_constr.xdc
projects/common/zcu102/zcu102_system_constr.xdc
projects/common/zed/zed_system_constr.xdc
projects/fmcomms5/zc702/system_constr.xdc
projects/fmcomms5/zc706/system_constr.xdc
projects/fmcomms5/zcu102/system_constr.xdc

For SPI we use two approached based on the processing system:
Zynq based systems:  create a 50 MHz clock on the output of the primitive
MicroBlaze based systems:  create a generated clock on the output of the SPI cores
Testing: all affected projects compiled.

fix missing clock definitions

---

projects/common/a10gx/a10gx_system_qsys.tcl

Add a clock crossing bridge for the interfaces that runs on a different
clock than the emif_user_clk.
This way we can simplify the main interconnect, and prevent occasional
timing violations.
Tested with DAQ2.

A10GX Optimise the base design to avoid timing issues

---

projects/fmcomms11/common/fmcomms11_bd.tcl
projects/fmcomms11/zc706/system_bd.tcl
projects/fmcomms11/zc706/system_constr.xdc
projects/fmcomms11/zc706/system_top.v

A few minor patch for FMCOMMS11:
- connect dac_fifo_bypass to GPIO[60]
- fix the DAC data path (define connections between upack and FIFO)

Fix FMCOMMS11

---

library/axi_ad9361/axi_ad9361.v
library/axi_ad9361/axi_ad9361_hw.tcl
library/axi_ad9361/xilinx/axi_ad9361_cmos_if.v
library/axi_ad9361/xilinx/axi_ad9361_lvds_if.v
projects/fmcomms5/common/fmcomms5_bd.tcl

Define a MIMO_ENABLE paremeter for the core, which will insert
and additional deskew logic to prevent timing issues comming from
the clock skew differences of two or multiple AD9361.

axi_ad9361: Define a MIMO enabled parameter

---

projects/ad9265_fmc/common/ad9265_bd.tcl
projects/ad9434_fmc/common/ad9434_bd.tcl
projects/ad9739a_fmc/common/ad9739a_fmc_bd.tcl

After the clock/reset restructuring, there were a couple of leftovers, the following projects are fixed with this patch:
- AD9434
- AD9625
- AD9739A

Fixing resets for various projects

---

library/axi_fmcadc5_sync/axi_fmcadc5_sync_constr.xdc

Rename the clock so it won't conflict with the main spi clock name.
Tested
Comiled VC707 project.

axi_fmcadc5_sync: rename generated spi clock

---

library/util_clkdiv/util_clkdiv_constr.xdc

Vivado propagates and auto derives the clocks, however if multiple
instances of this components are used the names of the propagated clock
change while the constraint file has fixed name which will match only
the clocks from the first instance letting the second instance of the
clock div without exception.
Tested on Zed + fmcomms2

util_clkdiv: fix for multiple instances

---

library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v

This patch will fix the following warning:
[Synth 8-689] width (16) of port connection 'up_axi_awaddr'
does not match port width (12) of module 'up_axi'

ad_ip_jesd204_tpl_dac: Quick fix

---

projects/daq3/vcu118/system_bd.tcl

This patch should fix the timing issue on DAQ3 VCU118.
Apparently this constraint will cause more harm than good. The tool will
try to prevent an invalid hold violation by increasing the net delay,
causing a setup violation on the same path. (inside the smart connect)
See more info here:
https://forums.xilinx.com/t5/AXI-Infrastructure/Smartconnect-and-Synchronous-Clock-Domain-Crossing-Issues/td-p/904824

daq3:vcu118: Delete constraint related to smart connect

---

library/axi_dmac/axi_dmac_ip.tcl

The unused AXI stream signals have to be added to the AXIS interface so
they don't hang loose on the IP in the block design.
Tested compile only with:  
pluto, usrp310x, daq2/zc706

axi_dmac:axi_dmac_ip: Fix AXI Stream signals bundle

---

projects/adrv9361z7035/common/ccbox_constr.xdc

adrv9361z7035/ccbox: Keep by default in powerdown the 12V power supply.
Because of build hazards, the power supply can be randomly turned on for diferent carriers, when the enable pin is left floating.
Tested on adrv9361 ccbox.

Set default rfpack 12 power supply

---

library/scripts/adi_env.tcl
projects/common/intel/sys_gen.tcl
projects/scripts/adi_env.tcl
projects/scripts/adi_project_intel.tcl

Our internal repository was changed from phdl to ghdl. Update the
adi_env.tcl scripts and other scripts, which depends on the $ad_ghdl_dir
variable. This way the tools will see all the internal IPs too.

Update adi_env.tcl scripts

---

projects/common/zc702/zc702_system_constr.xdc
projects/common/zc706/zc706_system_constr.xdc
projects/common/zcu102/zcu102_system_constr.xdc
projects/common/zed/zed_system_constr.xdc
projects/m2k/standalone/system_constr.xdc
projects/pluto/system_constr.xdc

According to data sheets the EMIO SPI controller maximum frequency is
just 25MHz. Constrain the SPI clock accordingly.

zynq:all: fix SPI clock constraint

---

library/common/ad_bus_mux.v
projects/adrv9009/common/adrv9009_bd.tcl
projects/adrv9009/zc706/system_project.tcl
projects/adrv9009/zc706/system_top.v
projects/adrv9009/zcu102/system_project.tcl
projects/adrv9009/zcu102/system_top.v
projects/adrv9371x/common/adrv9371x_bd.tcl
projects/adrv9371x/kcu105/system_project.tcl
projects/adrv9371x/kcu105/system_top.v
projects/adrv9371x/zc706/system_project.tcl
projects/adrv9371x/zc706/system_top.v
projects/adrv9371x/zcu102/system_project.tcl
projects/adrv9371x/zcu102/system_top.v
projects/common/xilinx/adi_fir_filter_bd.tcl
projects/scripts/adi_board.tcl

Add generic fir filters(decimation/interpolation by a factor of 8) for adrv9371x and adrv9009.
The filters are bypassed by default. To activate them set:
- gpio[61](EMIO) - decimation filter
- gpio[62](EMIO) - interpolation filter
Tested on:
- adrv9371 zc706 and zcu102
- adrv9009 zcu102

Adrv9xxx add fir filters

---

library/axi_dac_interpolate/axi_dac_interpolate.v
library/axi_dac_interpolate/axi_dac_interpolate_filter.v
library/axi_dac_interpolate/axi_dac_interpolate_reg.v
projects/m2k/common/m2k_bd.tcl

The previous channel sync mechanism was simply holding the transmission by
pulling down the dma_rd_en of the two DMAs for each channel(set reg 0x50). After a
period of time (that will take the two DMAs to have the data ready to move)
the dma_rd_en was set for both channels, resulting in a synchronized start.
This mechanism is valid when the two channels are streaming the same
type of data (constant, waveform, buffer or math) at close frequencies.
Streaming 10MHz on a channel and 100KHz on the second one will result
in different interpolation factors being used for the two channels.
The interpolation counter runs only when the dma_transfer_suspended(reg 0x50)
is cleared. Because of this, different delays are added by the interpolation
counter one DMA with continuous dma_rd_en will have …

Fix m2k dac channel sync

---

library/common/ad_3w_spi.v

The module is compliant with the SPI interface specified in ADI-SPI technical specification.
(See doc [here](https://wiki.analog.com/_media/resources/technical-guides/adispi_rev_1p0_customer.pdf))

A 4-wire to 3-wire SPI converter

---

library/axi_adc_trigger/axi_adc_trigger.v

Currently trigger out pin is hold for 1ms in the next transition state(t+1) state(0 or 1), but not in the state that follows (t+2). This commit fixes this issue.
Tested on M2k.

 axi_adc_trigger: Fix trigger out glitches

---

library/axi_adc_trigger/axi_adc_trigger.v
library/axi_logic_analyzer/axi_logic_analyzer.v
library/axi_logic_analyzer/axi_logic_analyzer_trigger.v
projects/m2k/standalone/system_constr.xdc

Equalize the delay paths for data and trigger between the axi_adc trigger and axi_logic_analyzer.
This will increase a bit the utilization, gaining reduced the trigger source delay uncertainty and reduce the software effort in compensating for that delay.
Tested on M2k.

Dev m2k equal data delay

---

projects/ad9208_dual_ebz/vcu118/system_bd.tcl
projects/ad9208_dual_ebz/vcu118/system_constr.xdc
projects/common/vcu118/vcu118_system_constr.xdc

Minimize skew on synchronous CDC timing paths between clocks originating
from the same MMCM source. (sys_mem_clk and sys_cpu_clk)
This is required mostly by the smart interconnect.
The CLOCK_DELAY_GROUP property must be applied directly to the output net of BUFGs.
See: https://forums.xilinx.com/t5/AXI-Infrastructure/Smartconnect-and-Synchronous-Clock-Domain-Crossing-Issues/td-p/904824
Tested with all VCU118 project. Compile only.

common/vcu118: Balance clocks

---

projects/cn0506_rgmii/zcu102/README.rst

cn0506_rgmii/zcu102: Fix README typo.
The daughter card uses FMC1 because of the global clock pins distribution FMC0.

cn0506_rgmii/zcu102: Fix README typo

---

library/axi_ad9361/axi_ad9361.v
library/axi_ad9361/axi_ad9361_tx.v
library/axi_ad9361/intel/axi_ad9361_cmos_if.v
library/axi_ad9361/intel/axi_ad9361_lvds_if.v
library/axi_ad9361/xilinx/axi_ad9361_cmos_if.v
library/axi_ad9361/xilinx/axi_ad9361_lvds_if.v
projects/fmcomms5/common/fmcomms5_bd.tcl

this commit allows the following:
- having fixed latency from Tx to Rx application layer interface of axi_ad9361  
- having synchronized Rx channels at sample level from both ad9361 in fmcomms5
Tested with: 
zc706 + fmcomms2
zc706 + fmcomms5
zcu102 + fmcomms2 
zcu102 + fmcomms5

ad9361 latency fixes

---

library/intel/axi_adxcvr/axi_adxcvr_up.v

Add device spec register for axi_adxcvr core.
Tested on daq2_a10gx hardware.

intel/axi_adxcvr_up: Add device spec register

---

library/spi_engine/axi_spi_engine/axi_spi_engine.v
projects/adaq7980_sdz/common/adaq7980_bd.tcl

The pulse period had a fixed value. Therefore, in order to be able
to configure it from the software, a 32b register pulse_period_reg
was added in axi_spi_engine. Also, to generate the pulse, the
output register pulse_gen_loadc was added.

spi_engine: Update pulse generation

---

projects/adrv9009_zu11eg_som/carrier_bd.tcl
projects/adrv9009_zu11eg_som/system_bd.tcl

i2s mclk generated by ps instead of axi clkgen ip. ADAU1761 expects a free running clock and the i2s driver was switching the axi clkgen ip off which was causing issues.

adrv9009_zu11eg_som: i2s fix

---

projects/adrv9371x/kcu105/system_bd.tcl
projects/daq2/kcu105/system_bd.tcl
projects/daq3/kcu105/system_bd.tcl

Update GTH3 parameters according to a 10Gbps link from the Transceiver
Wizard.
Without this fix none of the JESD projects Tx side is working (ADRV9371, DAQ2, DAQ3)
2018_r2 already had this fix but was not ported to master: https://github.com/analogdevicesinc/hdl/commit/482933bc49c578411a8eb35e62bfcf7e9be6029e
Tested on KCU105  + DAQ2

adrv9371/daq2/daq3:kcu105: patch GTH3 CPLL parameters

---

projects/dac_fmc_ebz/common/config.tcl
projects/dac_fmc_ebz/zc706/system_bd.tcl
projects/dac_fmc_ebz/zcu102/system_bd.tcl

A configuration can be selected when calling make e.g.:
make ADi_DAC_DEVICE=AD9144 ADI_DAC_MODE=04
Build tested on zcu102.

dac_fmc_ebz config device and mode at build

---

library/common/ad_csc_CrYCb2RGB.v
library/common/ad_csc_RGB2CrYCb.v
library/common/ad_ss_444to422.v

Local parameters can not be used in port definitions. Various synthesizers do not support this and can generate errors.

Fix port definition for some common modules

---

projects/ad7134_fmc/common/ad7134_bd.tcl

The initial SPI Engine framework supported data transfers of maximum 24b width. In order to enlarge it to 32b, the following changes were made: the data_width parameter was set to 32 for an adc_resolution of 16 or 24 bits and to 64 for an adc_resolution of 32 bits. Also, the upscaler IP was reoved, as it was no more needed. Thus, the design supports resolutions of 16/24/32 bits.

ad7134: Change maximum data width from 24b to 32b

---

projects/ad_fmclidar1_ebz/a10soc/system_project.tcl

The project is using the FMCA connector of the board. Make sure that all
the carrier re-work is related to the FMCA connector.

ad_fmclidar1_ebz/a10soc: Fix the comment about the carrier re-work

---

projects/scripts/adi_project_xilinx.tcl
projects/scripts/project-xilinx.mk

Add commands to generate one extra resource utilization file, in CSV format.
New commands are executed only if ADI_GENERATE_UTILIZATION environment variable is set.

adi_project_xilinx.tcl: Add commands to generate extra resource utilization files

---

library/spi_engine/spi_engine_execution/spi_engine_execution.v
projects/ad77681evb/common/ad77681evb_bd.tcl
projects/ad77681evb/zed/system_constr.xdc
projects/ad77681evb/zed/system_top.v

The second ADC was removed from the project, as the EV-AD7768-1FMCZ evaluation
board contains only one ADC. Therefore, all the IPs related to the
second ADC have been removed, too.

ad7768-1evb: Remove ADC2 and update spi engine framework

---

projects/adrv9009zu11eg/adrv2crr_fmc/Makefile
projects/adrv9009zu11eg/adrv2crr_fmc/system_bd.tcl
projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl
projects/adrv9009zu11eg/common/adrv9009zu11eg_constr.xdc

v2: Updated after name change. Decreased SPI clock speed to meet timing.

adrv9009_zu11eg_som: Add axi_sysid

---

projects/fmcjesdadc1/kc705/system_constr.xdc
projects/fmcjesdadc1/vc707/system_constr.xdc
projects/fmcjesdadc1/zc706/system_constr.xdc

The rx_div_clk should have a frequency of 125MHz, as the maximum lane
rate is 5Gbpsb (5Gbps/40=125MHz). Therefore, the period of rx_div_clk
needs to be changed from 6.40, which corresponds to a frequency of
156.25 MHz, to 8.00 in order to obtain a 125MHz frequency.

fmcjesdadc1: Change rx_div_clk to 125MHz

---

library/axi_adc_trigger/axi_adc_trigger.v
library/axi_adc_trigger/axi_adc_trigger_ip.tcl
library/axi_adc_trigger/axi_adc_trigger_reg.v
library/axi_logic_analyzer/axi_logic_analyzer.v
library/axi_logic_analyzer/axi_logic_analyzer_reg.v
projects/m2k/common/m2k_bd.tcl

Waiting on trigger holdoff to be merged.
-Fix "trigger jitter"
-Fix data alignment" - The data was captured with two samples earlier than expected when using sampling frequencies slower than the maximum(100MSPS).
Tested on m2k.

Fix trigger to data alignment on ADC path 

---

projects/daq3/zcu102/system_top.v

gpio_bd_i  is an  input should not be driven with logic.

daq3:zcu102: fix GPIO double drive

---

projects/common/vcu118/vcu118_system_bd.tcl
projects/common/vcu118/vcu118_system_constr.xdc

The DDR controller for C2 for is much closer to the transceivers which
connect to the FMCp connector so designs does not have to span over all
three SLRs just over two reducing implementation and timing closure effort.
Tested compile only on dual_ad9208 and daq3. 
Tested on hardware with non hdl projects.

common:vcu118: move system memory to DDR C2

---

library/util_pack/util_cpack2/util_cpack2.v
library/util_pack/util_cpack2/util_cpack2_ip.tcl
library/util_pack/util_upack2/util_upack2.v
library/util_pack/util_upack2/util_upack2_ip.tcl

Add 32 channel for upack and cpack cores. Useful in JESD framework where L=16 and M = 32
Tested 32 channels in simulation and hardware.

util_pack:  support for 32 channels

---

projects/scripts/adi_board.tcl

When channels are not swapped in groups of four but are completely out of order
the common control channel can't be reordered based on the index of the
channel.

adi_board.tcl:ad_xcvrcon: do not reorder common control

---

library/util_adcfifo/util_adcfifo.v

Read pointer should be always behind the write pointer except when it
reaches the last memory location where the writer stops.
Tested in simulation and hardware.

util_adcfifo: fix read pointer

---

projects/common/xilinx/adi_fir_filter_bd.tcl
projects/common/xilinx/adi_fir_filter_constr.xdc

The GPIO, which activates the decimation and interpolation filters was not synchronized to the filter core clock, causing timing violation on KCU105.

Fix filter control GPIO

---

projects/dac_fmc_ebz/common/dac_fmc_ebz_bd.tcl
projects/dac_fmc_ebz/zcu102/system_top.v

:bug: Pass through FIFO bypass GPIO signal
:bug: Create dummy ports only for unused lanes

Bugfixes for dac_fmc_ebz; unused lanes and bypassing FIFO 

---

library/axi_clkgen/bd/bd.tcl

A typo prevents the usage of second clock output.

library/axi_clkgen: Fix second clock output

---

projects/ad40xx_fmc/common/ad40xx_bd.tcl
projects/ad40xx_fmc/zed/system_constr_ad40xx.xdc
projects/ad40xx_fmc/zed/system_constr_adaq400x.xdc

The upscaler IP is no more needed, as the SPI Engine framework supports data transfers larger than 16 bits. Also, the AXI SPI Engine IP has been renamed to axi_regmap, which is more suggestive. 
Because the SDO_SHIFT_REG is initialized once at the beginning of the SPI transfer, increase the timing margin for the REG so we can use higher spi_clk frequency. The corresponding multicycle path constraints have been added in both xdc.

ad40xx: Remove redundant upscaler IP

---

library/intel/adi_jesd204/adi_jesd204_hw.tcl
library/intel/jesd204_phy/jesd204_phy_glue_hw.tcl
library/intel/jesd204_phy/jesd204_phy_hw.tcl

A new option was added to tcl scripts to allow the use of x6/xN clock network (bonded mode) rather than x1/xN clock network (non-bonded mode).
This option can solve routing issues as "Error (14566): The Fitter cannot place 1 periphery component(s) due to conflicts with existing constraints (1 LC_PLL_MUX_CLUSTER(s))"
This new feature has been successfully tested on custom hardware (https://b-com.com/fr/bcom-software-radio-5G-SAT) featuring two AD9136 and AD9689 connected to an Arria 10AX066K3F40.

intel/adi_jesd204: bonded clock network support

---

library/scripts/adi_ip_xilinx.tcl

Bus sizes often depend on parameters. In such cases the physical indexes
of the interfaces from the multi bus must be calculated based on parameters.
For each interface expose the formula that calculates the indexes to the
block design.
Tested with JESDC, VCU118, MxFE
Needed by JESD204C

scripts/adi_ip_xilinx.tcl: add variable width for multi bus interfaces

---

projects/ad40xx_fmc/common/ad40xx_bd.tcl

As the supported ADC resolution of AD40XX is 16/18/20b, the data width should be 32 for a resolution below 32b and 64 for a resolution higher than 32b.

ad40xx: Fix data_width definition

---

library/xilinx/common/ad_rst_constr.xdc

critical warnings were caused by this file when the ad_rst.v instantiation
was done using generate depending on a parameter (i.e. axi_spi_engine)

ad_rst_constr: Added the quiet option

---

projects/ad_fmclidar1_ebz/a10soc/system_project.tcl
projects/ad_fmclidar1_ebz/zc706/system_constr.xdc
projects/ad_fmclidar1_ebz/zcu102/system_constr.xdc

The IO location of the laser_driver_otw_n was moved from FMC_HPC_LA27_N
to FMC_HPC_LA31 (laser_gpio[12]).
laser_gpio[11:0] assignments were shifted with one bit to MSB, and laser_gpio[0]
got the old location of the laser_driver_otw_n.

Lidar: update the IO constraints to revB

---

projects/cn0506_mii/a10soc/system_project.tcl
projects/cn0506_mii/zc706/system_constr.xdc
projects/cn0506_mii/zcu102/system_constr.xdc
projects/cn0506_mii/zed/system_constr.xdc

Because of the rmii mode requirements(external 50MHz clock), the board will have the rx_err signal replaced on the FMC connector by the 50MHz external clock (D08/D20).
The rx_er will be shifted to the D9/D21 pins.

cn0506_mii Updates for Rev B board

---

projects/ad40xx_fmc/zed/Makefile
projects/ad40xx_fmc/zed/system_project.tcl
projects/ad9208_dual_ebz/vcu118/Makefile
projects/ad9208_dual_ebz/vcu118/system_project.tcl
projects/cn0506_mii/a10soc/Makefile
projects/cn0506_mii/a10soc/system_project.tcl
projects/cn0506_mii/zc706/Makefile
projects/cn0506_mii/zc706/system_project.tcl
projects/cn0506_mii/zcu102/Makefile
projects/cn0506_mii/zcu102/system_project.tcl
projects/cn0506_mii/zed/Makefile
projects/cn0506_mii/zed/system_project.tcl
projects/cn0506_rgmii/a10soc/Makefile
projects/cn0506_rgmii/a10soc/system_project.tcl
projects/cn0506_rgmii/zc706/Makefile
projects/cn0506_rgmii/zc706/system_project.tcl
projects/cn0506_rgmii/zcu102/Makefile
projects/cn0506_rgmii/zcu102/system_project.tcl
projects/cn0506_rgmii/zed/Makefile
projects/cn0506_rgmii/zed/system_project.tcl

The name of the project generated by system_project.tcl should be the same with the name of the project folder.

Rename projects for consistency

---

library/jesd204/jesd204_tx/jesd204_tx.v
library/jesd204/jesd204_tx/jesd204_tx_hw.tcl

This change adds an option for pipe-lining the Tx link layer towards physical layer for better timing closure on multi SLR devices.
Tested on non-public hardware.

jesd204_tx: add output pipeline stage

---

projects/dac_fmc_ebz/common/config.tcl

Fix typo for 916x family.
Tested compile only.

dac_fmc_ebz/common/config.tcl: fix typo

---

projects/cn0506_rgmii/zcu102/system_constr.xdc

This commit fixes the critical warning regarding the missing clock
definitions.
- Defined MDC(MDIO) clocks
- Set false path on(to) the ps8 MDIO input pins. There are synchronization
stages in the GMII to RGMII converter for the CDC between the 375M refclk
and 2.5M MDC clock domains.
Tested on cn0506_zcu102.

cn0506_rgmii: Fix no clock defined warnings

---

projects/ad77681evb/common/ad77681evb_bd.tcl

The maximum accepted frequency for spi clock is 20MHz. In order to obtain this value, the clock connected to spi_clk will be set to 40MHz and the prescaler will be set to 0. This will produce a division by 2 of the spi_clk, thus resulting a 20MHz spi clock.

ad77681evb: Set spi_clk to 40MHz

---

projects/common/vcu118/vcu118_plddr4_adcfifo_bd.tcl
projects/common/vcu118/vcu118_plddr4_dacfifo_bd.tcl

Use 1GB from the DDR4 for either ADC or DAC sample buffering.
Max theoretical bandwidth of 19.2 GB/s
Tested with vcu118/mxfe

common:vcu118: support for plddr4 adc and dac fifo

---

projects/dac_fmc_ebz/a10soc/system_top.v
projects/dac_fmc_ebz/zc706/system_top.v
projects/dac_fmc_ebz/zcu102/system_top.v

spi_en is active ...
... high for AD9135-FMC-EBZ, AD9136-FMC-EBZ, AD9144-FMC-EBZ,
... low for AD9171-FMC-EBZ, AD9172-FMC-EBZ, AD9173-FMC-EBZ
Tested with AD9144 and ZCU102

dac_fmc_ebz: drive spi_en pin automatically based on FMC board selected

---

library/axi_dac_interpolate/axi_dac_interpolate.v
library/axi_dac_interpolate/axi_dac_interpolate_filter.v
projects/m2k/common/m2k_bd.tcl

The previous mechanism was "probing" the DMAs for valid data. Better said,
each interpolation channel enabled it's DMA until a valid data was received,
then it disabled the DMA read and waited for the adjacent channel(DMA) to
receive a valid data. Only when for both channels had valid data on the
DMAs interfaces was the transmission started. This added an undesired and
redundant complexity to the interpolation channels. Furthermore, for continuous
transmission, using the above mechanism lead to a fixed phase(sample)
shift between the two channels at each start.
By using the streaming mechanism the interface is simplified and the
above problems are solved.
Tested on m2k.

m2k: use DMA streaming interface

---

projects/ad_fmclidar1_ebz/common/ad_fmclidar1_ebz_qsys.tcl

Fix the SPI interface configuration for the AFE's ADC.

LiDAR A10SOC: Fix AFE's SPI polarity

---

projects/fmcomms8/zcu102/system_constr.xdc

The maximum SPI rate set to 10MHz, as at 40 MHz it doesn't meet timing

fmcomms8: Fix SPI timing

---

projects/ad_fmclidar1_ebz/a10soc/system_project.tcl
projects/ad_fmclidar1_ebz/a10soc/system_top.v
projects/ad_fmclidar1_ebz/common/ad_fmclidar1_ebz_qsys.tcl

The AFE's I2C interface should be pin-multiplexed to the FPGA. Also, add
a bidirectional IO buffer for the interface, and make sure it has weak
pull-up resistors.

LiDAR A10SOC: Fix AFE's I2C interface

---

library/scripts/adi_xilinx_device_info_enc.tcl

Add definition for new ultrascale device packages.
The package information is used by software for xcvr calibration.
At the moment, the factors that are influencing the calibration for the new
packages are not clear.

adi_xilinx_device_info_enc: Add new packages

---

library/common/ad_iqcor.v
library/jesd204/ad_ip_jesd204_tpl_dac/Makefile
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_channel.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_core.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl

The IQ rotation is ported from the FMCOMMS2. See the algorithm 
https://wiki.analog.com/resources/eval/user-guides/ad-fmcomms2-ebz/iq_rotation
Integrated into TPL. 
Updated to support multiple samples on a clock cycle. 
Tested on MxFE

Dev mxfe iq rotation

---

library/axi_dmac/bd/bd.tcl

In some cases, the Vivado version can contain other characters than just
numbers. One such example is after applying the patch of AR# 71948,
which makes `version -short` return something like `2018.3_AR71948`.
This patch changes the version check to ignore anything after the first
two components of the version.

axi_dmac: generalize version check

---

library/common/ad_iqcor.v

Generate loops must have labels. 
Tested on A10SoC  + ADRV9009

library/common/ad_iqcor: Fix Intel compilation issues 

---

projects/ad_fmclidar1_ebz/a10soc/system_project.tcl
projects/ad_fmclidar1_ebz/a10soc/system_top.v
projects/ad_fmclidar1_ebz/common/ad_fmclidar1_ebz_qsys.tcl

The AFE's I2C interface should be pin-multiplexed to the FPGA. Also, add
a bidirectional IO buffer for the interface, and make sure it has weak
pull-up resistors.

ad_fmclidar1_ebz/a10soc: Fix AFE's I2C interface

---

library/axi_ad9144/Makefile
library/axi_ad9144/axi_ad9144_hw.tcl
library/axi_ad9152/Makefile
library/axi_ad9152/axi_ad9152_hw.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_hw.tcl

Even if the IQ rotation is disabled in the projects all modules has to be
added to the list of dependencies to avoid compilation errors.
Tested compilation on: 
daq2 a10soc
daq3 a10gx
dac_fmc_ebz a10soc

jesd204/ad_ip_jesd204_tpl_dac: Fix Intel dependencies

---

library/common/ad_iqcor.v

For converter resolution smaller than 16 when the core is disabled the
bypassed data was truncated. This patch should fix that.
Tested in simulation.

common/ad_iqcor: Fix for sample width smaller than 16

---

library/spi_engine/spi_engine_execution/spi_engine_execution.v

The commit 9ab88f1200099274853035bf75b8c23e70ce4ffb introduced a new
feature for the execution module, which provides the possibility to
delay the SDI line latch with one or more core clock cycle. Unfortunatly
the implementation was not correct and the SDI line was latched at the
wrong time.
This patch fix the aligment of the shift register and the SDI_DELAY parameter,
to latch the SDI line of the physical interface at the right time.
Improve the description of the feature.

spi_engine_execution: Fix the SDI latching

---

library/scripts/adi_ip_xilinx.tcl
projects/scripts/adi_project_xilinx.tcl

There is a major compatibility issue between 2019.1 and 2019.2.
The file system_top.hdf got a different file extention. This will
cause a compilation failer in the end of the build. To save time
and fail earlier, upgrade the version mismatch message to ERROR.
If user still wants to build a branch with different tool version
the variable ADI_IGNORE_VERSION_CHECK should be set to 1.

scripts/xilinx: Version mismatch is upgraded to ERROR

---

library/axi_sysid/axi_sysid.v

fixes critical warning reported by lnagy

sysid_intel: Fixed axi_sysid module name

---

library/scripts/adi_ip_xilinx.tcl

This change fixes the CRITICAL warning regarding the use of "range" not being one of the available arguments.
Build tested.

library/scripts/adi_ip_xilinx: Fix critical warning

---

library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/axi_spi_engine/axi_spi_engine_constr.ttcl
library/spi_engine/axi_spi_engine/axi_spi_engine_ip.tcl
library/spi_engine/interfaces/spi_engine_offload_ctrl_rtl.xml
library/spi_engine/spi_engine_execution/spi_engine_execution.v
library/spi_engine/spi_engine_offload/spi_engine_offload.v
library/spi_engine/spi_engine_offload/spi_engine_offload_constr.ttcl
library/spi_engine/spi_engine_offload/spi_engine_offload_ip.tcl

Increment the sync_id value at each transfer. The initial value of the sync_id is the value of the last SYNC command loaded into the command buffer.
Add constraints ttcl for the data offload module.

SPI Engine Offload add incremental sync_id

---

library/spi_engine/axi_spi_engine/axi_spi_engine.v

Two minor SPI Engine improvement:
- the value of NUM_OF_SDI is accessible from register 0xC
- FIFO read support data widths up to 64 bits

SPI Engine improvements

---

library/spi_engine/axi_spi_engine/axi_spi_engine.v

The conversion start configuration interface can be used to configure
a PWM generator (util_pulse_gen) to generate CNV for a precision ADC.

axi_spi_engine: Add pulse_width to the CNV configuration interface

---

projects/scripts/adi_env.tcl

When building parameterizable projects the value of the variables does not show up in the build log. 
This patch should fix that.

scripts/adi_env.tcl: print in logs system variables are used

---

library/jesd204/scripts/jesd204.tcl
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/scripts/adi_env.tcl

Having the same name for dac and adc TPLs creates conflict in the
address segment naming having random names associated to the segments.
This causes difficulties during scripting of the project in test bench
mode.
Tested with AD9081

Rename TPL instance names in block design

---

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_hw.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_hw.tcl
projects/adrv9371x/common/adrv9371x_qsys.tcl

Update the block design for intel carriers, to use the generic JESD204 TPL cores.

ADRV9371x Intel Generic JESD204 TPL

---

projects/scripts/adi_project_xilinx.tcl

Look for an overall indicator of timing failure.
Create critical warning if timing is failed.

adi_project_xilinx.tcl: discover all timing failures

---

projects/cn0540/coraz7s/system_project.tcl

The previous version of system_project.tcl didn't generate a hdf file because of a mistakenly commented line.

cn0540: Fix typo

---

library/spi_engine/spi_engine_execution/spi_engine_execution.v

The SDI (MISO) latching did not work correctly if SDI_DELAY was set to a higher value than zero.
The following patches fix the issue.

Fix SPI Engine execution

---

projects/fmcomms5/zc702/system_bd.tcl

The $sys_dma_clk variable is connected to 200 MHz by default. It's a variable that must contain a net name.
Fix the variable update, to be connected to the 150MHz clock source. This will add some timing margin for the HPS2 and HPS3 interconnects.

fmcomms5/zc702: Fix the sys_dma_clk connections

---

library/axi_adc_trigger/axi_adc_trigger.v
library/axi_logic_analyzer/axi_logic_analyzer_trigger.v

Add trigger disable option for both ADC and Logic Analyzer instruments.
Tested on m2k.

M2k trigger disable condition

---

library/axi_logic_analyzer/axi_logic_analyzer.v
library/axi_logic_analyzer/axi_logic_analyzer_reg.v

Add instrument triggering for the Pattern Generator.
The trigger signal can be internal (Oscilloscope or Logic Analyzer) or external(TI, TO pins).
Tested on M2k

m2k: PG add instrument triggering

---

library/common/ad_dds.v

For projects where the clock ratio between the sampling clock and core clock
is higher than 2, the ad_dds generates a number of samples equal with
the clock ratio. There is a phase offset between the samples, proportional
with the requested DDS frequency.
In scenarios where the DDS out frequency is closer to the upper
limit(Nyquist) and/or the clock ratio is also greater than 2 and the
dac_data_sync reminds low for an extended period of time, the DAC will
receive at each core clock period, a number of samples equal with the
clock ratio and with an amplitude influenced by the DDS out frequency.
In most cases similar with a sawtooth signal.
With this commit we ensures that samples received by the DAC are 0 for
the period where dac_data_sync signal is high. Only when the signal
transitions …

ad_dds: Fix noise caused by dac_data_sync

---

projects/scripts/adi_project_intel.tcl

The next supported version is Quartus PRO 19.3, so we can have the same version for Quartus and EDS too.
Change the Tcl script to generate an error if the required and the actual version is not the same. It is used the same logic as in case of Xilinx toolchain.

QPRO version upgrade

---

projects/ad40xx_fmc/common/ad40xx_bd.tcl

In general we have to add a delay of half SCLK cycle. (latch the MISO on the next consecutive SCLK edge)

FIX ad40xx_fmc SDI latching

---

library/axi_adc_decimate/axi_adc_decimate.v
library/axi_adc_trigger/axi_adc_trigger.v
library/axi_logic_analyzer/axi_logic_analyzer.v
library/axi_logic_analyzer/axi_logic_analyzer_constr.xdc
library/axi_logic_analyzer/axi_logic_analyzer_reg.v
projects/m2k/common/m2k_bd.tcl
projects/m2k/standalone/system_constr.xdc

Auto sync(compensate) LA to ADC path delays.
The number of delay taps in the LA data path can be controlled manually, from
the regmap or automatically, according to the axi_adc_decimate's rate.
Moreover, because the rate is configure by software, and the time of
initialization, is different for the ADC path and LA path. There is an
uncertainty of plus/minus one sample between the two. Because ADC and LA
paths share the same clock we can easily synchronize the two paths. We
can't use reset, because the rate generation mechanism is different
between the two. So the ADC path can be used as master(valid generator)
to drive the LA path.
The synchronization is done by setting the rate source bit. This
mechanism can be used only if the desired rates for both paths are equal,
including …

Dev m2k sync osc la sync

---

projects/adrv9371x/a10gx/system_project.tcl
projects/daq2/a10gx/system_project.tcl

The ADRV9371/a10gx and daq2/a10gx fails timing with default optimization mode. Use aggressive performance to improve timing.

Fix QPRO optimization mode

---

projects/scripts/adi_project_intel.tcl

In Quartus Prime in place of the set_domain_assignment commad, the set_interconnect_requirement command is used.

adi_project_intel: Update QSYS generation

---

library/spi_engine/axi_spi_engine/axi_spi_engine_constr.sdc
library/spi_engine/axi_spi_engine/axi_spi_engine_hw.tcl
library/spi_engine/spi_engine_execution/spi_engine_execution_hw.tcl
library/spi_engine/spi_engine_interconnect/spi_engine_interconnect_hw.tcl
library/spi_engine/spi_engine_offload/spi_engine_offload_hw.tcl

This commit contains the *_hw.tcl files for building the SPI Engine modules
for Intel projects. Also, a new set of constraints is added for the regmap module,
in order to meet timing.

spi_engine: Add SPI Engine Intel Support

---

library/spi_engine/spi_engine_offload/spi_engine_offload_ip.tcl

Before:
After:
NOTE: This commit does not change the functionality of the IP.

SPI Engine Offload: Update IPXACT GUI layout

---

library/spi_engine/axi_spi_engine/axi_spi_engine_ip.tcl
library/spi_engine/spi_engine_execution/spi_engine_execution_ip.tcl
library/spi_engine/spi_engine_offload/spi_engine_offload_ip.tcl
projects/cn0540/coraz7s/system_constr.xdc

The IPXACT updates introduced a bug into the SPI Engine framework. This patch fix it.
Also improved the timing constraint for cn0540/coraz7.

Fix SPI Engine framework

---

projects/scripts/adi_intel_msg.tcl
projects/scripts/adi_project_intel.tcl

Trying to do the same thing as for Xilinx projects. This will downgrade the critical warning related to the unused TX high speed channel.

scripts/intel: Add message severity definition file

---

library/common/ad_dds.v

If dac_valid is not a constant '1' it gets synchronized with the
dac_data_sync signal. This causes that dac_valid never asserts while
dac_data_sync is high, this way skipping the phase initialization.
Tested on ZED+9001

library/common/ad_dds: Fix initialization when 'valid' not constant

---

projects/adrv9001/zcu102/system_constr.xdc
projects/adrv9001/zcu102/system_top.v
projects/adrv9001/zed/system_constr.xdc
projects/adrv9001/zed/system_top.v

VADJ on Zedboard can be higher than 1.8V the 9001 supports. The evaluation board has a circuitry built to detect higher voltage levels than 1.8V  asserting VADJ_ERR in this case.   A status LED on the evaluation board indicated good operation.  
For Zedboard all outputs are kept high-z in case VAD_ERR is set. 
For ZCU102 only the status led is driven. 
Tested on Zed

ADRV9001 refactor VADJ monitoring

---

library/axi_generic_adc/axi_generic_adc.v

The axi_generic_adc module had warnings regarding the use of parameters before their declaration. This commit will fix the warnings, as the parameters are now declared within the module.

axi_generic_adc: Declare parameters before use

---

library/axi_logic_analyzer/axi_logic_analyzer.v
projects/m2k/common/m2k_bd.tcl

Fix warnings regarding the use of a localparam in a port declaration and unused registers.
Build tested.

Fix m2k warnings

---

library/axi_hdmi_tx/axi_hdmi_tx_core.v
library/common/ad_csc.v
library/common/ad_ss_422to444.v

Fix warnings regarding the use of a localparam in a port declaration and unused registers.
Build tested.

Fix hdmi tx warnings

---

library/spi_engine/spi_engine_interconnect/spi_engine_interconnect.v

Always construct should not contains blocking and non-blocking assignment at the same time.

SPI Engine Interconnect: Fixed assignment type

---

projects/ad40xx_fmc/zed/system_constr_ad40xx.xdc
projects/ad40xx_fmc/zed/system_constr_adaq400x.xdc

ad40xx_fmc/zed: Fix constraints, to avoid critical warnings in synthesis

Fix constraints for ad40xx

---

projects/cn0506_rmii/zc706/system_constr.xdc
projects/cn0506_rmii/zed/system_constr.xdc

Fix the critical warnings caused by missing clock definitions.
Build tested

cn0506_rmii: Fix no defined clock warnings

---

projects/scripts/adi_board.tcl

board name is taken after last underscore from the project name in vivado, the rest is considered project name

sysid: Fix board/project name underscore issue

---

projects/ad77681evb/zed/Makefile
projects/ad77681evb/zed/system_constr.xdc
projects/ad77681evb/zed/system_top.v

This commit will fix the warning caused by the redundant use of ad_data_clk.

ad77681evb: Remove redundant ad_data_clk

---

projects/common/s10soc/s10soc_system_assign.tcl
projects/daq2/a10soc/system_project.tcl
projects/scripts/adi_intel_msg.tcl

Fix various critical warnings in Quartus designs and a timing violation:
1) Disable "Unused TX/RX channel" critical warning for Stratix 10
2) Fix critical warning related to wrong IO property constraints for input port for Startix 10 base design 
3) Put a higher optimization effort for the implementation, for DAQ2_A10SOC

Fix Quartus critical warnings and timing issues

---

projects/cn0363/zed/system_top.v

iobuf was generating drc warning because it was not fully connected.

cn0363: Remove iobuf for spi sdo

---

library/axi_gpreg/Makefile
library/axi_gpreg/axi_gpreg_constr.ttcl
library/axi_gpreg/axi_gpreg_ip.tcl

fixed critical warnings generated when the NUM_OF_CLK_MONS parameter
is set to 0 and the constraints written in up_clock_mon_constr.xdc
cannot be applied; removed up_clock_mon_constr.xdc from ip core.

axi_gpreg: Add ttcl for clock_mon  constraints

---

projects/cn0540/common/cn0540_bd.tcl
projects/cn0540/coraz7s/system_constr.xdc

Increase the spi_clk frequency to 80MHz. This way we do not lose the last bit in the SPI interface.

Fix cn0540 with coraz7s

---

projects/cn0540/common/cn0540_bd.tcl
projects/cn0540/coraz7s/system_constr.xdc
projects/cn0540/coraz7s/system_top.v

The coraz7s has an Arduino/chipKIT Shield connector with 6 Single-ended
and 8 Differential Analog inputs tied to Xilinx's XADC.
The CN0540 uses the A0-5 pins as single-ended adc channels to monitor
the differential input, ADC driver, and buffer voltages.
Signed-off-by: Sergiu Cuciurean <sergiu.cuciurean@analog.com>

projects: cn0540: coraz7s: Add XADC support

---

projects/ad9081_fmca_ebz/vcu118/system_constr.xdc
projects/ad9081_fmca_ebz/zcu102/system_constr.xdc

The device clocks are AC coupled LVDS lines without external termination.
For proper operation internal differential termination must be enabled,
the DQS_BIAS will DC bias the AC coupled signal to VCCO/2 (1.8/2) 0.9V
Tested on MxFE and ZCU102

ad9081_fmca_ebz: Fix device clocks termination

---

projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl

Switch RX path reset to be controlled by the TPL and use
RX SYSREF as external synchronization for the ADC TPL
Use TX SYSREF for synchornizing the TX DDS

adrv9009_zu11eg: Add synchronization at application layer

---

library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_framer.v

The parameters were not in the order of invocation and this causes an error in the vivado simulator (xsim).
* closes https://github.com/analogdevicesinc/hdl/issues/583

ad_ip_jesd204_tpl_dac_framer: fix localparam ordering

---

library/axi_ad6676/axi_ad6676.v
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_pnmon.v

Most of JESD projects have the PN checker not working. From Dan's experiment and my testing on AD9081 looks the MSB of the PN checker is inverted wrongly when the data format is two's complement. It should be the other way around.
The TWOS_COMPLEMENT parameter should reflect the data format of the part even if the parameter is currently used only in the pn monitor.  So changing the TWOS_COMPLEMENT to 0 in order to have the PN passed can cause confusion.
Tested on AD9081

jesd204: Fix pn mon

---

projects/cn0540/coraz7s/Makefile

fix missing dependency causing project to fail

cn0540: Add axi_clkgen to Makefile

---

projects/scripts/adi_pd_intel.tcl

adi_pd_intel contains a bunch of prints that were used during development, filling up the log file with noise. Delete these print outs.

scripts/adi_pd_intel: Delete noisy print outs

---

library/spi_engine/axi_spi_engine/axi_spi_engine.v
projects/adaq7980_sdz/common/adaq7980_bd.tcl
projects/adaq7980_sdz/zed/Makefile

Controlling the offload trigger (in case of an internal trigger) from AXI SPI Engine module is a wrong approach, and it can generate tightly coupled solutions which are hard to maintain and debug. The best approach is to control and generate the internal trigger from outside of the framework, taking the fact that the source of the trigger can vary in function of the application.
The only project that uses these "AXI SPI Engine" offload trigger generator registers is the ADAQ7980.
Revert all the commits that add the control register for the trigger generator. Update the ADAQ7980 project to use an axi_utile_pulsegen for offload trigger generation. 
Note: software needs to be updated to support the new trigger generation scheme. This PR will be merge after testing the solution.

AXI SPI Engine: revert pulse period

---

projects/adv7513/de10nano/system_constr.sdc
projects/adv7513/de10nano/system_top.v
projects/common/de10nano/de10nano_system_assign.tcl

Fix missing IO assignment definitions and delete unused IO ports.

Fix critical warnings on adv7513@de10nano

---

library/axi_ad9963/axi_ad9963.v
library/axi_ad9963/axi_ad9963_if.v
library/axi_ad9963/axi_ad9963_tx.v
library/axi_ad9963/axi_ad9963_tx_channel.v
library/axi_dac_interpolate/axi_dac_interpolate.v
library/axi_dac_interpolate/axi_dac_interpolate_filter.v
library/axi_dac_interpolate/axi_dac_interpolate_reg.v
projects/m2k/common/m2k_bd.tcl

Add DAC last sample hold support.
- add trigger start/stop options
- DMA sync stop option
- transmit last sample or zero option
Usually a transmission is achieved with cyclic buffers written in memory. One for each channel(DMA). When the transmission is halted, the software, will first stop the DMAs. Regarding the DMA sync stop option, if one DMA is stopped, the other one will still transfer data(software can’t stop them at the same time), but “the last sample” is stored and used(at the DAC interface level), in regards with the first stopped DMA
In order for this mechanism to function properly, the application should not go back to DDS source select at the DAC interface level(axi_ad9963) after the transmission ends.

M2k dac sample hold

---

projects/fmcomms8/zcu102/system_top.v

Add a comment that the spi CS decoding is tied to a setting in the device tree.

fmcomms8:zcu102: Add an SPI comment to system_top.v 

---

projects/ad_fmclidar1_ebz/a10soc/system_top.v

Fixing a typo in projects/ad_fmclidar1_ebz/a10soc/system_top.v.

ad_fmclidar1_ebz/a10soc: Fix a typo

---

library/common/ad_mux.v
library/common/ad_mux_core.v
library/common/tb/ad_mux_tb
library/common/tb/ad_mux_tb.v
library/common/tb/run_tb.sh
library/common/tb/tb_base.v
library/common/up_dac_channel.v
library/jesd204/ad_ip_jesd204_tpl_dac/Makefile
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_channel.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_core.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_hw.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl

This series of changed adds channel crossbar to DAC TPL selectable through synthesis parameter. 
The capability is discoverable by the software through the config register. 
The crossbar is an N to N mux,  implemented with pipelined muxes. 
Allows routing any channel to any, or one to many to broadcast the same channel to all converters.
Each converter has a register which defines the source of the data from the DMA interface, 
Tested with MxFE. 
Tested compile only DAQ2/A10SOC

Add channel crossbar to DAC TPL

---

library/intel/adi_jesd204/adi_jesd204_hw.tcl

In phase aligned mode the fPLL uses an external feedback path to better
align the phase of the PLL output to the phase of the external reference
clock.
This mode is required for deterministic latency to be able to sample SYSREF
which is source synchronous to the external reference clock signal.
So far phase aligned mode had been disabled since manual PLL calibration
would fail in this mode under certain (unknown) circumstances and dynamic
reconfiguration of the PLL would not work.
The latest Intel Arria 10 transceiver datasheet contains instructions for
the proper calibration sequence to make it work when the PLL is configured
for phase aligned mode. Software has been updated accordingly, so enable
phase aligned mode.

adi_jesd204: Configure fPLL phase aligned mode

---

projects/ad7768evb/common/ad7768_if.v
projects/ad7768evb/common/ad7768evb_bd.tcl
projects/ad7768evb/zed/Makefile
projects/ad7768evb/zed/system_top.v

A parallel data path has been added to the initial design to enable only the desired channels of the ADC.

ad7768evb: Remove buffers, add parallel data path

---

library/spi_engine/axi_spi_engine/Makefile
library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/axi_spi_engine/axi_spi_engine_hw.tcl
projects/ad40xx_fmc/zed/system_constr_ad40xx.xdc

Missed to update the Makefile/hw script for axi_spi_engine after util_axis_fifo refactoring. This patch will fix the broken build for all SPI Engine projects.

axi_spi_engine: Fix make/script after util_axis_fifo refactoring

---

projects/adv7513/de10nano/system_top.v
projects/cn0540/de10nano/system_top.v
projects/common/de10nano/de10nano_system_assign.tcl
projects/common/de10nano/de10nano_system_qsys.tcl

Without defining this signal, the UART lines receive garbage data
when no cable is connected to the J4 USB UART port.
The GPIO9 is enabled in the reference base design along with the
4MA CURRENT_STRENGTH constraint on the UART pins

de10nano: Add hps_conv_usb_n signal to stabilize UART lines

---

projects/ad_fmclidar1_ebz/a10soc/Makefile
projects/ad_fmclidar1_ebz/a10soc/system_project.tcl
projects/ad_fmclidar1_ebz/a10soc/system_top.v
projects/adv7513/de10nano/Makefile
projects/adv7513/de10nano/system_project.tcl
projects/adv7513/de10nano/system_top.v
projects/arradio/c5soc/Makefile
projects/arradio/c5soc/system_project.tcl
projects/arradio/c5soc/system_top.v
projects/cn0506_mii/a10soc/Makefile
projects/cn0506_mii/a10soc/system_project.tcl
projects/cn0506_mii/a10soc/system_top.v
projects/cn0506_rgmii/a10soc/Makefile
projects/cn0506_rgmii/a10soc/system_project.tcl
projects/cn0506_rgmii/a10soc/system_top.v
projects/cn0540/de10nano/Makefile
projects/cn0540/de10nano/system_project.tcl
projects/cn0540/de10nano/system_top.v

This reverts commit a3a610728c0bee96950ebd95d2e908ea6a7f3d49.
The ad_iobuf module works for Xilinx but not for Intel, where the IOBUF is not correctly inferred from the HDL description.
Build tested on arria 10. Tested in hardware only on cyclone 5.

Revert "intel: Update projects to use ad_iobuf instead of ALT_IOBUF"

---

projects/scripts/adi_project_xilinx.tcl

Add a layer under adi_project that allows you to directly specify a device/board combination without determining it from the project name. This allows support of additional hardware without modifying the script to include new board/device pairs.

scripts: allow directly specifying a device when creating a project

---

library/intel/adi_jesd204/adi_jesd204_hw.tcl
library/intel/jesd204_phy/jesd204_phy_hw.tcl
projects/adrv9009/a10gx/system_constr.sdc
projects/adrv9009/a10soc/system_constr.sdc
projects/adrv9009/common/adrv9009_qsys.tcl
projects/adrv9371x/a10gx/system_constr.sdc
projects/adrv9371x/a10soc/system_constr.sdc
projects/adrv9371x/common/adrv9371x_qsys.tcl
projects/fmcomms8/a10soc/system_constr.sdc
projects/fmcomms8/common/fmcomms8_qsys.tcl

When phase alignment is active, the PFD frequency value should be used as outclk1 actual frequency.
The configuration interface of the fPLL does not support fractional values. If the reference clock is fractional, the tool will
throw an error, that requirement above is not respected.
Round up the reference clock for the SERDES and the lane rate in order to overcome this issue, until it's not fixed by Intel.

Fix Intel fPLL configuration

---

projects/daq3/zcu102/system_bd.tcl

Fix critical warning on Daq3/zcu102 project by connecting overflow pin for the AD9680 TPL

daq3:zcu102: Connect overflow pins for the AD9680 TPL

---

library/scripts/adi_ip_xilinx.tcl
projects/common/vc707/vc707_system_bd.tcl
projects/scripts/adi_project_xilinx.tcl
projects/scripts/adi_xilinx_msg.tcl
projects/scripts/project-xilinx.mk

projects affected by missing (discontinued) ip in xilinx catalog: 
cn0506_rmii.zed
cn0506_rmii.zcu102
cn0506_rmii.zc706

Vivado 2020.1 upgrade

---

projects/adrv9009zu11eg/adrv2crr_fmc/system_project.tcl
projects/adrv9009zu11eg/adrv2crr_fmcomms8/system_project.tcl
projects/adrv9361z7035/ccbob_cmos/system_project.tcl
projects/adrv9361z7035/ccbob_lvds/system_project.tcl
projects/adrv9361z7035/ccfmc_lvds/system_project.tcl
projects/adrv9361z7035/ccpackrf_lvds/system_project.tcl
projects/adrv9364z7020/ccbob_cmos/system_project.tcl
projects/adrv9364z7020/ccbob_lvds/system_project.tcl
projects/adrv9364z7020/ccpackrf_lvds/system_project.tcl
projects/m2k/standalone/system_project.tcl
projects/pluto/system_project.tcl
projects/scripts/adi_project_xilinx.tcl
projects/sidekiqz2/system_project.tcl
projects/usrpe31x/system_project.tcl

After the #602 all standalone projects fails. In this patch all the standalone projects are using the **adi_project_create** process directly in their system_project.tcl file, instead the **adi_project**.

Quick fix of standalone projects

---

library/util_axis_fifo/util_axis_fifo.v

Vivado synthesis is optimizing out the "zerodeep" block, resulting untreated clock domain crossing. Set **KEEP** attribute for the registers.
Although I closed this a week ago (#623), the problem still persist in some projects. The proper fix would be to refactor the DMA, to not use the util_axis_fifo with zero address width. Until then **KEEP** is used to prevent unwanted optimization.

util_axis_fifo: Add KEEP synthesis attribute for zerodeep CDC

---

library/xilinx/util_adxcvr/util_adxcvr_xch.v

The control lines for TX PRBS must be synchronized using the TX clock.
This will fix timing failure on VCU118+MxFE

util_adxcvr: Fix PRBS synchroniser typo

---

projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl
projects/fmcomms8/common/fmcomms8_bd.tcl

The TX lanes 0 and 1 are swapped in hardware, resulting I/Q sample swap for TX RF channel 0. This fixes the swap. Tested on the ZCU102

fmcomms8: zcu102: Fix lane swapping

---

library/spi_engine/scripts/spi_engine.tcl
library/spi_engine/spi_engine_execution/Makefile
library/spi_engine/spi_engine_execution/spi_engine_execution.v
library/spi_engine/spi_engine_execution/spi_engine_execution_constr.ttcl
library/spi_engine/spi_engine_execution/spi_engine_execution_ip.tcl
projects/ad40xx_fmc/common/ad40xx_bd.tcl
projects/ad40xx_fmc/zed/system_constr_ad40xx.xdc
projects/ad40xx_fmc/zed/system_constr_adaq400x.xdc

There are boards, which takes the SCLK and echos back to
the FPGA through a level shifter - doing this removes the effect of
round-trip timing delays from the level shifter. This is commonly done
whenever isolators are used since they are very slow.
By setting the ECHO_SCLK parameter to 1, the IP will use the incoming
echoed SCLK clock to latch the SDI line(s).
The designer responsibility to time the SDI shift registers in a way
that respects the design requirements.

SPI Engine: Add echoed SCLK support

---

projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl
projects/fmcomms8/common/fmcomms8_bd.tcl

Same as https://github.com/analogdevicesinc/hdl/pull/640 but for master branch.
The TX lanes 0 and 1 are swapped in hardware, resulting I/Q sample swap for TX RF channel 0. This fixes the swap.

Fix fmcomms8 lanes

---

projects/scripts/adi_board.tcl

This will allow building base test harnesses and place on top of them
existing block designs for simulation purposes.
Test harnesses will contain basic functionality like
- clock and reset generators
- AXI master to aid register access of the cores.
- memory model of the DDR
- interrupt controller
Existing procedures (ad_mem_hp0_interconnect, ad_cpu_interconnect, ... ) will
connect to this harness as they do to a real base design.

 scripts/adi_board.tcl: Add simulation support

---

projects/cn0540/coraz7s/system_constr.xdc

Design uses 80MHz spi_clk which does not require
special considerations

cn0540/cora: Remove multicycle constraint

---

library/axi_ad9361/axi_ad9361_constr.xdc
library/axi_adrv9001/axi_adrv9001_constr.sdc
library/axi_adrv9001/axi_adrv9001_constr.xdc
library/axi_adrv9001/axi_adrv9001_core.v
library/axi_adrv9001/axi_adrv9001_hw.tcl
projects/adrv9001/zcu102/cmos_constr.xdc

Below commits are addressing timing failures or critical warnings related to constraints. 
Tested on 
ZCU102 + ADRV9001 CMOS
ZCU102 + ADRV9001 LVDS
ZED + ADRV9001 CMOS

ADRV9001 fixes for 2019_R2

---

library/axi_dmac/axi_dmac_burst_memory.v

Non-blocking assignments in combinatorial blocks can cause simulation problems. In this particular case iverilog coughed up a hairball.

axi_dmac: fix non-blocking assignment in combinatorial block

---

projects/adrv9001/zc706/Makefile
projects/adrv9001/zc706/cmos_constr.xdc
projects/adrv9001/zc706/system_bd.tcl
projects/adrv9001/zc706/system_constr.xdc
projects/adrv9001/zc706/system_project.tcl
projects/adrv9001/zc706/system_top.v

The project supports CMOS interface only.
VADJ on the ZC706 must be programmed to 1.8V
Tested on ZC706 and Navassa B0

adrv9001/zc706: Initial commit

---

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl

This workarounds a DMA bug until that is fixed.
Tested on MxFE  and VCU118 with N'12 profile

ad9081_fmca_ebz: Workaround DMA bug when bus size equals max burst size

---

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc.v
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_core.v
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_deframer.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v
library/jesd204/jesd204_rx/jesd204_rx.v
library/jesd204/jesd204_rx/jesd204_rx_constr.ttcl
library/jesd204/jesd204_rx/jesd204_rx_ctrl_64b.v
library/jesd204/jesd204_rx/jesd204_rx_lane_64b.v
library/jesd204/jesd204_tx/jesd204_tx_lane_64b.v

This series of fixes tries to address timing closure issues seen on larger designs like QuadMxFE on N' 12 and lane rate of 24.75Gbps setups where also the datapath increases.
- make non essential features opt-in to reduce resource usage
- reduce fanout of asynchronous reset signals
- add pipeline registers
- add ASYNC_REG to double synchronizers
- adjust padding for N'=12 in the DAC TPL to match fmcomms2 like sample arrangement
Tested with QuadMxFE + VCU118

JESD204C timing fixes

---

library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/axi_spi_engine/axi_spi_engine_constr.ttcl

Let the util_axis_fifo's to generate the almost_full and almost_empty signals for the interrupt logic.

Fix axi_spi_engine almost full and almost empty IRQ

---

library/xilinx/axi_adxcvr/axi_adxcvr_up.v

Forgot to increase version when I added PRBS support. Software needs it so it can discover the capability.

xilinx/axi_adxcvr: Increase version to 17.02.a to show PRBS capability

---

library/jesd204/jesd204_rx/jesd204_rx_constr.ttcl

get_cell on i_lmfc/cdc_sync_stage1_reg doesn't return anything because design was updated.
This generates a CRITICAL WARNING and since the constraint it not necessary anymore, it can be deleted.

jesd204_rx_constr.ttcl: Remove ASYNC_REG from i_lmfc/cdc_sync_stage1_reg

---

projects/ad469x_fmc/zed/system_constr.xdc

The project is using a 160MHz spi clock (internal) which sometimes causes timing failures which should be fixed with this commit.

ad469x/zed: Add multicycle path constraint

---

projects/scripts/adi_pd.tcl

Parsing of not existed "gitbranch_string" fails the build process.

sysid: Make sure gitbranch_string is always declared

---

library/axi_pulse_gen/axi_pulse_gen.v
library/axi_pwm_gen/Makefile
library/axi_pwm_gen/axi_pwm_gen.v
library/axi_pwm_gen/axi_pwm_gen_1.v
library/axi_pwm_gen/axi_pwm_gen_constr.sdc
library/axi_pwm_gen/axi_pwm_gen_constr.ttcl
library/axi_pwm_gen/axi_pwm_gen_ip.tcl
library/axi_pwm_gen/axi_pwm_gen_regmap.v

Added axi_pwm_gen which is an improved version of axi_pulse_gen with a different register map structure(compatible with Linux PWM framework).
This option was also chosen to keep the backwards compatibility with other projects for a short period.
Tested on a testbench and cora.

Dev axi pwm gen

---

library/axi_pulse_gen/axi_pulse_gen.v

Fix axi_pulse_gen typo added in commit https://github.com/analogdevicesinc/hdl/commit/c235e5e583756fccd86223548e27405dd04b25aa

axi_pulse_gen: Fix typo introduced in c235e5e58

---

projects/adrv9361z7035/common/ccbob_constr.xdc

LED_GPIO_1 and LED_GPIO_2 are flipped in the constraints file

Correct constraints file pin mapping

---

library/axi_ad9361/axi_ad9361_tdd.v

As alluded to in the subject, this commit simply fixes what appears to be a copy-paste bug.

axi_ad9361: Fix typo in tdd interface

---

library/common/up_tdd_cntrl.v

Adds a magic identification value of 0x54444443 at word address 0x3.
It is derived from the ASCII String "TDDC" interpreted as a big-endian
32-bit unsigned integer.

up_tdd_cntrl: Add magic value "TDDC"

---

projects/adrv9001/a10soc/system_qsys.tcl

For fixing "Failed to reset the device and set SPI Config"
error, both clockPolarity and clockPhase should be disabled
or both enabled. By default both are unset.
Signed-off-by: Stefan Raus <stefan.raus@analog.com>

adrv9001:a10soc:system_qsys.tcl: set clock polarity to 0

---

library/Makefile
library/axi_tdd/Makefile
library/axi_tdd/axi_tdd.v
library/axi_tdd/axi_tdd_ip.tcl

This commit adds a standalone TDD IP core based on the
existing `up_tdd_cntrl` module and the `up_axi` pcore <-> axi bridge.
~~Note: This code has not been tested in hardware yet, as such the PR should retain its draft status until further notice.~~

axi_tdd: Add standalone axi_tdd IP core

---

library/axi_dmac/axi_dmac_regmap_request.v
library/axi_dmac/tb/regmap_tb.v

Restore axi_dmac_regmap_request to f7b8a2d version and adapt regmap_tb to this version. This commit will fix timing violation fails on adv7513 with de10nano and daq2 with a10gx projects.

axi_dmac: Restore axi_dmac_regmap_request to f7b8a2d version

---

library/axi_adrv9001/adrv9001_rx.v
library/axi_adrv9001/adrv9001_tx.v
library/xilinx/common/ad_serdes_in.v
library/xilinx/common/ad_serdes_out.v

After a reset with mssi_sync from the top level (mssi_sync is an input to axi_adrv9001.v), the data bus may be randomly left in a bad or corrupted state in a xilinx FPGA. This problem will occur more than 10% of the time. It is present in the provided evaluation images on xilinx series eval boards and on a custom FPGA design.
The stream corruption is due to related IOserdes (being part of the same 16-bit serial stream like Q data on tx channel 0) being asynchronously reset, leaving them in a random phase relative to one another. The solution in this pull request is to synchronously de-assert the reset in the data clock domain.
The applied fix was run thousands of times in an automated fashion using pattern loopback test after a mssi_sync to confirm working bus state.
This took a lot of …

adrv9001: fixes for reset metastability on xilinx ioserdes

---

projects/scripts/adi_board.tcl

The goal of this commit is to make sure there isn't any significance to the order in which parameters of ad_connect are specified.
As an example, previously you could only `ad_connect target VCC`, while `ad_connect VCC target` would fail.
Note: This code intentionally ignores `bd_{,intf_}ports`, because these can all be treated as bd_pins.
A list of supported type combinations of the two parameters:
As you can tell from the table above, all interaction with `bd_intf_net`s is currently treated as invalid. This does not appear to be an issue from what i can tell, but there may be a situation that i've missed and i'd love to hear about it ;)

adi_board: Rewrite ad_connect to support all input permutations

---

library/jesd204/tb/frame_align_tb
library/jesd204/tb/frame_align_tb.v
library/jesd204/tb/jesd204_frame_align_replace_tb.v

Fix jesd204 frame_aligh_tb by adding a fifo to solve rx and tx delay.
It saves the data from tx and compares it with the recieved ones from
rx.

tb: jesd204: update and automate frame_align_tb

---

projects/scripts/adi_project_xilinx.tcl

For the OOC flow it would be useful to have the number of parallel jobs controllable.
Tested in compile-only with dual-mxfe and vcu118.

scripts/adi_project_xilinx: Set number of parallel OOC jobs through env variable

---

library/axi_pwm_gen/axi_pwm_gen.v
library/axi_pwm_gen/axi_pwm_gen_ip.tcl
library/axi_pwm_gen/axi_pwm_gen_regmap.v

Fix offset for pwms with different periods.
The previous version was using an offset scheme based on pwm counter_0.
By using a separate offset counter the user will not be constrained by
pwm_0 period in regards with the offset of other pulses. In this version
offset 0 is used to delay pwm 0 in regards to the offset counter.
The offset counter will start after the load_config signal is asserted
and all active pwm counters finish the previous cycle or by a software
reset.
The software reset should also be used when using external_sync.

axi_pulse_gen: Fix offset mechanism

---

projects/ad_fmclidar1_ebz/common/ad_fmclidar1_ebz_bd.tcl

This commit removes two invalid ad_connect invocations, which weren't
caught in the original tests for commit cdda184007.

ad_fmclidar1_ebz: Remove invalid ad_connect invocations

---

projects/scripts/adi_board.tcl

This commit fixes the command tracing output of ad_connect to reflect the actual commands which are issued.
Additionally, a useless conditional is removed.

adi_board: Fix ad_connect command tracing

---

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_ip.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl
library/jesd204/jesd204_rx/jesd204_rx.v
library/jesd204/jesd204_tx/jesd204_tx.v

Until now the supported max datapath width was 12 octets but this is not enough for wider frame sizes the AD9083 has.
Tested with AD9083  L=1,M=32,F=64
this PR goes together with https://github.com/analogdevicesinc/testbenches/pull/14

[JESD] Support more options for TPL datapath width

---

library/jesd204/axi_jesd204_tx/axi_jesd204_tx.v

The width of the parameter `device_cfg_octets_per_multiframe` doesn't match the width in the submodules and corresponding slave interface of the jesd204_tx module, resulting in a warning generated during validation in Vivado. 
This patch increases the width of this parameter in axi_jesd204_tx.
Vivado warning:
WARNING: [BD 41-2384] Width mismatch when connecting pin: '/axi_adrv9009_tx_jesd/tx/device_cfg_octets_per_multiframe'(10) to pin: '/axi_adrv9009_tx_jesd/tx_axi/device_cfg_octets_per_multiframe'(8) - Only lower order bits will be connected.

Fix width of device_cfg_octets_per_multiframe

---

projects/ad9083_evb/common/ad9083_evb_bd.tcl
projects/ad9083_evb/zcu102/system_bd.tcl

Removed intermediary FIFO as the bandwidth requirements are within the capabilities of the HPC port

ad9083: Removed FIFO and increased DMAC transfer length

---

library/scripts/adi_ip_xilinx.tcl
library/xilinx/axi_xcvrlb/axi_xcvrlb.v
library/xilinx/axi_xcvrlb/axi_xcvrlb_ip.tcl
library/xilinx/util_adxcvr/util_adxcvr_constr.xdc
projects/ad9082_fmca_ebz/vcu118/system_project.tcl
projects/common/kcu105/kcu105_system_bd.tcl
projects/common/kcu105/kcu105_system_constr.xdc
projects/common/vcu118/vcu118_system_bd.tcl
projects/scripts/adi_project_xilinx.tcl

Update vivado version to 2020.2:
- update default vivado version from 2020.1 to 2020.2
- add conditions to apply specific contraints only in Out Of Context mode.
- update DDR controler parameters for vcu118 and kcu105 dev boards
- set default value of ADI_USE_OOC_SYNTHESIS variable to 1

Update Vivado version to 2020.2

---

projects/scripts/adi_make.tcl
projects/scripts/adi_make_boot_bin.tcl

The 2020.1 Xilinx tools have a different tcl procedures to build the boot.bin file.
This commit updates the adi_make tcl flow for the new tools. The new process is not backwards compatible with tools older than 2020 version.

adi_make: Update bin build flow for 2020.1 tools

---

library/axi_adrv9001/adrv9001_rx_link.v
library/axi_adrv9001/adrv9001_tx_link.v
library/axi_adrv9001/axi_adrv9001.v
library/axi_adrv9001/axi_adrv9001_core.v
library/axi_adrv9001/axi_adrv9001_if.v
library/axi_adrv9001/axi_adrv9001_rx.v
library/axi_adrv9001/axi_adrv9001_rx_channel.v
library/axi_adrv9001/axi_adrv9001_tx.v
library/common/up_adc_common.v
library/common/up_dac_common.v

Add CMOS support for the interface for the following symbol modes on Xilinx devices:
| A |  B | C | D | E | F | G | H |  
| --- | --- | --- | --- | --- | --- | --- | --- |
| CSSI__1-lane | 1 |  16/8 | 80-SDR/160-DDR | 80 | - | SDR/DDR | SDR/DDR->4/2(C=16),2/1(C=8) |
Columns description:
A - SSI Modes
B - Data Lanes Per Channel
C - Serialization factor Per data lane
D - Max data lane rate(MHz)
E - Max Clock rate (MHz)
F - Max Sample Rate for I/Q (MHz)
G - Data Type
H - DDS Rate
CSSI - CMOS Source Synchronous Interface

axi_adrv9001: Add support for symbol operation mode on Xilinx devices

---

projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl
projects/common/zcu102/zcu102_system_bd.tcl

The derived clocks of the zynqmp core are not calculated correctly due
rounding issues, instead of 100MHz the value of 99999001 is received
causing warnings during system validation.
This can be fixed/worked around with the proper reference clock
definition.
The issue is present in Vivado 2020.1 and 2020.2
I have not tested newer versions.

adrv9009zu11eg & common/zcu102 : Fix zynqmp ref clock definition

---

library/xilinx/axi_adxcvr/axi_adxcvr_ip.tcl
library/xilinx/util_adxcvr/util_adxcvr_ip.tcl

"Reset pins" polarity between (axi_adxcvr and util_adxcvr) is fixed 
Correctly defined up_cpll_rst and up_qpll_rst pins as rst pins in block design

master: Correctly defined resets in bd.

---

library/data_offload/data_offload.v
library/data_offload/data_offload_constr.ttcl
library/data_offload/data_offload_fsm.v
library/data_offload/data_offload_ip.tcl
projects/common/xilinx/data_offload_bd.tcl

This commit adds a new synthesis option to the design, that controls
whether an internal clock domain crossing will be generated. Disabling
this option allows you to use a synchronization signal that is
synchronized to the write clock domain externally, and possibly shared
between multiple devices.
The default value retains the old behavior.

data_offload: Improve external synchronization

---

projects/fmcjesdadc1/common/fmcjesdadc1_bd.tcl
projects/fmcjesdadc1/kc705/Makefile
projects/fmcjesdadc1/kc705/system_bd.tcl
projects/fmcjesdadc1/vc707/Makefile
projects/fmcjesdadc1/vc707/system_bd.tcl
projects/fmcjesdadc1/zc706/Makefile

Modified the project such that there is only one data path for the ADC
data: deleted one of the JESD tpl instances, one of the cpack instances and
one of the dma instances.
This pull request was opened after closing the https://github.com/analogdevicesinc/hdl/pull/701 pull request. It introduces the same modification as the closed pull request but the branch it is linked to is up-to-date with the master branch. It also contains all the modifications suggested by the users who commented on the previous pull  request.

fmcjesdadc1: Update block design

---

library/spi_engine/spi_engine_execution/spi_engine_execution.v

The cs signal can now accept the IOB TRUE attribute.

spi_engine_execution: Fix cs signal generation

---

projects/scripts/project-xilinx.mk

After cleaning a project build a *.gen folder remains in the project folder which should be cleaned when running "make clean"

scripts: Add *.gen to clean list

---

library/common/ad_mem_asym.v
projects/common/xilinx/data_offload_bd.tcl

With larger block rams the option to control cascade height might come in handy when the Xilinx tools fail to identify a group of block rams as timing critical. In that case the cascade hight may be overridden to 1.
For more information on this attribute, see page 45 of the [Vivado Design Suite
User Guide - Synthesis](https://www.xilinx.com/support/documentation/sw_manuals/xilinx2020_2/ug901-vivado-synthesis.pdf)

ad_mem_asym: Add option to control cascade layout

---

library/data_offload/data_offload_fsm.v

This commit slightly changes the behavior of cyclic mode when a synchronization mode is enabled, to always wait before each iteration for another sync impulse. This allows the user to repeatedly replay a waveform at precise, and externally controlled timing, without having to refill the buffer each time. This does not change the behavior when synchronization is disabled or oneshot is enabled.

data_offload: Add sync to cyclic mode

---

library/data_offload/data_offload.v

data_offload: Fix timing violation

---

library/scripts/adi_ip_xilinx.tcl
projects/scripts/adi_project_xilinx.tcl

Update vivado version from 2020.2 to 2021.1 in projects and library scripts.

adi_project_xilinx.tcl, adi_ip_xilinx.tcl: update version to 2021.1

---

library/xilinx/axi_adxcvr/axi_adxcvr_ip.tcl
library/xilinx/util_adxcvr/util_adxcvr_ip.tcl

Defining up_qpll_rst and up_cpll_rst resets pins from util_adxcvr as asynchronous resets by removing clock associations.
Applying the same logic for up_pll_rst pin from axi_adxcvr ip.
Tested with jesd loopback test bench.

axi_adxcvr_ip.tcl util_adxcvr_ip.tcl: fixed asynchronous resets critical warnings in XCVR

---

library/data_offload/data_offload_fsm.v

This commit fixes an issue in situations where we provide an oversized
transaction to the data offload in TX mode. Previously, the data offload
would stop accepting new data (wr_ready <= 0) after filling up the
internal storage, and get stuck waiting for the input transaction to
end, thus locking up the device.
This commit addresses that issue by allowing the data offload to consume
the full input transaction, even if the tail of the buffer will be
truncated in the output.
Note, i am opening this as a **draft** to request feedback, but i haven't finished testing yet!

data_offload: Fix oversized inputs in TX mode

---

library/data_offload/README.md

Correct the  ZCU102 PL DDR memory controller interface width and speed based on available options of the MIG

Update offload README.md

---

.gitignore
library/jesd204/jesd204_rx/jesd204_rx_ip.tcl
library/jesd204/jesd204_tx/jesd204_tx.v
library/jesd204/jesd204_versal_gt_adapter_rx/Makefile
library/jesd204/jesd204_versal_gt_adapter_rx/jesd204_versal_gt_adapter_rx.v
library/jesd204/jesd204_versal_gt_adapter_rx/jesd204_versal_gt_adapter_rx_ip.tcl
library/jesd204/jesd204_versal_gt_adapter_tx/Makefile
library/jesd204/jesd204_versal_gt_adapter_tx/jesd204_versal_gt_adapter_tx.v
library/jesd204/jesd204_versal_gt_adapter_tx/jesd204_versal_gt_adapter_tx_ip.tcl
library/scripts/adi_ip_xilinx.tcl
library/scripts/adi_xilinx_device_info_enc.tcl
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9081_fmca_ebz/vck190/Makefile
projects/ad9081_fmca_ebz/vck190/system_bd.tcl
projects/ad9081_fmca_ebz/vck190/system_constr.xdc
projects/ad9081_fmca_ebz/vck190/system_project.tcl
projects/ad9081_fmca_ebz/vck190/system_top.v
projects/ad9081_fmca_ebz/vck190/timing_constr.xdc
projects/common/vck190/vck190_system_bd.tcl
projects/common/vck190/vck190_system_constr.xdc
projects/common/vmk180/vmk180_system_bd.tcl
projects/common/vmk180/vmk180_system_constr.xdc
projects/common/vmk180_es1/vmk180_es1_system_bd.tcl
projects/common/vmk180_es1/vmk180_es1_system_constr.xdc
projects/scripts/adi_board.tcl
projects/scripts/adi_project_xilinx.tcl
projects/scripts/project-xilinx.mk

This series of changes contains:
- Versal support 
-  Changed cpu interconnect to SmartConnect
- NOC support
- Base design for VMK180, VMK180_ES1, VCK190
- AD9081 project for VCK190
Tested on VCK190 + AD9081

Versal support

---

projects/adrv9009zu11eg/adrv2crr_xmicrowave/Makefile
projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_bd.tcl
projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_constr.xdc
projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_project.tcl
projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_top.v

Add reference design for Xmicrowave on ADRV9009ZU11EG.
It was successfully tested on hardware, using Linux drivers.

Add reference design for Xmicrowave

---

library/common/tb/generate_xml.sh

Replace '<' with '&lt;' and '>' with '&gt;' in ERRS to not broke created xml.

generate_xml.sh: Replace '<'  and '>' in error message

---

library/axi_hdmi_tx/axi_hdmi_tx.v
library/axi_i2s_adi/fifo_synchronizer.vhd
library/axi_i2s_adi/i2s_controller.vhd

On Xilinx UltraScale+ the output DDR FF uses the same ODDRE1 primitive as on Xilinx UltraScale (non "plus"): add it to the Verilog file. Without this, on Xilinx UltraScale+, the resulting design lacks the clock output stage.
Add initialization on the cdc_sync_stage0_tick signals, or the simulation will not work (as cdc_sync_stage0_tick always has 'U' as value).

Minor fixes on axi_hdmi_tx and axi_i2s_adi

---

library/scripts/adi_xilinx_device_info_enc.tcl

This PR addresses the issue https://github.com/analogdevicesinc/hdl/issues/795

library/scripts/adi_xilinx_device_info_enc.tcl: Add K26 support

---

library/axi_adrv9001/adrv9001_rx.v
library/axi_adrv9001/adrv9001_tx.v
library/axi_adrv9001/axi_adrv9001.v
library/axi_adrv9001/axi_adrv9001_if.v
projects/adrv9001/zed/system_bd.tcl

Occasionally with zed, the implementation failed at the placement stage where the tool could not fit the logic cells inside a single clock region, constraint required by the usage of regional clock buffers. 
This commit allows the usage of the global clock buffers which help the tool in such cases and allow a larger application logic to be implemented in fabric.

Fix placement errors for ADRV9001 Zed

---

library/Makefile
library/axi_dmac/axi_dmac_ip.tcl
library/jesd204/scripts/jesd204.tcl
library/util_pad/Makefile
library/util_pad/util_pad.v
library/util_pad/util_pad_ip.tcl
projects/ad_quadmxfe1_ebz/Makefile
projects/ad_quadmxfe1_ebz/common/ad_quadmxfe1_ebz_bd.tcl
projects/ad_quadmxfe1_ebz/common/quad_mxfe_gpio_mux.v
projects/ad_quadmxfe1_ebz/vcu118/Makefile
projects/ad_quadmxfe1_ebz/vcu118/system_bd.tcl
projects/ad_quadmxfe1_ebz/vcu118/system_constr.xdc
projects/ad_quadmxfe1_ebz/vcu118/system_project.tcl
projects/ad_quadmxfe1_ebz/vcu118/system_top.v
projects/ad_quadmxfe1_ebz/vcu118/timing_constr.xdc

This version uses the Xilinx PHY for the 204C modes. Replacing the PHY with the util_adxcvr can be done later since this would break compatibility with excising device trees and would imply a significant amount of work in the Linux side. 
Tested in hardware

Quad MxFE support for Rev C board

---

projects/adrv9009zu11eg/adrv2crr_fmcomms8/system_top.v

The IBUFGDS primitive is deprecated in UltraScale devices.
Tested in hardware.

adrv9009zu11eg/adrv2crr_fmcomms8: Add clock buffers for core clocks

---

projects/ad9081_fmca_ebz/a10soc/system_project.tcl
projects/ad9081_fmca_ebz/a10soc/system_top.v
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_qsys.tcl

For ad9081/a10soc project, the RX_LANE_RATE and TX_LANE_RATE were computed
from SAMPLE_RATE. Remove SAMPLE_RATE and add RX_LANE_RATE and TX_LANE_RATE
as parameters. Update also computation examples from comments.

ad9081_fmca_ebz_qsys.tcl: Add RX_LANE_RATE and TX_LANE_RATE parameters

---

library/axi_adrv9001/intel/adrv9001_rx.v
library/axi_adrv9001/intel/adrv9001_tx.v

This commit fixes failures introduces by https://github.com/analogdevicesinc/hdl/commit/fcb16daf5b16ad7c1838c4ff815f7eafab796071

axi_adrv9001/intel: Add dummy parameters to match Xilinx interface

---

library/jesd204/jesd204_rx/jesd204_lane_latency_monitor.v

Current implementation is correct only for datapath width of 8.
The buswidth of latency measurement inside a beat has a fixed width (3 bits)
for each lane that must be taken in account when computing the total latency.
Tested in simulation.

jesd204_rx/jesd204_lane_latency_monitor.v: Fix for datapath width of 4

---

projects/ad_fmclidar1_ebz/zcu102/system_top.v
projects/adrv9009zu11eg/adrv2crr_fmc/system_top.v
projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_top.v
projects/fmcomms5/zcu102/system_top.v
projects/fmcomms8/zcu102/system_top.v

The IBUFGDS primitive is deprecated in UltraScale devices.

zcu102: ad_fmclidar1_ebz, fmcomms5, fmcomms8 & adrv2crr_fmc: adrv9009zu11eg

---

projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9081_fmca_ebz/vcu128/timing_constr.xdc

Fix the critical warnings introduced by: https://github.com/analogdevicesinc/hdl/pull/808 and https://github.com/analogdevicesinc/hdl/pull/797

ad9081_fmca_ebz: Fix critical warnings

---

README.md

Add in README.md how to use and from where to get already built boot files.
Signed-off-by: Stefan Raus <stefan.raus@analog.com>

README.md: Add link to boot partition files download link

---

projects/ad9081_fmca_ebz/zc706/system_top.v

Corrected the length parameter for the rx_data input.

ad9081_fmca_ebz: Fix signal length parameter

---

projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_bd.tcl

This commit fixes the naming of the second axi_iic interrupt.

xmicrowave: Fix typo

---

library/common/util_pulse_gen.v

This patch fixes an issue where the pulse width is only updated two
periods after the current one.

util_pulse_gen: Reload registers when counter is at one

---

projects/fmcjesdadc1/common/fmcjesdadc1_bd.tcl
projects/fmcjesdadc1/kc705/system_project.tcl
projects/fmcjesdadc1/vc707/system_project.tcl
projects/fmcjesdadc1/zc706/system_project.tcl

fmcjesdadc1: Parameterize JESD204 configuration values

---

library/scripts/adi_xilinx_device_info_enc.tcl

The regex does not work for vcu128. It sets it as Ultrascale instead of Ultrascale+.
The part can be found here: https://github.com/analogdevicesinc/hdl/blob/master/projects/scripts/adi_project_xilinx.tcl#L85
And the regex is here: https://github.com/analogdevicesinc/hdl/blob/master/library/scripts/adi_xilinx_device_info_enc.tcl#L147
I made a build for the project and checked the axi_mxfe_tx_xcvr IP and it has ultrascale set as fpga technology.

scripts/adi_xilinx_device_info_enc.tcl: Change regex for vcu128

---

projects/daq2/common/daq2_bd.tcl
projects/daq2/kc705/system_project.tcl
projects/daq2/kcu105/system_project.tcl
projects/daq2/zc706/system_project.tcl
projects/daq2/zcu102/system_project.tcl

line for the Xilinx FPGAs in the project.

daq2: Parameterize JESD204 configuration values

---

projects/daq3/common/daq3_bd.tcl
projects/daq3/kcu105/system_project.tcl
projects/daq3/vcu118/system_project.tcl
projects/daq3/zc706/system_project.tcl
projects/daq3/zcu102/system_project.tcl

line for the Xilinx FPGAs in the project.

daq3: Parameterize JESD204 configuration values

---

library/common/ad_dds.v

When using a CLK_RATIO > 1 the first n samples(n=CLK_RATIO) after sync, are
noisy. This is because the phase accumulator data is passed to the phase to
amplitude converter, during the phase synchronization step.

ad_dds: Fix DDS start samples

---

library/common/up_adc_common.v
library/common/up_dac_common.v
library/common/up_xfer_cntrl.v
library/common/util_ext_sync.v
library/jesd204/ad_ip_jesd204_tpl_adc/Makefile
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc.v
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_core.v
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_hw.tcl
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_ip.tcl
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_regmap.v
library/jesd204/ad_ip_jesd204_tpl_dac/Makefile
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_core.v
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_hw.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl
library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl

This series of changes refactors the external sync support at the TPL level and applies it to AD9081 and ADRV9009ZU11 designs.
Fixes issue with up_xfer_cntrl that made 1 of 64 transfers fail when used with self clearing bits.
Tested hardware on both platforms. 
VCK190 + AD9082
ZCU102 + AD9081
ADRV9009ZU11 + FMCOMMS8

External sync at TPL level

---

projects/dac_fmc_ebz/common/dac_fmc_ebz_bd.tcl
projects/dac_fmc_ebz/zc706/system_constr.xdc
projects/dac_fmc_ebz/zc706/system_top.v
projects/dac_fmc_ebz/zcu102/system_constr.xdc
projects/dac_fmc_ebz/zcu102/system_top.v

This updated was made for the new VCU118 carrier support

dac_fmc_ebz_bd.tcl: Updated bd for multiple tx_ref_clk

---

projects/dac_fmc_ebz/vcu118/Makefile
projects/dac_fmc_ebz/vcu118/README.md
projects/dac_fmc_ebz/vcu118/system_bd.tcl
projects/dac_fmc_ebz/vcu118/system_constr.xdc
projects/dac_fmc_ebz/vcu118/system_project.tcl
projects/dac_fmc_ebz/vcu118/system_top.v

- New VCU118 Block Design for AD9172(dac_fmc_ebz) eval board
- Tested on NO-OS software with this changes: https://github.com/analogdevicesinc/no-OS/commit/6b3aa74b96938a3c9ac1986378f159309d0cb82e

dac_fmc_ebz_vcu118: Initial commit

---

projects/adrv9009/common/adrv9009_bd.tcl
projects/adrv9009/zc706/system_top.v
projects/adrv9009/zcu102/system_top.v
projects/adrv9371x/common/adrv9371x_bd.tcl
projects/adrv9371x/kcu105/system_top.v
projects/adrv9371x/zc706/system_top.v
projects/adrv9371x/zcu102/system_top.v

Take the ref clock of internal clock generators directly from IBUFDS_GT instead of OUTCLK of the XCVR to remove circular dependency in case of the usage of JESD FSM.  
Tested in hardware on
ADRV9371 + ZCU102
ADRV9371 + ZC706
Tested compile only with all Xilinx projects.

ADRV9371 & ADRV9009 ref clk updates

---

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_core.v

The TPL can have a latency up to two cycles on data path, but current design does not matches the latency of the control path with data path. 
Tested in simulation.

ad_ip_jesd204_tpl_adc: Fix latency of valid signal

---

projects/common/vcu118/vcu118_system_constr.xdc
projects/common/vcu128/vcu128_system_constr.xdc

There are no external termination resistors on the VCU118 for the SGMII
clock lines. The board files enables them, but this was not reflected in the
constraint files.
See: https://ez.analog.com/fpga/f/q-a/551237/unable-to-get-ad9208-dual-ebz-to-acquire-dhcp-address-and-communication-using-static-ip-also-not-working
Tested compile only.

Fix vcu118 vcu128 eth clk

---

projects/adrv9001/common/adrv9001_bd.tcl

axi_adrv9001_tx1_dma/irq is no longer dissconnecting axi_iic_fmc/irq

adrv9001_zed: Fix irq overlap

---

projects/ad9083_evb/common/ad9083_evb_bd.tcl

The change is needed in order to support testbench variable redefine.

ad9083: Using variables instead of hard coded nets

---

projects/scripts/adi_board.tcl

In case of JESD configurations with less than the maximum number of lanes, the other lanes from **util_xcvr** remain unconnected. This error is caused by the **lane_map** list that is passed as a parameter in the **ad_xcvrcon** function so we need to append all the other unused lanes in this list so everything is connected.

projects/scripts/adi_board.tcl: Fix padding error caused by lane_map in ad_xcvrcon procedure

---

library/xilinx/common/ad_data_out.v

In my previous commit I have a typo which generates critical warnings. This should fix it.

xilinx/common:ad_data_out.v: Fix typo

---

projects/cn0506_mii/a10soc/system_project.tcl
projects/cn0506_rgmii/a10soc/system_project.tcl

Remove contraints related to quartus version so that
cn0506_mii and cn0506_rgmii on arria10 to be built
with default quartus version.

cn0506_mii/rgmii on a10soc: update to Quartus 21.2

---

library/axi_clock_monitor/Makefile
library/axi_clock_monitor/axi_clock_monitor.v
library/axi_clock_monitor/axi_clock_monitor_ip.tcl

Issue: library fails on build and returns the following
make[2]: *** No rule to make target axi_clock_monitor_constr.xdc', needed by component.xml'. Stop.
make[1]: *** [lib] Error 2
Fix:
1. replaced .xdc file inside Makefile and axi_clock_monitor_ip.tcl
2. updated verilog file
-fixed typo
-removed PROC_ADDR_WD parameter dependency from wire signals

library/axi_clock_monitor: Fix axi_clock_monitor ip core

---

library/axi_tdd/Makefile
library/axi_tdd/axi_tdd.v
library/axi_tdd/axi_tdd_constr.ttcl
library/axi_tdd/axi_tdd_constr.xdc
library/axi_tdd/axi_tdd_ip.tcl
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl

This allows the external synchronization input to be driven from
asynchronous sources like a 1 PPS signal or just signals from different
clock domains in general.

axi_tdd: Add false paths to tdd sync input

---

projects/common/xilinx/adi_xilinx_ila.tcl

This PR introduces some small helpers to generate ILA cores and XVC infrastructure. The use of these functions in described in this wiki article: https://wiki.analog.com/resources/fpga/docs/xilinx_ila (WIP, not public yet)
Currently these have been fully tested on ZynqMP and partially on Zynq-7000. No Microblaze tests have been performend yet.

common: Add xilinx ila utils

---

library/axi_dmac/address_generator.v
library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_ip.tcl
library/axi_dmac/axi_dmac_regmap.v
library/axi_dmac/axi_dmac_transfer.v
library/axi_dmac/dest_axi_mm.v
library/axi_dmac/request_arb.v
projects/scripts/adi_board.tcl

- Support connecting HPC ports on PS8
- Add register to `axi_dmac` controlling `AxCACHE`
I also have a patch for the `dma-axi-dmac` Linux driver, setting the register if the DMA node in the devicetree has the `dma-coherent` property. Will make a PR if this one is accepted.
The purpose here is to speed up transfers when the CPU should manipulate the samples immediately after transferring them from PL to main memory:
- Without the `dma-coherent` devicetree property, it is assumed that it is unsafe to read addresses from cache that the DMA may have written to (and rightfully so). This means all reads will be from main memory.
- Using the Ultrascale HPC port with `AxCACHE` set accordingly, DMA writes will invalidate the cache at those addresses. This means we can safely set the `dma-coherent` …

Ultrascale DMA via HPC

---

projects/common/vcu128/vcu128_system_bd.tcl

Increased the Microblaze performance for the VCU128 carrier:
-  Enabled branch target cache option
-  Increased the size of Instruction Cache and Data Cache to 64kB
Increased the Microblaze clock frequency:
- Using the DDR4 Controller to generate sys_mb_clk clock of 200MHz and the sys_cpu_clk is obtained by dividing by 2 the sys_mb_clk using a BUFGCE_DIV Utility Buffer.
**Tested on hardware with ad9081_fmca_ebz project!**

vcu128: Increase Microblaze performance and clock frequency

---

projects/ad9081_fmca_ebz/zcu102/system_constr.xdc
projects/ad9081_fmca_ebz/zcu102/system_top.v
projects/ad_quadmxfe1_ebz/common/quad_mxfe_gpio_mux.v
projects/ad_quadmxfe1_ebz/vcu118/system_constr.xdc
projects/ad_quadmxfe1_ebz/vcu118/system_top.v

The MxFE supports two links, so two pairs of SYNC signals are available.  One of them can be used for fast frequency hopping in single link mode or in 64b/66b 204C mode.  
Tested on :
ZCU102 + MxFE
VCU118 + QuadMxFE Rev C

Single/Quad MxFE SYNC refactor

---

library/axi_gpreg/axi_gpreg_ip.tcl

mark axi_gpreg.v as systemverilog, otherwise it gives an error with vivado 2022.1

mark axi_gpreg.v as systemverilog, otherwise it gives an error with vivado 2022.1

---

.gitignore

Almost all the IPs found in library generate a bd folder when they are built. Updated the .gitignore so that it does not appear as an untracked file.
Also, changes to tracked bd.tcl files (ex:axi_dmac) will still appear as modified files.
Signed-off-by: Liviu.Iacob <liviu.iacob@analog.com>

.gitignore: Add the bd.tcl files from built IPs into gitignore

---

projects/ad9081_fmca_ebz/a10soc/system_project.tcl
projects/ad9081_fmca_ebz/a10soc/system_top.v
projects/ad9081_fmca_ebz/vck190/system_constr.xdc
projects/ad9081_fmca_ebz/vck190/system_top.v
projects/ad9081_fmca_ebz/vcu128/system_constr.xdc
projects/ad9081_fmca_ebz/vcu128/system_top.v
projects/ad9081_fmca_ebz/zc706/system_constr.xdc
projects/ad9081_fmca_ebz/zc706/system_top.v

The https://github.com/analogdevicesinc/hdl/pull/922 added support for ZCU102 and VCU118.  This series of changes extends the support for other carriers too. 
The MxFE supports two links, so two pairs of SYNC signals are available. One of them can be used for fast frequency hopping in single link mode or in 64b/66b 204C mode.
Tested compile only for all affected carriers.

MxFE FFH suppor for rest of the carriers

---

.gitignore

Fix gitignore commit 6a6c5ac that did not ignore imbricated bd files.
Signed-off-by: Liviu.Iacob <liviu.iacob@analog.com>

.gitignore: Fix to ignore imbricated bd.tcl files too

---

.gitignore

Added the files generated by Quartus Pro 21.2, 20.1 and Platform Designer for each of the versions. The files added are generated and removed by make.
Signed-off-by: Liviu.Iacob <liviu.iacob@analog.com>

.gitignore: ignore files generated by Quartus & Platform Designer

---

.github/scripts/check_for_missing_readme_md.sh
.github/workflows/test_n_lint.yml

* Updated action to run only in PRs on master branch, on library/ and
projects/ paths
* Edited the text for the printed warnings
* Updated the version for the checkout action from v2 to v3
Signed-off-by: Iulia Moldovan <iulia.moldovan@analog.com>

lint: Update action to run only in PRs

---

projects/adaq8092_fmc/common/adaq8092_bd.tcl

The new revision of the board doesn't need this inversion.

projects/adaq8092_fmc: New board revision update

---

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9081_fmca_ebz/vck190/system_project.tcl

This series of changes allows setting different lane rates and ref clocks for the Versal transceiver. 
Tested compile only on AD9081 + VCK190

Fix ad9081 vck190

---

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9081_fmca_ebz/vck190/system_project.tcl

This series of changes allows setting different lane rates and ref clocks for the Versal transceiver. 
Tested compile only.

Fix ad9081 vck190  for 2021_R1

---

library/axi_ltc2387/axi_ltc2387_channel.v
library/common/ad_datafmt.v
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_channel.v

Currently the data format-er is working in octets which does not suits the JESD N' 12 use cases where the interface towards the DMA/application layer is not 16. 
Tested compile only.

Fix data frmt

---

library/common/ad_pack.v
library/common/ad_upack.v
library/common/tb/ad_pack_tb.v
library/common/tb/run_tb.sh

This update is necessary in order to fix a bug found in simulation for a 3/8 packing ratio. The unpacker is updated in a symmetrical fashion.
By applying this update, the packing IPs should be able to compute every possible packing/unpacking ratio, while optimizing the synthesis output.

Update Packer IPs to be more generic

---

library/scripts/adi_ip_xilinx.tcl
projects/scripts/adi_project_xilinx.tcl
scripts/adi_env.tcl

Update the Vivado version to 2021.2 in 
- library/scripts/adi_ip_xilinx.tcl
- projects/scripts/adi_project_xilinx.tcl

scripts: Update Vivado version to 2021.2

---

projects/scripts/adi_project_intel.tcl
scripts/adi_env.tcl

New version of Quartus Pro for A10SOC, A10GX and S10SOC was changed
to 21.4. Is known that some projects will not build anymore due to
timming violations.

scripts:adi_env Change the default version of Quartus Pro to 21.4

---

projects/ad777x_ardz/de10nano/system_project.tcl
projects/adv7513/de10nano/system_project.tcl
projects/arradio/c5soc/system_project.tcl
projects/cn0540/de10nano/system_project.tcl
projects/scripts/adi_project_intel.tcl

New version of Quartus Standard for de10nano and sockit  was changed
to 21.1.
Signed-off-by: Liviu Adace <liviu.adace@analog.com>

scripts:adi_env: Change the default version of Quartus Standard to 21.1

---

projects/scripts/adi_pd.tcl

For some newer versions of git where by default color.ui=always.
The colored string captured can result in some special characters
(ASCI escape codes for coloring the terminal output) before and after the string.
e.g:
$ git branch > test.txt
$ vim test.txt
"
* ^[[32mmaster^[[m
dev_new_device^[[m"
The above escape codes will mess up a terminals color scheme  when this
information is read from sysid and displayed on a terminal.
Use --no-color flag to fix this issue.

adi_pd.tcl: Fix sysid branch string

---

library/jesd204/axi_jesd204_common/jesd204_up_sysref.v
library/jesd204/axi_jesd204_rx/axi_jesd204_rx.v
library/jesd204/axi_jesd204_rx/jesd204_up_rx.v
library/jesd204/axi_jesd204_tx/axi_jesd204_tx.v
library/jesd204/jesd204_rx/Makefile
library/jesd204/jesd204_rx/elastic_buffer.v
library/jesd204/jesd204_rx/jesd204_rx_hw.tcl
library/jesd204/jesd204_rx/jesd204_rx_ip.tcl
library/jesd204/jesd204_tx/Makefile
library/jesd204/jesd204_tx/jesd204_tx.v
library/jesd204/jesd204_tx/jesd204_tx_gearbox.v
library/jesd204/jesd204_tx/jesd204_tx_hw.tcl
library/jesd204/jesd204_tx/jesd204_tx_ip.tcl
library/jesd204/scripts/jesd204.tcl
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/ad9081_fmca_ebz/zcu102/system_project.tcl
projects/ad9082_fmca_ebz/zcu102/system_project.tcl

- fix for JESD Tx links where gearbox is used with 1:1 ratio  (output data was 0)
- allow narrower TPL width than PHY width for better resource utilization in application layer
- fix buffer adjustment register for reducing Rx link latency
Tested on ZCU102 + AD9082

JESD fixes

---

library/axi_ltc2387/axi_ltc2387.v
library/axi_ltc2387/axi_ltc2387_channel.v
library/axi_ltc2387/axi_ltc2387_if.v
library/axi_ltc2387/axi_ltc2387_ip.tcl
projects/cn0577/common/cn0577_bd.tcl
projects/cn0577/zed/system_bd.tcl
projects/cn0577/zed/system_constr.xdc
projects/cn0577/zed/system_top.v

- Update how adc_valid is made: now it represents the current data sample, as opposed to the earlier version where it was for the previous sample. This caused the first conversion sample to be invalid, but now it's fixed and checked in hardware
- Minor change in constraints file to use now DIFF_TERM TRUE instead of DIFF_TERM 1; it was generated using ad_fmc_constr_generator.tcl
- Aspect changes in the rest of the files, nothing regarding logic

cn0577/zed: Update adc_valid logic

---

projects/ad4630_fmc/zed/Makefile
projects/ad4630_fmc/zed/system_bd.tcl
projects/ad4630_fmc/zed/system_project.tcl
projects/ad4630_fmc/zed/system_top.v
projects/ad9783_ebz/zcu102/Makefile
projects/ad9783_ebz/zcu102/system_project.tcl
projects/ad9783_ebz/zcu102/system_top.v

Rename projects to be identical with the folder name.

Fix naming consistency

---

library/common/tb/run_tb.sh

If 'xvlog' or 'xelab' xilinx commands are failing, exit from run_tb.sh script without trying to run simulation.

run_tb.sh:don't run xsim if previous commands fail

---

projects/ad719x_asdz/Makefile
projects/ad719x_asdz/README.md
projects/ad719x_asdz/coraz7s/Makefile
projects/ad719x_asdz/coraz7s/system_bd.tcl
projects/ad719x_asdz/coraz7s/system_constr.xdc
projects/ad719x_asdz/coraz7s/system_project.tcl
projects/ad719x_asdz/coraz7s/system_top.v

- For AD7190, AD7193, AD7195
- This PR should not be merged until the issue with Cora Z7S' board design is fixed

Add support for AD719x

---

projects/cn0540/common/cn0540_bd.tcl
projects/cn0561/common/cn0561_bd.tcl
projects/pulsar_adc_pmdz/common/pulsar_adc_pmdz_bd.tcl

V1: To maintain compatibility between carriers, the DMA memory interconnect was moved from HP0 to HP1.

The memory interconnect was moved from HP0 to HP1 on Coraz7s projects

---

projects/cn0501/Readme.md
projects/cn0501/common/cn0501_bd.tcl
projects/cn0501/coraz7s/Makefile
projects/cn0501/coraz7s/system_bd.tcl
projects/cn0501/coraz7s/system_constr.xdc
projects/cn0501/coraz7s/system_project.tcl
projects/cn0501/coraz7s/system_top.v

The CN0501 was updated to use axi_ad7768 IP core

---

projects/adrv9009/common/adrv9009_bd.tcl
projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl

Add logic for TX_JESD_L=2/talise (2 for adrv9009, 4 for adrv9009zu11eg_adrv2crr_fmc and 8 for adrv9009zu11eg_fmcomms8).
This changes require the same number RX_OS converters as the TX.

Tx l2 per talise adrv9009

---

docs/regmap/adi_regmap_dmac.txt
library/axi_dmac/axi_dmac_hw.tcl
library/axi_dmac/axi_dmac_ip.tcl
library/axi_dmac/axi_dmac_regmap.v
library/axi_dmac/axi_dmac_regmap_request.v
library/axi_dmac/bd/bd.tcl

Tested with the following testbench: https://github.com/analogdevicesinc/testbenches/tree/dev_DMA_64bit
Currently testing in hardware with the following use case for ZynqMP with DAQ2: https://github.com/analogdevicesinc/hdl/tree/ZynqMP_DDR_HIGH

axi_dmac: Add suport for 64 bit address width

---

docs/regmap/adi_regmap_common.txt

adi_regmap_common.txt: Add missing RD_RAW_DATA field in regmap definition file in commit [d9a861f](https://github.com/analogdevicesinc/hdl/commit/d9a861fb1339be7fa40b2757668d17330f664971);

adi_regmap_common.txt: Add missing RD_RAW_DATA field in regmap definition file

---

docs/regmap/adi_regmap_adc.txt

Fix minor typo in adc regmap which is breaking an external parser.
Signed-off-by: Travis F. Collins <travis.collins@analog.com>

Remove extra FIELD marker in adc regmap

---

projects/scripts/adi_board.tcl

In ad_xcvrcon procedure from adi_board, phy_en_char_align must be connected only when 8B10B encoding is used, otherwise this signal does not exists in the JESD ip and will cause an error.
Signed-off-by: Filip Gherman <Filip.Gherman@analog.com>

adi_board: Connnect phy_en_char_align only for 8B10B encoding

---

library/intel/adi_jesd204/adi_jesd204_hw.tcl

In case of using JESD configurations with more than 6 lanes, Master Clock Generation Block(mcgb) must be enabled for both bonding and non-bonding clock cases when using Stratix 10 H-Tile.

intel/adi_jesd204: Enable master clock generation block for S10 H-Tile

---

library/axi_ad7768/axi_ad7768.v
library/axi_ad777x/axi_ad777x.v
library/axi_ad9265/axi_ad9265.v
library/axi_ad9361/axi_ad9361_rx.v
library/axi_ad9434/axi_ad9434_core.v
library/axi_ad9467/axi_ad9467.v
library/axi_ad9625/axi_ad9625.v
library/axi_ad9671/axi_ad9671.v
library/axi_ad9684/axi_ad9684.v
library/axi_ad9963/axi_ad9963_rx.v
library/axi_adaq8092/axi_adaq8092.v
library/axi_adrv9001/axi_adrv9001_rx.v
library/axi_generic_adc/axi_generic_adc.v
library/axi_ltc2387/axi_ltc2387.v
library/common/up_adc_common.v
library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_regmap.v

up_adc_common:
- Update custom RD/WR mechanism for ADC configuration
- **adc_config_ctrl** - 32 bits : bit 1 - RD ('b1) | WR ('b0), bit 0 - enable WR/RD operation;

up_adc_common: Update custom RD/WR mechanism for ADC configuration

---

library/axi_adrv9001/intel/adrv9001_rx.v

- Issue introduced by [this commit](https://github.com/analogdevicesinc/hdl/commit/173f4a83d492365dad6ca7ad111f952884041a95)
- When IODELAY_ENABLE was inserted in axi_adrv9001_if for adrv9001_rx (Xilinx instance), for Intel instance (intel/adrv9001_rx.v) was omitted and caused a build error for adrv9001/a10soc
- Now it built ok
Signed-off-by: Iulia Moldovan <Iulia.Moldovan@analog.com>

axi_adrv9001/intel: Add dummy parameter IODELAY_ENABLE in adrv9001_rx

---

projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9081_fmca_ebz/vck190/system_project.tcl
projects/ad9081_fmca_ebz/vck190/timing_constr.xdc

This profile corresponds to the default linux profile.
This design has tighter timing constraints so it may fail timing from time to time.
It met timing when I built it two times in a row.

ad9081: vck190: Update default profile

---

projects/scripts/adi_board.tcl

The current procedure will remove the whole net connected to the pin, which is not ok in all cases.
After the update, the command will disconnect the target pin from the net, without modifying the rest of the design

scripts: adi_board: Update ad_disconnect procedure

---

projects/scripts/adi_board.tcl

In situations when multiple TX axi_xcvr's are connected to only one util_xcvr, the common channels need to be connected using the updated index $m(current axi_xcvr lane + the max number of lanes used by the previous connections)

adi_board.tcl: Support multiple common channels connections between different TX axi_xcvr's and one util_xcvr

---

library/axi_ad7768/axi_ad7768_if.v

If the sampling clock is lower than dclk * number_of_active_lines * 32 the interface should wait for the next adc_ready signal to reset the counter. The adc_valid_p signal should be set high just for a clock period after the sample was captured.

library/axi_ad7768: Data valid signal updates to support lower sample rates with the same dclk.

---

projects/ad7606x_fmc/zed/system_constr.xdc
projects/ad7606x_fmc/zed/system_top.v

ad7606x:
- Fix gpio instances from the system_top module;

ad7606x: Fix system_top module's gpio instances

---

docs/regmap/adi_regmap_adc.txt
docs/regmap/adi_regmap_common.txt

The adi_regmap_adc.txt and adi_regmap_common.txt were updated to match the currently approved version of the [Wiki Register Map](https://wiki.analog.com/resources/fpga/docs/hdl/regmap) page.

docs/regmap: Updates on regmap text files.

---

projects/scripts/adi_project_intel.tcl

bug:
say "make LVDS_CMOS_N=0"
- will set ad_project_dir as LVDSCMOSN0
- will then set system_qip_file as LVDSCMOSN0/system_bd/synthesis/system_bd.qip
- build error reveals system_bd can't be found
- maybe due to setting ad_project_dir as a relative file path 
fix:
- set ad_project_dir as an absolute file path

adi_project_intel.tcl: bugfix for ad_project_dir

---

library/axi_ad7768/Makefile
projects/cn0579/Makefile
projects/cn0579/coraz7s/Makefile
projects/cn0579/de10nano/Makefile
projects/cn0579/de10nano/system_project.tcl
projects/cn0579/de10nano/system_top.v

- Quartus version was updated
- the start_n output port was deteled from system_top.v
- the ""mixed_port_feed_through_mode" parameter of RAM can not have value "old"" warning was disabled
- update Makefile copyright year

projects/cn0579/de10nano: Fix Critical Warnings

---

library/scripts/adi_xilinx_device_info_enc.tcl

Add detection scenario for xazu*, xczu*, xqzu* and ultrascale+ packages.
Requested on EZ.

adi_xilinx_device_info_enc: Enlarge detection

---

library/axi_ad7606x/axi_ad7606x.v
projects/ad7606x_fmc/common/ad7606x_bd.tcl

- [axi_ad7606x: Fix data width and order of ADC channels](https://github.com/analogdevicesinc/hdl/commit/3af72779a2814841b27bbda7587b5485c179be03)
- [ad7606x_fmc: Fix up_cpack2 module's SAMPLE_DATA_WIDTH parameter](https://github.com/analogdevicesinc/hdl/commit/462ec6adfdd80067f4f7b0c2a5b9e5f535027f00)

ad7606x: Fix axi control module's data width and channels order, and up_cpack2 module's SAMPLE_DATA_WIDTH

---

projects/scripts/adi_project_xilinx.tcl

The ADI_EXTRACT_PORTS variable is used to extract all the ports and nets properties of the desired IPS for the HighSpeedConverterToolbox to be later used for generating the json files automatically.
The ADI_SKIP_SYNTHESIS variable is used to stop the building process before the synthesis when used with Matlab support as it is not necessary at this point.
The ADI_MATLAB variable is used to choose the correct paths when building the design when using the HWA workflow.
The updated script has been tested along with this branch: https://github.com/analogdevicesinc/HighSpeedConverterToolbox/tree/update_to_hdl_master 
using the following build command:
make -C ./CI/scripts build HDLBRANCH=adi_project_xilinx_matlab
then using the HWA.

adi_project_xilinx.tcl: Add matlab env variables

---

library/scripts/library.mk
projects/scripts/project-xilinx.mk

Added `gui`, `*.runs` and `*.gen` for _library_ IP's to be removed when running `make clean`.
As for _projects_, added `gui` only (as the others exist already).

Update CLEAN_TARGET list for "make clean" command

---

.github/scripts/check_guideline.py
.github/workflows/check_for_guideline_rules.yml

* Updated the versions for repos and this solved the deprecated command issue
(See here the issue solved in the used repo: https://github.com/Ana06/get-changed-files/issues/19)
* Changed the end message for when the guideline is not followed

py script & action: Update used repos version

---

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9081_fmca_ebz/vck190/system_project.tcl
projects/ad9081_fmca_ebz/vck190/system_top.v
projects/ad9081_fmca_ebz/vck190/timing_constr.xdc
projects/ad9082_fmca_ebz/vck190/Makefile
projects/ad9082_fmca_ebz/vck190/system_bd.tcl
projects/ad9082_fmca_ebz/vck190/system_project.tcl
projects/ad9209_fmca_ebz/vck190/system_top.v

- Removes the _reset_tx_pll_and_datapath_in_ reset
- Connects _gtreset_in_ to make use of the master reset found inside the Transceiver Bridge IP
- Connects the necessary signals for the master reset between the Transceiver Wizard and Transceiver Bridge
- Fixes the TX link at higher lane rates (>13GSPS) on AD9081 & AD9209 with vck190.
- Adds vck190 support for the AD9082
Related to PR #1112

Change reset for Versal transceivers and port ad9082 to vck190

---

projects/scripts/adi_project_xilinx.tcl

- project_xilinx.tcl: Fix the regex expression for Kria KV260 evaluation board - [link](https://github.com/analogdevicesinc/hdl/commit/269e9fbe2ca6c17ec9489f355deea04c675843fc) (collapse the expression to xck26 in order to include only the kv260 board)

project_xilinx.tcl: Fix the regex expression for Kria KV260 evaluation board

---

library/scripts/adi_xilinx_device_info_enc.tcl

- adi_xilinx_device_info: Update speed_grade_list;
- Add k26i's specific speed grade id (k26SOM-i);
- Add k26c's specific speed grade id (k26SOM-c, kv260, kr260);
- Started from [this EZ thread](https://ez.analog.com/fpga/f/q-a/571731/adrv9002-k26i---unsupported-speed-grade--2lvi)

adi_xilinx_device_info: Update speed_grade_list

---

projects/ad4110/README.md
projects/ad4134_fmc/Readme.md
projects/ad4630_fmc/Readme.md
projects/ad469x_fmc/Readme.md
projects/ad5766_sdz/Readme.md
projects/ad6676evb/Readme.md
projects/ad7134_fmc/Readme.md
projects/ad7606x_fmc/Readme.md
projects/ad7616_sdz/Readme.md
projects/ad777x_ardz/Readme.md
projects/ad9081_fmca_ebz/Readme.md
projects/ad9082_fmca_ebz/Readme.md
projects/ad9208_dual_ebz/Readme.md
projects/ad9213_dual_ebz/Readme.md
projects/ad9783_ebz/Readme.md
projects/ad_fmclidar1_ebz/Readme.md
projects/ad_quadmxfe1_ebz/Readme.md
projects/adaq8092_fmc/Readme.md
projects/adrv9009/Readme.md
projects/adrv9364z7020/Readme.md
projects/adv7511/Readme.md
projects/adv7513/Readme.md
projects/cn0363/Readme.md
projects/cn0501/Readme.md
projects/cn0561/Readme.md
projects/cn0577/Readme.md
projects/cn0579/Readme.md
projects/dac_fmc_ebz/Readme.md
projects/fmcadc5/Readme.md
projects/fmcjesdadc1/Readme.md

Includes updates to wiki pages:
AD713x, [wiki](https://wiki.analog.com/resources/eval/user-guides/ad713x/hdl)
AD4134, [wiki](https://wiki.analog.com/resources/eval/user-guides/ad4134/hdl)
CN0561 [wiki](https://wiki.analog.com/resources/eval/user-guides/cn0561/hdl)
need approval.
Incomplete Readmes include:
[ad9083_vna](https://github.com/analogdevicesinc/hdl/tree/master/projects/ad9083_vna)
[adaq8092_fmc](https://github.com/analogdevicesinc/hdl/tree/master/projects/adaq8092_fmc)
[adv7513](https://github.com/analogdevicesinc/hdl/tree/master/projects/adv7513)
[cn0501](https://github.com/analogdevicesinc/hdl/tree/master/projects/cn0501)
[cn0579](https://github.com/analogdevicesinc/hdl/tree/master/projects/cn0579)
[usrpe31x](https://github.com/analogdevicesinc/hdl/tree/master/projects/usrpe31x …

Readme updates

---

library/jesd204/axi_jesd204_common/axi_jesd204_common_ip.tcl
library/jesd204/axi_jesd204_rx/axi_jesd204_rx_ip.tcl
library/jesd204/axi_jesd204_tx/axi_jesd204_tx_ip.tcl
library/jesd204/jesd204_common/jesd204_common_ip.tcl
library/jesd204/jesd204_rx/jesd204_rx_ip.tcl
library/jesd204/jesd204_tx/jesd204_tx_ip.tcl
library/util_cdc/util_cdc_ip.tcl
library/util_cic/util_cic_ip.tcl
library/util_pack/util_upack2/util_upack2_ip.tcl

This issue was raised when building with Vivado 2023.1, and to ensure backwards compatibility, **these changes are being introduced while having Vivado 2022.2**. With this, many projects are still failing when using Vivado 2023.1.
Solution from here: https://support.xilinx.com/s/article/69320?language=en_US
Brought changes to the following IPs:
- util_cdc
- util_cic
- jesd204_rx/tx
- util_upack2
- axi_jesd204_common: used in axi_jesd204_rx/tx
- axi_jesd204_rx/tx
- jesd_common
Needs to be merged after #1136

Fix error regarding hierarchy that Vivado misses

---

projects/scripts/adi_fmc_constr_generator.tcl

Constraint generation for intel got stuck after generating the first batch of serial_data

scripts/adi_fmc_constr_generator: Fix intel constr generation

---

projects/scripts/adi_project_xilinx.tcl

project_xilinx.tcl: Fix the regex expression for Kria KV260 eval board.

project_xilinx.tcl: Fix the regex expression for Kria KV260

---

projects/cn0561/coraz7s/system_constr.xdc

The busy_sync pulse was replaced by an axi pwm generator IP, so the constraint in xdc file is no longer needed.

cn0561: Fixed critical warning during make

---

library/xilinx/common/ad_data_in.v

Add single data rate support to ad_data_in. This will help in adding IODELAYs to non designs that don't need dual data rate.

xilinx/ad_data_in.v: Add SDR support

---

projects/scripts/project-intel.mk

Change necessary to build intel projects with different system_top verilog files.
This was patterned to https://github.com/analogdevicesinc/hdl/blob/ae09b8a1bb123a40d2b9c112e3049f79755f2a7b/projects/scripts/project-xilinx.mk#L70

project-intel.mk: change 'system_top.v' to '$(wildcard system_top*.v)'

---

library/axi_adrv9001/axi_adrv9001_core.v
projects/jupiter_sdr/system_bd.tcl
projects/jupiter_sdr/system_top.v

Fix DDS second channel sync.
PL sysmon updates:
- add checks for a different power supply
- connect pl_sysmon interrupt, required by the Linux driver.
Change SD card controller to autodir configuration.

jupiter sdr: Updates

---

library/data_offload/data_offload.v
scripts/adi_env.tcl

- Updated the Vivado version to 2023.1
- Fixed an error in the data_offload IP regarding the MEM_TYPE parameter

Update to Vivado 2023.1

---

projects/pluto/Makefile
projects/pluto/Readme.md
projects/pluto/system_bd.tcl
projects/pluto/system_constr.xdc
projects/pluto/system_top.v

This commit adds support for ADALM-PHASER, allowing the user to choose between the default PlutoSDR mode and Phaser mode through a software controlled GPIO pin: _phaser_enable_.
The Generic TDD Engine was integrated to output a logic signal on the L10P pin, which connects to the input of the ADF4159, when receiving an external synchronization signal on the L12N pin from the Raspberry Pi. Two additional TDD channels are used to synchronize the TX/RX DMA transfer start.

pluto: Enable phaser integration

---

projects/ad9083_evb/a10soc/system_qsys.tcl

Tested on hardware.
Works, but jesd_status reports "measured link clock" as being double the value of "reported link clock".

ad9083_evb/a10soc: Overwrite spi frequency

---

projects/ad4630_fmc/common/ad4630_fmc.txt
projects/ad4630_fmc/zed/system_constr.xdc
projects/ad4630_fmc/zed/system_constr_4sdi.xdc
projects/common/zed/zed_system_constr.xdc

- Added projects/ad4630_fmc/common/ad4630_fmc.txt for initial constraint generation option.
- Added FMC pinout comments to the existing .xdc files for identification:
- projects/ad4630_fmc/zed/system_constr.xdc
- projects/ad4630_fmc/zed/system_constr_4sdi.xdc
- Added FMC i2c pinout comments to projects/common/zed/zed_system_constr.xdc for identification.

FMC pinout configurations for AD4630.

---

projects/cn0561/common/cn0561_fmc.txt
projects/cn0561/coraz7s/system_constr.xdc
projects/cn0561/zed/system_constr.xdc

This PR covers the SPI Engine project checking and updates. Changes and additions include:
- Added txt description of all FMC pins used/unused
- Updated constraint files with FMC pinout location for Zed and Cora carrier boards
Hardware test with available software:
* CN0561 NO-OS updated for new HDL design (PWM trigger for SPIE offload)
- CN0561-Zed **successful** test - ADC conversion 1MHz ODR
- CN0561-Cora    **failed**    test - 0V on ADC output channel 
PR opened on NO-OS repo to introduce HDL design related changes. Merged into NO-OS master.

projects/cn0561: Update SPIE project. FMC pinout. Software test

---

projects/ad4134_fmc/common/ad4134_fmc.txt
projects/ad4134_fmc/zed/system_constr.xdc

This PR covers the AD4134 SPI Engine project checking and updates. Changes and additions include:
* Added txt description of all FMC pins used/unused
* Updated constraint files with FMC pinout location
Hardware test with available software:
* Linux: Test **partially successful**. A dc signal is obtained. [ad4134 Linux driver](https://github.com/analogdevicesinc/linux/blob/529d8ebd2ca325649c04c62416f675d5afd8f8a4/drivers/iio/adc/ad4134.c)
* NO-OS: Tested **failed**. It cannot communicate with the chip on the evaluation board.
[AD413X NO-OS project](https://github.com/analogdevicesinc/no-OS/tree/master/projects/ad413x) Debugger log: dev_init fails. dev_id should be 4, but it is always 0. Changes in NO-OS must be made in order to recognize the chip.

projects/ad4134_fmc: Update SPIE project. Add FMC pinout. Test soft support on hardware

---

projects/ad7134_fmc/common/ad7134_fmc.txt
projects/ad7134_fmc/zed/system_constr.xdc

This PR covers the AD7134 SPI Engine project checking and updates. Changes and additions include:
* Added txt description of all FMC pins used/unused
* Updated constraint files with FMC pinout location
Hardware test with available software:
AD7134 NO-OS **needs updating** for new HDL design (PWM trigger for SPIE offload)
NO-OS PR not yet up, waiting for CN0561 PR to see what soft team expects.
Test **failed**. Initialization of ADC device fails. Debug log:
* ad713x_init failed due to CHIP_TYPE == 0, it should be CHIP_TYPE == 7
* first ad713x device (ADC chs 0-3) CHIP_TYPE not initialized 
* second ad713x device (ADC chs 3-7) initialized successfully
Force initialization via the Vitis debugger ==> 0V on ADC channels, conversation fails

projects/ad7134_fmc: Update AD7134 SPIE project. Add FMC pinout. Test software support

---

projects/adaq7980_sdz/Readme.md
projects/adaq7980_sdz/common/adaq7980_bd.tcl
projects/adaq7980_sdz/common/adaq7980_fmc.txt
projects/adaq7980_sdz/zed/Makefile
projects/adaq7980_sdz/zed/system_bd.tcl
projects/adaq7980_sdz/zed/system_constr.xdc
projects/adaq7980_sdz/zed/system_top.v

I replaced the SPI Engine connections in the adaq7980_bd.tcl with the spi_engine_create procedure found in the spi_engine.tcl script. Through these changes, a more generic instantiation for the spi_engine can be achieved. I configured the parameters for axi_pwm_gen and axi_clkgen according to the results in the SPI_Engine_Timing_Computations Excel where I created a file for adaq7980.
I created the adaq7980_fmc.txt file for generating the system_constr.xdc file. I modified the system_bd.tcl, system_top.v, system_constr.xdc and Readme.md files. Also I regenerated the Makefile. It was tested in NO-OS. I created a new branch: update_adaq7980_noos_spi_engine in the NO-OS repository where I made some changes. The project works on this branch.

Update adaq7980 spi engine

---

projects/ad5766_sdz/Readme.md
projects/ad5766_sdz/common/ad5766_fmc.txt
projects/ad5766_sdz/zed/system_constr.xdc

The functionality of the ad5766 project was verified with SPI Engine. Over the old version it was created the ad5766_fmc.txt file for generating the system_constr.xdc file. Also it was updated the system_constr.xdc and Readme.md files. Tested with NO-OS. No correct signals were obtained from the DAC output channels.

Update ad5766 spi engine

---

projects/ad738x_fmc/Readme.md
projects/ad738x_fmc/common/ad738x_bd.tcl
projects/ad738x_fmc/common/ad738x_fmc.txt
projects/ad738x_fmc/zed/Makefile
projects/ad738x_fmc/zed/system_bd.tcl
projects/ad738x_fmc/zed/system_constr.xdc
projects/ad738x_fmc/zed/system_project.tcl
projects/ad738x_fmc/zed/system_top.v

I replaced the SPI Engine connections in the ad738x_bd.tcl with the
spi_engine_create procedure found in the spi_engine.tcl script. Through
these changes, a more generic instantiation for the spi_engine can be
achieved. I also added ad738x_fmc.txt file for generating the system_constr.xdc file.
Tested with NO-OS. Only one channel works, partially.

Update ad738x spi engine

---

projects/pulsar_adc_pmdz/common/pulsar_adc_pmdz_fmc.txt
projects/pulsar_adc_pmdz/common/pulsar_adc_pmdz_pmod.txt
projects/pulsar_adc_pmdz/coraz7s/system_constr.xdc

I replaced the SPI Engine connections in the pulsar_adc_pmdz_bd.tcl with the
spi_engine_create procedure found in the spi_engine.tcl script. Through
these changes, a more generic instantiation for the spi_engine can be
achieved. I have update system_constr.xdc file and added pulsar_adc_pmdz_pmod.txt. Tests were done on the eval-ad7689-ebz and eval-ad7984-pmdz boards. Linux part works good on AD7689 if only one channel is selected and partially on AD7984.

Update SPI Engine PULSAR ADC PMDZ

---

projects/scripts/adi_board.tcl
projects/scripts/adi_project_xilinx.tcl

Commit 5db7574 switched ad_cpu_interconnect from SmartConnect to AXI Interconnect for Zynq-7000 family SoC. What is the reason ad_mem_hpx_interconnect still uses SmartConnect for all chips? Would the use of Interconnect for HP ports like in this PR have any drawbacks?

Zynq-7000 AXI Interconnect vs SmartConnect

---

docs/library/spi_engine/instruction-format.rst
library/spi_engine/spi_engine_execution/spi_engine_execution.v

This PR fixes observed behavior of the Chip-Select and Sleep instructions not matching the documentation. A separate testbench was created for this behavior on [a fork](https://github.com/LBFFilho/testbenches/tree/spi_engine_instruction_fix). A corresponding PR will be created for the testbench. To run it, simply go to the testbenches/pulsar_adc_pmdz directory, and run
`make CFG=cfg1 TST=sleep_delay_test`
According to the [documentation on the wiki](https://wiki.analog.com/resources/fpga/peripherals/spi_engine/instruction_format), the Sleep instruction should sleep for
`sleep_time = (t + 1) * ((div + 1) * 2) / f_clk`
where "t" is the parameter given to the sleep instruction. However, the current SPI engine implementation (before this PR) actually sleeps for double the duration, due to the …

SPI Engine: Fixed delay behaviour on Chip-Select and Sleep instructions

---

projects/ad9213_dual_ebz/s10soc/Makefile
projects/ad9213_dual_ebz/s10soc/system_qsys.tcl
projects/adrv9009/s10soc/Makefile
projects/adrv9009/s10soc/system_qsys.tcl
projects/common/s10soc/Makefile
projects/common/s10soc/s10soc_system_qsys.tcl

The sysid IP was added in ad9209_fmca_ebz/vck190, ad9213_dual_ebz/s10soc and adrv9009/s10soc

projects: Add missing sysid IP

---

library/axi_ad7606x/axi_ad7606x_ip.tcl

axi_ad7606x: Add the correct IP's name [Critical Warning generated by the incorrect name in the `adi_ip_files` function];

axi_ad7606x: Add the correct IP's name

---

docs/projects/ad7616_sdz/index.rst

The axi_spi_engine IP info was duplicated in the HDL related section.

docs/ad7616: Remove duplicated info

---

.github/workflows/check_for_guideline_rules.yml
.github/workflows/test_n_lint.yml

Renamed the branch on which the actions are run on, from ``master`` to ``main`` due to the renaming of the default branch.
Otherwise these actions are not triggered.

.github/workflows: Rename branch name for GitHub actions

---

scripts/adi_env.tcl

* The version is set to be `23.2.0` because this is what Quartus returns as value when running the --version command
* Still, Quartus has as installation path `intelFPGA_pro/23.2` and not the version which contains an additional `.0`
* Intel projects failing: adv7513/de10nano, but this one uses Quartus Standard and not Quartus Pro whose version is updated now

adi_env.tcl: Update Quartus Pro version to 23.2.0

---

docs/library/spi_engine/index.rst
docs/library/spi_engine/instruction-format.rst
docs/library/spi_engine/pipeline-delays.rst
docs/library/spi_engine/spi_engine_delays.rst

Add documentation for  the different delays on the command path and data path, including communication between submodules and instruction execution overhead.

SPI Engine: Add execution delay documentation

---

docs/library/axi_dmac/block_diagram.svg
docs/library/axi_dmac/index.rst
docs/regmap/adi_regmap_dmac.txt
library/axi_dmac/Makefile
library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_constr.ttcl
library/axi_dmac/axi_dmac_hw.tcl
library/axi_dmac/axi_dmac_ip.tcl
library/axi_dmac/axi_dmac_pkg_sv.ttcl
library/axi_dmac/axi_dmac_regmap.v
library/axi_dmac/axi_dmac_regmap_request.v
library/axi_dmac/axi_dmac_reset_manager.v
library/axi_dmac/axi_dmac_response_manager.v
library/axi_dmac/axi_dmac_transfer.v
library/axi_dmac/bd/bd.tcl
library/axi_dmac/dmac_sg.v
library/axi_dmac/request_arb.v
library/util_hbm/util_hbm.v
projects/arradio/common/arradio_qsys.tcl
projects/fmcomms2/common/fmcomms2_bd.tcl

This commit introduces a different interface to submit transfers, using DMA descriptors.
The structure of the DMA descriptor is as follows:
struct dma_desc {
u32 flags,
u32 id,
u64 dest_addr,
u64 src_addr,
u64 next_sg_addr,
u32 y_len,
u32 x_len,
u32 src_stride,
u32 dst_stride,
};
The 'flags' field currently offers two control bits:
- bit 0: if set, the transfer will complete after this last descriptor is processed, and the DMA core will go back to idle state; if cleared, the next DMA descriptor pointed to by 'next_sg_addr' will be loaded.
- bit 1: if set, an end-of-transfer interrupt will be raised after the memory segment pointed to by this descriptor has been transferred.
The 'id' field corresponds to an identifier of the descriptor.
The 'dest_addr' and 'src_addr' contain the …

axi_dmac: Add support for DMA Scatter-Gather

---

docs/library/spi_engine/instruction-format.rst
library/spi_engine/spi_engine_execution/spi_engine_execution_ip.tcl

I have updated the documentation for the SPI. I had to modify spi_engine_execution_ip.tcl because the scripts are using it for some strings.

doc: Fixed SPI documentation consistency

---

library/jesd204/jesd204_common/jesd204_common_ip.tcl

The lack of the create_xgui_files causes Vivado to exit with an error when running
multiple Vivado instances (parallel make case).
`jesd204_common` was missing this tcl command.
To reproduce
```
(cd library ; make clean all -j8)
```
Fails on main, but not with the fix.
Important: the ip.log between branches are identical, the only difference is that 
Vivado exists with an error code at main.
Tested with Vivado 2022.2 and 2023.1.

library: jesd204: Fixup Vivado exiting with error

---

.gitignore
projects/scripts/project-intel.mk
projects/scripts/project-xilinx.mk

This PR fixes  clean-all target and adds ,lock files to the git ignore list.

Fix make clean

---

library/util_axis_fifo/util_axis_fifo.v

Added missing signal drivers for tlast and tkeep that would otherwise produce a no driver warning, which can lead to unexpected behavior of the design. 
The new warning that now appears is that the respective signals are hard wire to 0 in case of tlast and to 1 in case of tkeep, but this is isn't a problem at all.

util_axis_fifo: Update

---

projects/adrv9026/Makefile
projects/adrv9026/common/adrv9026_bd.tcl
projects/adrv9026/common/adrv9026_fmc.txt
projects/adrv9026/zcu102/Makefile
projects/adrv9026/zcu102/system_bd.tcl
projects/adrv9026/zcu102/system_constr.xdc
projects/adrv9026/zcu102/system_project.tcl
projects/adrv9026/zcu102/system_top.v

Initial design for Madura (adrv9026) 
Linux and no-OS support tested in hardware

projects/adrv9026: Add reference design for ADRV9026+ZCU102

---

library/spi_engine/spi_engine_execution/spi_engine_execution.v

In case an SPI read was immediately followed by a cs assert, the sdi register
was being cleared one cycle too soon, so that the data being passed on was always 'b0.
This was tested on the pulsar testbenches, and also the ad463x testbenches (for the 
ECHO_SCLK=1 case).

SPI Engine: fix early sdi data clear

---

library/axi_pwm_gen/axi_pwm_gen.sv

Updated the pause_cnt logic. Before this modification, no pwm signal was generated on pwm channel 0.

lib/axi_pwm_gen: Update pause_cnt logic

---

projects/cn0540/common/cn0540_ardz.txt
projects/cn0540/common/cn0540_bd.tcl
projects/cn0540/coraz7s/Makefile
projects/cn0540/coraz7s/system_bd.tcl
projects/cn0540/coraz7s/system_constr.xdc
projects/cn0540/coraz7s/system_project.tcl
projects/cn0540/coraz7s/system_top.v

Replaced the SPI Engine connections in the cn0540_bd.tcl with the spi_engine_create procedure found in the spi_engine.tcl. 
Through these changes, a more generic instantiation for the spi_engine can be achieved. 
I also created the cn0540_ardz.txt file.
It was tested with Linux and it worked well.

Update cn0540 spi engine

---

projects/ad9213_dual_ebz/s10soc/system_qsys.tcl
projects/adrv9009/s10soc/system_qsys.tcl

The introduction of sysid IPs on some Stratix 10 projects introduced a problem where they would fail to build, due to `mem_init_sys_file_path` not being defined. This PR fixes this.

s10soc: Fixed a minor issue preventing some projects to be built.

---

library/util_hbm/scripts/adi_util_hbm.tcl
library/util_hbm/util_hbm_ip.tcl
scripts/adi_env.tcl

- Updated the Vivado version to 2023.2
- Corrected the naming of a parameter in _ad_create_util_hbm_ procedure
- Gave valid default value to LENGTH_WIDTH in util_hbm IP
- Rewrote the value Tcl expression for HBM_SEGMENTS_PER_MASTER in util_hbm IP
A more detailed explanation:
The util_hbm IP fix came from the GithHub issue #1237 (AD9081_FMCA_EBZ/VCU128 project) where there were errors regarding `HBM_SEGMENTS_PER_MASTER` and `LENGTH_WIDTH` parameters from util_hbm IP, instantiated by data_offload IP.
`HBM_SEGMENTS_PER_MASTER` parameter was given no value because `LENGTH_WIDTH` didn't have a value from among the list of valid values. So the default value given to LENGTH_WIDTH (was 24) now is 28, from the list of accepted values.
Also, the way the Tcl expression for `HBM_SEGMENTS_PER_MASTER` …

Update to Vivado 2023.2 and fixes to util_hbm IP

---

projects/ad7768evb/Makefile
projects/ad7768evb/zed/Makefile
projects/ad7768evb/zed/system_top.v

In SPI control mode, when not used as GPIO the FILTER pin and when a crystal is used as the clock source, this pin must be set to 1. The START pin must be tied to a logic 1 through a pull-up resistor, when it is not used.

hdl: Zed-AD7768: Wideband fixed bug_2022_R2

---

docs/regmap/adi_regmap_spi_engine.txt
library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/scripts/spi_engine.tcl

Adds registers at dword 0x04 and 0x05, respectively allowing software to get the sizes of the Offload Module memories (command and sdo) or the sizes of the FIFOs on the AXI regmap.
I'm not sure if this is the occasion for incrementing the SPI Engine patch version (or minor version).

SPI Engine: Add registers for Offload memory and FIFO sizes

---

library/spi_engine/interfaces/interfaces_ip.tcl
library/spi_engine/spi_engine_offload/spi_engine_offload_ip.tcl

Minor, non-breaking fixes.
Revert AXI bus signals back to upper case on SPI Engine Offload IP, changed on e2ca5a991aadff875d54c82e8174ba641dc2fb09. Fixup signals from sd*_data_* to sd*_* for spi_engine_ctrl interface. Non-breaking mistake, but added warnings to the IP.
Edit: also solves hanging testbenches due to case-sensitiveness during tb compilation not present during synthesis.
Please replace this comment with summary, motivation and context of the changes.
List any dependencies required for this change.
You can check the checkboxes below by inserting a 'x' between square brackets
(without any other characters or spaces) or just check them after publishing the PR.
If there is a breaking change, specify dependent PRs in description and
try to push all related PRs at the same time.
- …

spi_engine: Revert Offload AXI signals, ctrl fixup

---

projects/max96724/Makefile
projects/max96724/Readme.md
projects/max96724/kv260/Makefile
projects/max96724/kv260/system_bd.tcl
projects/max96724/kv260/system_constr.xdc
projects/max96724/kv260/system_project.tcl
projects/max96724/kv260/system_top.v

This commit adds the GMSL-based reference design for the Kria KV260 evauation kit (using TIER-IV's camera C1 with integrated GMSL serializer - YUV422 data format).

projects/max96724/kv260: Initial commit

---

library/axi_clock_monitor/axi_clock_monitor.v

- The IP was building correctly only with the ID set to 0, because the ID section was included in the register selector, but the ID part in the register addresses is 6'b0. 
- For this reason when the ID was other then 0, the relevant part of the IP fell out during synthesis.

 Fixing register selection for any ID in 'library/axi_clock_monitor/axi_clock_monitor.v'.

---

library/axi_pwm_gen/axi_pwm_gen_regmap.sv

Replaced blocking assignments with non blocking in reset, in the register map write side.
Lattice tools give error for using blocking assignments at one side and non blocking in the other.

Assignment fix in reset, in library/axi_pwm_gen/axi_pwm_gen_regmap.sv

---

docs/projects/ad4630_fmc/adaq42xx_hdl_cm0_cz2_1.svg
docs/projects/ad4630_fmc/adaq42xx_hdl_cm1_cz2_1.svg
docs/projects/ad4630_fmc/index.rst
docs/projects/index.rst
projects/ad4630_fmc/common/ad4030_fmc.txt
projects/ad4630_fmc/common/ad463x_bd.tcl
projects/ad4630_fmc/common/adaq42xx_fmc.txt
projects/ad4630_fmc/zed/README.md
projects/ad4630_fmc/zed/system_constr.xdc
projects/ad4630_fmc/zed/system_top.v

Added initial version of adaq42xx with and without fully isolated power supply based on AD463x

ADD adaq42xx

---

library/util_do_ram/util_do_ram.v

Updated the util_do_ram to hold the keep value as well, not just the data. 
This part is required for the testbenches to pass if the keep is enabled for the verification IPs, which is on. 
Tested on data_offload and data_offload_2 testbenches with a branch: https://github.com/analogdevicesinc/testbenches/pull/82

util_do_ram: Added keep signal to the FIFO

---

projects/scripts/project-xilinx.mk

With the new `make -jX` support, flock is used but shells out sometimes. This assumes a bash like shell which isn't always the case. This fix forces flock to use sh.
PR to trigger the CI

Tell flock to use sh

---

library/spi_engine/axi_spi_engine/axi_spi_engine_hw.tcl
library/spi_engine/spi_engine_offload/Makefile
library/spi_engine/spi_engine_offload/spi_engine_offload_hw.tcl

Remove nonexistant pulse_gen_* interface on axi_spi_engine_hw.
Add sync_event.v to spi_engine_offload's intel_deps.
This commit:
* Fixes simulation on questa-intel.
* Resolves the following critical warning for spi-engine intel projects:
```
cn0540/de10nano$ grep -rn 'Critical Warning' .
cn0540_de10nano.map.rpt:; pulse_gen_period ; Unknown ; Critical Warning ; Named port was not declared by the instantiated entity ;
cn0540_de10nano.map.rpt:; pulse_gen_width  ; Unknown ; Critical Warning ; Named port was not declared by the instantiated entity ;
cn0540_de10nano.map.rpt:; pulse_gen_load   ; Unknown ; Critical Warning ; Named port was not declared by the instantiated entity ;
```
Note: We should also search for Critical warnings on *.map.rpt files for intel.

spi_engine: Remove nonexistent interface, add dep

---

library/axi_pulsar_lvds/Makefile
library/axi_pulsar_lvds/axi_pulsar_lvds.v
library/axi_pulsar_lvds/axi_pulsar_lvds_channel.v
library/axi_pulsar_lvds/axi_pulsar_lvds_if.v
library/axi_pulsar_lvds/axi_pulsar_lvds_ip.tcl
projects/pulsar_lvds_adc/Makefile
projects/pulsar_lvds_adc/Readme.md
projects/pulsar_lvds_adc/common/pulsar_lvds_adc_bd.tcl
projects/pulsar_lvds_adc/zed/Makefile
projects/pulsar_lvds_adc/zed/ad7626_system_top.v
projects/pulsar_lvds_adc/zed/ad7960_system_top.v
projects/pulsar_lvds_adc/zed/system_bd.tcl
projects/pulsar_lvds_adc/zed/system_constr.tcl
projects/pulsar_lvds_adc/zed/system_project.tcl

Add support for fast LVDS PulSAR AD762x/AD796x ADC.

PulSAR LVDS

---

docs/library/axi_pwm_gen/block_diagram.svg
docs/library/axi_pwm_gen/index.rst
docs/library/index.rst
docs/regmap/adi_regmap_pwm_gen.txt
library/axi_pwm_gen/Makefile
library/axi_pwm_gen/axi_pwm_gen.sv
library/axi_pwm_gen/axi_pwm_gen_1.v
library/axi_pwm_gen/axi_pwm_gen_constr.sdc
library/axi_pwm_gen/axi_pwm_gen_constr.ttcl
library/axi_pwm_gen/axi_pwm_gen_hw.tcl
library/axi_pwm_gen/axi_pwm_gen_ip.tcl
library/axi_pwm_gen/axi_pwm_gen_regmap.sv

1. External sync sampled on a clock faster than the rest of the core.
- dedicated input clock
- event logic synchronization to core clock
2. External sync force the phase align. The external sync was used to align the phases of enabled pwms, but only after being armed by a load_config signal toggle. This feature lets the user decide between using load_config to arm and wait for a neg-edge of sync or automatic phase align trigger on the ext_sync neg-edge.
3. Force align. Lets the user chose between immediately stopping the active pulses and realigning them, or waiting for all running pulse periods end, before realigning.
4. Start at sync. when feture is activated, the pulses will start immediately after the trigger event. Otherwise, each pulse will start after a period equal to the one for …

axi_pwm_gen: New features based on parameters

---

library/axi_ad9963/axi_ad9963_if.v

This change fixes the Tx2 one sample delay compared to Tx1, due to bad data wiring at the ODDR ports.

Fix axi ad9963 tx2 1 smp delay

---

docs/regmap/adi_regmap_pwm_gen.txt
library/axi_pwm_gen/axi_pwm_gen.sv
library/axi_pwm_gen/axi_pwm_gen_1.v

This changes fix the 100 duty cycle setting of the pwm.
Before the axi_pwm_gen's behavior resampled a 99% duty cycle at the 100% setting.

axi_pwm_gen: Fix 100% duty cycle width

---

docs/library/axi_dmac/index.rst
docs/regmap/adi_regmap_dmac.txt
library/axi_dmac/address_generator.v
library/axi_dmac/axi_dmac.v
library/axi_dmac/axi_dmac_hw.tcl
library/axi_dmac/axi_dmac_ip.tcl
library/axi_dmac/axi_dmac_regmap.v
library/axi_dmac/axi_dmac_transfer.v
library/axi_dmac/bd/bd.tcl
library/axi_dmac/dest_axi_mm.v
library/axi_dmac/dmac_sg.v
library/axi_dmac/request_arb.v
library/axi_dmac/src_axi_mm.v
projects/jupiter_sdr/system_bd.tcl

This PR adds Cache Coherency support for Jupiter SDR. The HPC (High Performance Coherent) interfaces are used in conjunction with the updated AXCACHE/AXPROT AXI signal values to enable cache coherency. 
The DMA was updated to support Cache Coherency for systems with different caching policies, by allowing the user to manually set the AXCACHE/AXPROT values to be different than the default (most commonly used) values when needed. Implemented to work for both Xilinx and Intel systems.

Cache Coherency support for Jupiter SDR

---

library/xilinx/common/ad_mul.v

This commit sets an initial value to an output to avoid triggering simulation failures.
Related to: https://github.com/analogdevicesinc/testbenches/pull/100

xilinx/common: Set the register to an initial value

---

docs/library/spi_engine/instruction-format.rst
docs/regmap/adi_regmap_spi_engine.txt
library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/spi_engine_execution/spi_engine_execution.v

Add a cs_active_high bit to the Configuration Register, which corresponds to the SPI_CS_HIGH linux flag. This bit inverts any CS values at the pin, so the internal logic remains the same. 
Thus when this bit is set, all behaviour that would happen on a negative edge of the CS pin (internal buffer clears) ends up happening on the positive edge.
This way the CS polarity is transparent to software (eg. setting cs to 0xFE is always enabling CS[0], setting it high if cs_active_high is set, or low otherwise). 
A separate test configuration for this setup is found below:
https://github.com/analogdevicesinc/testbenches/pull/89

SPI Engine: create inverted CS mode

---

projects/adrv9026/a10soc/Makefile
projects/adrv9026/a10soc/system_constr.sdc
projects/adrv9026/a10soc/system_project.tcl
projects/adrv9026/a10soc/system_qsys.tcl
projects/adrv9026/a10soc/system_top.v
projects/adrv9026/common/adrv9026_qsys.tcl

Add a10soc support with jesd204B to ad9026

adrv9026/a10soc: Initial design

---

projects/ad7606x_fmc/Readme.md

ad7606x: Reorder and fix mistake in name field from the parts' list

ad7606x: Reorder and fix mistake in name field from the parts' list

---

library/spi_engine/scripts/spi_engine.tcl

At the configuration instantiated by the script, ctrl_clk and spi_clk are always synchronous.
When axi_spi_engine/ASYNC_SPI_CLK=1, the ctrl_offload intf is fully domain crossed from clk to spi_clk.
Thus, spi_engine_offload/ASYNC_SPI_CLK=0.
The projects that use spi_engine_create on main are
```
projects/ad4134_fmc/common/ad4134_bd.tcl
projects/ad4630_fmc/common/ad463x_bd.tcl
projects/ad4630_fmc/common/ad463x_bd.tcl
projects/ad469x_fmc/common/ad469x_bd.tcl
projects/ad7134_fmc/common/ad7134_bd.tcl
projects/ad738x_fmc/common/ad738x_bd.tcl
projects/ad7606x_fmc/common/ad7606x_bd.tcl
projects/ad7616_sdz/common/ad7616_bd.tcl
projects/adaq7980_sdz/common/adaq7980_bd.tcl
projects/cn0363/common/cn0363_bd.tcl
projects/cn0540/common/cn0540_bd.tcl
projects/cn0561/common/cn0561_bd.tcl …
```

spi_engine: scripts: Fix offload clock domain

---

projects/ad469x_fmc/zed/system_top.v

gpio 33 was not referenced anywhere. We can tell by the `31'b0` in the `assign gpio_i` that likely the intent was to use 33 instead of 34 as the end of the range.

ad469x/zed: fix off by one error in gpio_i range

---

docs/regmap/adi_regmap_spi_engine.txt
library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/spi_engine_execution/spi_engine_execution.v

Currently word_length can affect the sleep duration, this fixes it.
Tested with updated testbench (https://github.com/analogdevicesinc/testbenches/pull/110)

SPI Engine: fix word_length affecting sleep

---

CONTRIBUTING.md
docs/user_guide/contributing.rst
docs/user_guide/git_repository.rst
docs/user_guide/index.rst

Added documentation on how to contribute as an external contributor. Both a MarkDown file to be easy to read in the root folder of the repo, and a page in our GitHub pages, with the same content but adapted to rST.

Add CONTRIBUTING.md & .rst

---

library/axi_ad7606x/axi_ad7606x.v

software expects DRP locked to be 1 and it should be set to 1 if not used
https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/commit/?h=testing&id=70a0e10f8ab62ba82b080347ca0a119e14e964c9
Please replace this comment with summary, motivation and context of the changes.
List any dependencies required for this change.
You can check the checkboxes below by inserting a 'x' between square brackets
(without any other characters or spaces) or just check them after publishing the PR.
If there is a breaking change, specify dependent PRs in description and
try to push all related PRs at the same time.

axi_ad7606x: Fix DRP locked

---

library/jesd204/jesd204_versal_gt_adapter_rx/jesd204_versal_gt_adapter_rx.v
library/jesd204/jesd204_versal_gt_adapter_tx/jesd204_versal_gt_adapter_tx.v
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9081_fmca_ebz/vck190/system_bd.tcl
projects/ad9081_fmca_ebz/vck190/system_top.v

Adds necessary changes for proper software support regarding the transceivers reset sequence. 
Tested on VCK190 + MxFE
Requires: https://github.com/analogdevicesinc/linux/pull/2528 to be merged.

FIX: Versal GTY PHY reset sequence

---

projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_top_xmicrowave.v
projects/adrv9026/zcu102/system_top.v
projects/adrv904x/zcu102/system_top.v
projects/cn0585/zed/system_top.v
projects/common/vpk180/system_top.v
projects/pulsar_lvds_adc/zed/ad7626_system_top.v
projects/pulsar_lvds_adc/zed/ad7960_system_top.v
projects/wiki_summary.sh

Made a script to check each link that contains the word "/master" and then replace it with "/main" in all the files from 
the /projects folder.

Replaced master from links with main

---

docs/projects/ad469x_fmc/index.rst
projects/ad469x_fmc/Readme.md
projects/ad469x_fmc/common/ad469x_bd.tcl
projects/ad469x_fmc/zed/system_constr.xdc
projects/ad469x_fmc/zed/system_project.tcl
projects/ad469x_fmc/zed/system_top.v

With the help of SPI_4WIRE parameter, for Conversion Mode, we can link the CNV to SPI_CS for 4-wire SPI interface
functionality. Also, BSY_ALT_GP0 is linked to trigger and GPIO.

AD469x: HDL build parameter

---

projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_project.tcl

Set the default configuration to fmcxmwbr1, so that the project and folder name would be the same.

adrv9009zu11eg/adrv2crr_fmcxmwbr1: Switch default build configuration

---

docs/projects/ad9434_fmc/index.rst
library/axi_ad9434/axi_ad9434_if.v
projects/ad9434_fmc/zed/system_constr.xdc

- Set the adc_clk period to 2.156ns
- Set the frequency to 463.82MHz because on Zedboard, there is a limitation for BUFG input clock frequency to 464MHz, which is below the maximum sampling rate of the ADC (500MSPS)
- Updated the documentation
- Linux PR: https://github.com/analogdevicesinc/linux/pull/2531

projects/ad9434_fmc/zed: Fix timing issue in IP and constraints

---

docs/projects/ad9434_fmc/index.rst
library/axi_ad9434/axi_ad9434_if.v
projects/ad9434_fmc/zed/system_constr.xdc

- Set the adc_clk period to 2.156ns
- Set the frequency to 463.82MHz because on Zedboard, there is a limitation for BUFG input clock frequency to 464MHz, which is below the maximum sampling rate of the ADC (500MSPS) (info based on [DS187, Table 67: Global Clock Switching Characteristics](https://docs.amd.com/v/u/en-US/ds187-XC7Z010-XC7Z020-Data-Sheet) (FMAX_BUFG))
- Updated the documentation
- Linux PR: https://github.com/analogdevicesinc/linux/pull/2532

projects/ad9434_fmc/zed: Fix timing issue in IP and constraints 

---

projects/adrv9009/zc706/system_bd.tcl

The signal integrity for this project was very bad on No-OS.
Upgraded the DMA buffers and clock.

adrv9009_zc706: Upgrade DMA

---

docs/projects/ad4134_fmc/index.rst
docs/projects/ad4630_fmc/index.rst
docs/projects/ad469x_fmc/index.rst
docs/projects/ad5766_sdz/index.rst
docs/projects/ad7134_fmc/index.rst
docs/projects/ad719x_asdz/index.rst
docs/projects/ad738x_fmc/index.rst
docs/projects/ad7606x_fmc/index.rst
docs/projects/ad7616_sdz/index.rst
docs/projects/ad7768evb/index.rst
docs/projects/ad9081_fmca_ebz/index.rst
docs/projects/ad9783_ebz/index.rst
docs/projects/adaq7980_sdz/index.rst
docs/projects/adrv9026/index.rst
docs/projects/adrv904x/index.rst
docs/projects/cn0363/index.rst
docs/projects/cn0540/index.rst
docs/projects/cn0561/index.rst
docs/projects/cn0585/index.rst
docs/projects/pulsar_adc/index.rst
docs/projects/pulsar_lvds/index.rst
docs/projects/template/index.rst

Especially in the HDL Related section, changed all the tags. For all the IPs present on Git Doc, the :dokuwiki: tag used to redirect the user, was changed to :ref: and all the redirects are toward Git Doc, not Wiki. The changes were predominantly in
docs/projects.

docs: Change :dokuwiki: to :ref: tag for ported IPs

---

docs/projects/cn0561/cn0561_hdl.svg
docs/projects/cn0561/index.rst
projects/cn0561/common/cn0561_bd.tcl
projects/cn0561/zed/system_constr.xdc

Change axi_clk_gen output frequency to 100MHz for set DCLK frequency to 50 MHz.
This is a requirement if we set the DCLK pin as an input in slave mode.

cn0561: Set DCLK frequency to 50 MHz

---

library/axi_ad9361/axi_ad9361_tx_channel.v

The unused TX channels are not entirely removed during synthesis when MODE_1R1T is set. These unused channels utilize multipliers and logic elements. This commit disables the TX channels similiar to the RX channel module.
Signed-off-by: Brett Witherspoon <brett@witherspoon.engineering>

axi_ad9361: Fix TX channel disable

---

projects/common/kc705/system_project.tcl
projects/fmcomms2/kc705/system_top.v
projects/fmcomms2/kcu105/system_top.v
projects/fmcomms2/vc707/system_top.v

Investigating the log, I noticed that
```
Instance ..SCK_O_NE_4_FDRE_INST cannot be placed in site OLOGIC_X1Y0 because the output signal of the cell requires general routing to fabric and cells placed in OLOGIC can only be routed to delay or I/O site.
```
Explained in [AMD article 66668](https://support.xilinx.com/s/article/66668?language=en_US).
Even though there is no additional cell in the path beyond the target register (FDRE), the dangling spi_clk_i net seem to trigger the error starting on Vivado 2023.2.
The solution was to remove the spi_clk_i/o loopback on the system_top to ensure only one net in this path, since the target register is instantiated at IP level.
Also, fixup nonexistent file in common/kc705 from system_project.tcl.
@bia1708 can you please remove the fmcomms2 …

fmcomms2: Fix synthesis (Vivado >= 2023.2)

---

projects/ad_gmsl2eth_sl/common/ad_gmsl2eth_sl_bd.tcl
projects/ad_gmsl2eth_sl/k26/system_top.v

- ad_gmsl2eth_sl: Add missing mfp_*_p2 pins to pwm_gen-based logic

ad_gmsl2eth_sl: Add missing mfp_*_p2 pins to pwm_gen-based logic

---

projects/ad9213_evb/vcu118/system_constr.xdc

The build log reported the following Critical Warning:
There are 8 register/latch pins with no clock driven by root clock pin: i_system_wrapper/system_i/hmc7044_spi/U0/NO_DUAL_QUAD_MODE.QSPI_NORMAL/QSPI_LEGACY_MD_GEN.QSPI_CORE_INTERFACE_I/LOGIC_FOR_MD_0_GEN.SPI_MODULE_I/RATIO_NOT_EQUAL_4_GENERATE.SCK_O_NQ_4_NO_STARTUP_USED.SCK_O_NE_4_FDRE_INST/Q (HIGH)
i_hmc7044_spi/spi_count_reg[0]/C
i_hmc7044_spi/spi_count_reg[1]/C
i_hmc7044_spi/spi_count_reg[2]/C
i_hmc7044_spi/spi_count_reg[3]/C
i_hmc7044_spi/spi_count_reg[4]/C
i_hmc7044_spi/spi_count_reg[5]/C
i_hmc7044_spi/spi_enable_reg/C
i_hmc7044_spi/spi_rd_wr_n_reg/C

ad9213_vcu118: Missing generated clock for hmc7044_spi

---

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9209_fmca_ebz/vck190/system_top.v

Implements the necessary changes to support the new Versal reset sequence triggered by the software.
Also fixes the building error that appeared.

Fix: ad9209_fmca_ebz: vck190: Implemented the Versal reset changes

---

projects/ad9265_fmc/zc706/system_constr.xdc

Changed the frequency of adc_clk to 125MHz as it was wrongly set to 300.3MHz.

projects/ad9265_fmc/zc706: Fix adc_clk freq -- 125MHz

---

projects/common/ac701/system_project.tcl
projects/common/coraz7s/system_project.tcl
projects/common/kcu105/system_project.tcl
projects/common/vc707/system_project.tcl
projects/common/vc709/system_project.tcl
projects/common/vcu118/system_project.tcl
projects/common/vcu128/system_project.tcl
projects/common/vmk180/system_project.tcl
projects/common/zc702/system_project.tcl
projects/common/zcu102/system_project.tcl

- Removed all absent system_constr.xdc file calls from Xilinx-related system_project.tcl

projects/common: Removed absent system_constr.xdc file

---

docs/projects/cn0577/cn0577_zed_block_diagram.svg
docs/projects/cn0577/index.rst
docs/projects/index.rst

This PR is made for the CN0577 wiki (https://wiki.analog.com/resources/eval/user-guides/circuits-from-the-lab/cn0577/hdl) HDL documentation migration for GitHubIO.
Also, edited the wiki page and added the warning about the migration of the documentation.
Issue: On the Wiki page, the schematic for CN0577 is not present, even though there is a section dedicated for this matter (clicking on the link will redirect the user on the top of the page)

docs/projects/cn0577: Migrate documentation

---

docs/projects/ad9265_fmc/ad9265_fmc_block_diagram.svg
docs/projects/ad9265_fmc/index.rst
docs/projects/index.rst
projects/ad9265_fmc/zed/Makefile
projects/ad9265_fmc/zed/system_bd.tcl
projects/ad9265_fmc/zed/system_constr.xdc
projects/ad9265_fmc/zed/system_project.tcl
projects/ad9265_fmc/zed/system_top.v

projects/ad9265_fmc/zed: Add HDL project to support ad9265_fmc on zed
docs/projects/ad9265_fmc: Add ad9265_fmc project documentation
Link to devicetree: https://github.com/analogdevicesinc/linux/pull/2407

projects: Port AD9265-FMC to ZedBoard & doc.

---

projects/scripts/adi_pd.tcl

This PR fixes the handling of the path to the sysid memory init file

sysid: Fix mem init file path

---

library/axi_ad9361/axi_ad9361_rx.v

This commit fixes the PN flag generation during calibration when the 1R1T mode is used.
Tested in simulation: https://github.com/analogdevicesinc/testbenches/pull/100

Fix PN error flags generation when 1 RF Channel is used

---

library/scripts/library.mk

Added cleaning of the .lock files for XILINX_LIB_DEPS as well.
For example, the case with axi_dmac, which has util_cdc and util_axis_fifo as dependency libraries:
when running `make clean-all` in a project which uses axi_dmac, this cleaning procedure wouldn't remove the `.lock` from util_cdc and util_axis_fifo, because they are dependencies of a dependency and the cleaning would go only on libraries specified in the Makefile of the project and not further down in the hierarchy. Not removing this lock file would make the build get stuck at the libraries.
Built the AD9265/ZC706 & Zedboard and AD485x/Zedboard and it works.

library/scripts/library.mk: Fix .lock cleaning for IPs requiring other IPs

---

library/jesd204/jesd204_versal_gt_adapter_rx/Makefile
library/jesd204/jesd204_versal_gt_adapter_rx/jesd204_versal_gt_adapter_rx.v
library/jesd204/jesd204_versal_gt_adapter_rx/jesd204_versal_gt_adapter_rx_ip.tcl
library/jesd204/jesd204_versal_gt_adapter_rx/lane_align.v
library/jesd204/jesd204_versal_gt_adapter_tx/Makefile
library/jesd204/jesd204_versal_gt_adapter_tx/jesd204_versal_gt_adapter_tx.v
library/jesd204/jesd204_versal_gt_adapter_tx/jesd204_versal_gt_adapter_tx_ip.tcl
projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl
projects/ad9081_fmca_ebz/common/versal_transceiver.tcl
projects/ad9081_fmca_ebz/vck190/Makefile
projects/ad9081_fmca_ebz/vck190/system_constr.xdc
projects/ad9081_fmca_ebz/vck190/system_project.tcl
projects/ad9081_fmca_ebz/vck190/system_top.v
projects/ad9081_fmca_ebz/vck190/timing_constr.xdc
projects/ad9209_fmca_ebz/vck190/system_top.v

This PR adds the jesd204b support for the AD9081 project on VCK190.

JESD204B support on VCK190

---

projects/ad9081_fmca_ebz/vpk180/system_bd.tcl
projects/ad9081_fmca_ebz/zcu102/system_bd.tcl

The ad9081 + zcu102 project was logging two parameters that didn't exist in the project and were always empty so I removed them.
The ad9081 + vpk180 project was missing the logging of the parameters so I added that.

Sysid parameters fixes

---

docs/library/spi_engine/instruction-format.rst
library/spi_engine/spi_engine_execution/spi_engine_execution.v

Fixes error seen in https://github.com/analogdevicesinc/hdl/issues/1389
Somewhat recently, during https://github.com/analogdevicesinc/hdl/pull/1200, while fixing a related bug, I altered the documentation to reflect what was then the behavior of the SPI Engine for the Sleep instruction: it slept for `t` prescaler ticks. 
What I didn't realize back then was that the intended behavior, as seen on the [first SPI Engine commit](https://github.com/analogdevicesinc/hdl/commit/e6b58e8a20fbcf8aade27a951aa32de0e1ce1ef4), is to sleep for `t+1` ticks, and that there had been a regression in the meantime. 
To illustrate, I've made some simple tests, which call the sleep instruction with a parameter of t=4. Expected behavior is for it to sleep for `t+1` ticks, as seen on first commit and as has been …

SPI Engine: fix off-by-one sleep time

---

docs/library/axi_ad3552r/index.rst
docs/projects/ad5758_sdz/index.rst
docs/projects/adrv904x/index.rst
docs/projects/template/index.rst
docs/user_guide/architecture.rst
docs/user_guide/porting_project.rst

* Fix a mistake in the code snippet from Porting an HDL project page
* Update the links in Architecture, as some of them don't point to the right page and they're not in the right format, and a small change in the template for project doc.
* library/axi_ad3552r: Remove duplicate link to driver
* projects/ad5758_sdz: Fix page name
* projects/adrv904x: Remove trailing whitespaces and update datasheet link and data_offload doc link

docs: Fix mistake in code snippet from Porting page and more

---

docs/user_guide/ip_cores/creating_new_ip.rst

Update the docs to explain the  extended syntax to allow inheritance from multiple register maps.
Related to #1448

docs: Allow inheriting multiple register maps

---

docs/regmap/adi_regmap_jesd_rx.txt
library/jesd204/axi_jesd204_rx/jesd204_up_rx.v

Change up_cfg_buffer_delay assignment from up_wdata [7:0] to [9:2].
Test [axi_jesd204_rx_regmap_tb.v](../blob/6128dd1ab53c9414bce2432457e41919501a1816/library/jesd204/tb/axi_jesd204_rx_regmap_tb.v#L267) was failing at register x90 with output:
```
Address 00000240, Expected 000103fc, Found 000103f0
```
The issue is at fields _Buffer release delay_ [9:2] and _Data path width alignment_ [1:0], the latter is always 2'b00.
Investigating jesd204_up_rx.v, I noticed that up_cfg_buffer_delay is assigned up_wdata[7:0] instead of [9:2], incoherent with the read instruction.
I ran all tests at tb and now all succeeds (xsim, 2023.1).

axi_jesd204_rx: Fixup write to up_cfg_buffer_delay

---

docs/library/axi_ad7606x/index.rst

This interface no longer exists on the ip, and was causing a warning when building the doc:
`WARNING: library/axi_ad7606x/component.xml: Signal external_clk defined in the hdl-interfaces directive does not exist in the IP-XACT!`

docs: remove ad7606 build warning

---

projects/ad9082_fmca_ebz_xmw_rx/Makefile
projects/ad9082_fmca_ebz_xmw_rx/Readme.md
projects/ad9082_fmca_ebz_xmw_rx/zcu102/Makefile
projects/ad9082_fmca_ebz_xmw_rx/zcu102/system_bd.tcl
projects/ad9082_fmca_ebz_xmw_rx/zcu102/system_constr.xdc
projects/ad9082_fmca_ebz_xmw_rx/zcu102/system_project.tcl
projects/ad9082_fmca_ebz_xmw_rx/zcu102/system_top.v
projects/ad9082_fmca_ebz_xmw_tx/Makefile
projects/ad9082_fmca_ebz_xmw_tx/Readme.md
projects/ad9082_fmca_ebz_xmw_tx/zcu102/Makefile
projects/ad9082_fmca_ebz_xmw_tx/zcu102/system_bd.tcl
projects/ad9082_fmca_ebz_xmw_tx/zcu102/system_constr.xdc
projects/ad9082_fmca_ebz_xmw_tx/zcu102/system_project.tcl
projects/ad9082_fmca_ebz_xmw_tx/zcu102/system_top.v

Modifying ad9082_fmca_ebz project to control 2-24GHz XMW TX and RX platforms targeting ZCU102 eval board with an AD9082 in the form of 2 new projects (ad9082_fmca_ebz_xmw_tx and ad9082_fmca_ebz_xmw_rx).
Source code includes peripheral control for ADF4371 (3-wire SPI controlled), ADMV8818 (4-wire SPI controlled) and ADRF5020, ADRF5730, ADRF5740 (GPIO controlled), along with original AD9082 and HMC7044 control.

HDL files for 2-24 GHz XMW TX/RX Platforms

---

docs/conf.py
docs/library/axi_ad485x/index.rst
docs/library/axi_dmac/index.rst
docs/library/spi_engine/instruction-format.rst
docs/library/spi_engine/tutorial.rst
docs/requirements.txt

The purpose of this PR is to fix typos & mistakes that mess up the PDF generation of the doc. More changes will be added as soon as they are caught. PDF generation method is still in progress & is tested on a certain batch of pages that have different functionalities (collapsible content, math formulas etc.).
Doctools PDF output method PR was merged into main (https://github.com/analogdevicesinc/doctools/pull/18).

docs: Cosmetic & functional fixes to comply with PDF generation req.

---

docs/requirements.txt

Small bug, wrong library for PDF output in requirments.txt file which contains all the needed dependencies for doc. building. Also, other important libraries involved in the build process were missing.
The main library needed for PDF export is called rst2pdf. The rest of the libraries are used for improving the
PDF output. For example:
- matplotlib: rst2pdf supports a math role and a math directive.
You can use them to insert formulae and mathematical notation in
your documents using a subset of LaTeX syntax, but doesn't require
you have LaTeX installed
- svglib: needed for .svg files rendering

Fixed PDF library name

---

docs/projects/ad_gmsl2eth_sl/index.rst
library/corundum/corundum.v
library/corundum/corundum_ip.tcl
projects/ad_gmsl2eth_sl/common/ad_gmsl2eth_sl_bd.tcl

Rework assign_bd_address to only provide objects to assign instead of providing a explicit target_address_space.
Aims to fix the error obtained on the CI:
```
ERROR: [BD 5-309] Master address space </corundum/m_axi_dma> does not exist.
while executing
"source ../common/ad_gmsl2eth_sl_bd.tcl"
(file "system_bd.tcl" line 8)
```
I was not able to replicate the error locally.
Synthesized the changed project locally.
Remove duplicated content on doc page.
48c3dff6c0854be5b3daefcdc671e34df0ea30c2 fixes:
```
CRITICAL WARNING: [xilinx.com:ip:smartconnect:1.0-1] system_axi_hpc0_interconnect_0: The device(s) attached to /S00_AXI do not share a common clock domain with this smartconnect instance. Modify the clock domain values of the attached device(s) or re-customize this AXI SmartConnect instance …
```

ad_gmsl2eth_sl: Rework assign_bd_address 

---

docs/projects/cn0579/index.rst

The code blocks that describe the make process needed an extra newline for correct rendering and all the unnecessary whitespaces were deleted.

docs/cn0579: Fixing the make rendering and removing whitespaces

---

docs/projects/pulsar_adc/index.rst
projects/pulsar_adc/Readme.md
projects/pulsar_adc/zed/Makefile
projects/pulsar_adc/zed/system_bd.tcl
projects/pulsar_adc/zed/system_constr_fmc.xdc
projects/pulsar_adc/zed/system_constr_fmc_sm0.xdc
projects/pulsar_adc/zed/system_constr_fmc_sm1.xdc
projects/pulsar_adc/zed/system_constr_fmc_sm2.xdc
projects/pulsar_adc/zed/system_constr_pmod.xdc
projects/pulsar_adc/zed/system_project.tcl
projects/pulsar_adc/zed/system_top_fmc.v
projects/pulsar_adc/zed/system_top_pmod.v

Adding some more build options to cover modes specific to AD7944

pulsar_adc: Add build options to include AD7944

---

library/xilinx/common/ad_serdes_in.v

Adding EXT_SERDES_RESET parameter to the ad_serdes_in module and indentation cosmetics.

library/xilinx/common/ad_serdes_in: Add external reset option

---

docs/library/axi_ad408x/block_diagram.svg
docs/library/axi_ad408x/index.rst
docs/library/index.rst
docs/projects/ad408x_fmc_evb/ad408x_fmc_clock_scheme.svg
docs/projects/ad408x_fmc_evb/ad408x_fmc_evb_zed_block_diagram.svg
docs/projects/ad408x_fmc_evb/index.rst
docs/projects/index.rst
library/axi_ad408x/Makefile
library/axi_ad408x/ad408x_phy.v
library/axi_ad408x/axi_ad408x.v
library/axi_ad408x/axi_ad408x_ip.tcl
projects/ad408x_fmc_evb/Makefile
projects/ad408x_fmc_evb/README.md
projects/ad408x_fmc_evb/common/ad408x_fmc_evb.txt
projects/ad408x_fmc_evb/common/ad408x_fmc_evb_bd.tcl
projects/ad408x_fmc_evb/zed/Makefile
projects/ad408x_fmc_evb/zed/system_bd.tcl
projects/ad408x_fmc_evb/zed/system_constr.xdc
projects/ad408x_fmc_evb/zed/system_project.tcl
projects/ad408x_fmc_evb/zed/system_top.v

This PR adds the following:
- the ad_serdes_in module was modified to allow external reset
- the ad_pack module was modified to allow MSB align 
- the up_adc_common exposes the up_adc_ddr_edgesel, up_adc_num_lanes and up_adc_sdr_ddr_n signals
- AXI_AD408X IP 
- AXI_AD408X IP documentation
- AD4080 project on ZedBoard
- AD4080 project on ZedBoard documentation

Add support for AD408X on ZedBoard 

---

projects/pluto/system_bd.tcl

This PR enables the transfer start synchronization feature on the TX DMA.
Previously, in order to control the timing of the TX buffers, the TDD CH2 was used as a reset for the UPACK, back-pressuring the TX DMA until the reset was de-assereted, thus allowing the DMA to start its transfer. Now, the synchronization mechanism is simpler and mirrors the one on the RX DMA, where a **sync** port is used to trigger the transmission.

pluto: Move TDD CH2 to TX DMA dedicated sync port

---

docs/library/spi_engine/spi_engine_offload.rst
docs/projects/ad57xx_ardz/ad57xx_coraz7s_hdl.svg
docs/projects/ad57xx_ardz/ad57xx_de10nano_hdl.svg
docs/projects/ad57xx_ardz/index.rst
docs/projects/index.rst
library/axi_pwm_gen/axi_pwm_gen_hw.tcl
library/spi_engine/scripts/spi_engine.tcl
library/spi_engine/spi_engine_offload/spi_engine_offload.v
library/spi_engine/spi_engine_offload/spi_engine_offload_hw.tcl
library/spi_engine/spi_engine_offload/spi_engine_offload_ip.tcl
projects/ad57xx_ardz/Makefile
projects/ad57xx_ardz/Readme.md
projects/ad57xx_ardz/common/ad57xx_ardz_bd.tcl
projects/ad57xx_ardz/common/ad57xx_ardz_qsys.tcl
projects/ad57xx_ardz/coraz7s/Makefile
projects/ad57xx_ardz/coraz7s/system_bd.tcl
projects/ad57xx_ardz/coraz7s/system_constr.xdc
projects/ad57xx_ardz/coraz7s/system_project.tcl
projects/ad57xx_ardz/coraz7s/system_top.v
projects/ad57xx_ardz/de10nano/Makefile
projects/ad57xx_ardz/de10nano/system_constr.sdc
projects/ad57xx_ardz/de10nano/system_project.tcl
projects/ad57xx_ardz/de10nano/system_qsys.tcl
projects/ad57xx_ardz/de10nano/system_top.v

Please replace this comment with summary, motivation and context of the changes.
List any dependencies required for this change.
Add support for the EVAL-AD5780ARDZ family of eval boards, which can be used to evaluate the AD5760, AD5780, AD5781, AD5790 and AD5791 DACs.
There is a testbench on [this branch](https://github.com/analogdevicesinc/testbenches/tree/ad57xx) with the corresponding PR: https://github.com/analogdevicesinc/testbenches/pull/122

ad57xx_ardz: add support for de10nano, coraz7s

---

docs/projects/adrv9026/index.rst
projects/adrv9026/common/adrv9026_bd.tcl
projects/adrv9026/common/versal_transceiver.tcl
projects/adrv9026/vck190/Makefile
projects/adrv9026/vck190/system_bd.tcl
projects/adrv9026/vck190/system_constr.xdc
projects/adrv9026/vck190/system_project.tcl
projects/adrv9026/vck190/system_top.v

Versal support for adrv9026 with JESD204B

adrv9026: Add vck190 support

---

docs/library/axi_tdd/index.rst
docs/regmap/adi_regmap_tdd_gen.txt
library/axi_tdd/axi_tdd_channel.sv
library/axi_tdd/axi_tdd_counter.sv
library/axi_tdd/axi_tdd_pkg.sv

This patch contains the following updates:
* Remove channel reset at the end of frame
* Fix initial delay length when STARTUP_DELAY = 1
* Rename 'SYNC_COUNTER' registers to 'SYNC_PERIOD'
* Update description for: STARTUP_DELAY, FRAME_LENGTH, SYNC_PERIOD

axi_tdd: Update to version 2.0.b

---

.github/scripts/gen_backstage_yaml.py
.github/workflows/backstage_yaml.yml
.gitignore
docs/requirements.txt

Creates components for HDL libraries and projects.
It leverages the Doctools HDL parser to create the dependency hierarchy. Descriptions and tags are obtained from the documentation.
Part names in the :adi: role are converted into tags.
The CI only commits when there are changes, and always amends the commit.
After PR approval, I need to update the CI to target refs/heads/main to run on push to main.
Artifacts are deployed to https://github.com/analogdevicesinc/hdl/tree/backstage_yaml (commit amend)

ci: Add backstage catalog yaml generator

---

docs/library/axi_ad9144/block_diagram.svg
docs/library/axi_ad9144/detailed_architecture.svg
docs/library/axi_ad9144/index.rst
docs/library/axi_ad9371/block_diagram.svg
docs/library/axi_ad9371/index.rst
docs/library/index.rst
docs/projects/index.rst

Migrate documentation for AXI IPs which are not maintained anymore from wiki to GitHub pages. This PR contains:
* two new pages (axi_ad9144 & axi_ad9371)
* new sections, in library/index.rst called 'Obsolete IPs' and in projects/index.rst called 'Obsolete Projects'

[Doc] Migrate obsolete IPs: axi_ad9144 & axi_ad9371 

---

library/axi_ltc2387/axi_ltc2387.v

Fixed the default value for the parameters. This way it removes Critical Warnings from the project CN0577/Zed. 
It should actually be ADC_RES=18 and OUT_RES=32.
Tested in hardware with Linux, but not with what's latest on main. That is because there were some changes done in the past month, which affected the functionality of this project.
I tested with the HEAD being at analogdevicesinc/linux@55546255ca63ded5c86f0040801cafa15459a2a8 (the commit right before the changes) and it works as expected.

library/axi_ltc2387/axi_ltc2387.v: Fix default value for parameters

---

docs/projects/ad77681evb/ad77681evb_hdl.svg
docs/projects/ad77681evb/index.rst
docs/projects/index.rst
projects/ad77681evb/Readme.md
projects/ad77681evb/common/ad77681evb_bd.tcl
projects/ad77681evb/zed/Makefile
projects/ad77681evb/zed/system_constr.xdc
projects/ad77681evb/zed/system_top.v

Ad77681evb update

---

library/axi_dmac/data_mover.v
projects/ad9081_fmca_ebz_x_band/zcu102/system_bd.tcl

This commit changes the following:
- The RX TDD sync can be performed through both the DO and DMAC.
- The clock domain crossing is performed in the DMA instead of the DO.
- The RX DMA length width was increased to allow large buffer captures.
- The DMAC s_axi_ready signal is gated with has_sync.

Updates stingray next stable

---

docs/conf.py

Use Cloudfare CDN for improved uptime and speed.
Fixes wavedrom.com downtime taking down the doc or making it slow to load.
It is the recommended url at https://cdnjs.cloudflare.com/ajax/libs/wavedrom/3.1.0/wavedrom.min.js

docs: Change wavedrom script url

---

docs/projects/ad411x_ad717x/ad411x_ad717x_hdl.svg
docs/projects/ad411x_ad717x/index.rst
library/util_sigma_delta_spi/Makefile
library/util_sigma_delta_spi/util_sigma_delta_spi_hw.tcl
projects/ad411x_ad717x/common/ad411x_ad717x_asdz_qsys.tcl
projects/ad411x_ad717x/de10nano/Makefile
projects/ad411x_ad717x/de10nano/system_project.tcl
projects/ad411x_ad717x/de10nano/system_top.v

Connect DOUT/RDY signal to a GPIO pin.
Update the HDL project to include the util_sigma_delta_spi module.

ad411x_ad717x: DRDY Interrupt

---

docs/library/axi_clock_monitor/index.rst
docs/library/index.rst
library/axi_clock_monitor/axi_clock_monitor_ip.tcl

- Added the doc. for AXI Clock Monitor IP core
- Edited the GUI of the IP such that it displays the range of the valid values which can be assigned to NUM_OF_CLOCKS and the new link to the doc, in the company_url field
I also added the warning to its corresponding [wiki page](https://wiki.analog.com/resources/fpga/docs/axi_clock_monitor), that it was migrated.

docs/library: Add axi_clock_monitor IP doc & Update IP GUI

---

library/common/tb/run_tb.sh

Added command argument to support SV files for Unit Level Testbenches.

unit_level_tb: Added SV support

---

projects/ad9081_fmca_ebz/s10soc/system_top.v
projects/common/s10soc/s10soc_system_assign.tcl

Fixes some critical warnings that made the Jenkins build fail even though the project compiled successfully.
system_top:  Added the missing system_project.tcl parameters.
s10soc_system_assign: Some of the assignments were referencing invalid ports, but the project still compiled fine because Quartus auto-placed those signals.

[main]: Fix S10SoC critical warnings

---

projects/ad9081_fmca_ebz/common/versal_transceiver.tcl

The [rx/tx]_progdiv_clock was truncated if the lane rate was an integer. So for a lane rate of '10', the ref clock calculated was 151.000 instead of 151.515.

ad9081_fmca_ebz: common: versal_transceiver: Force progdiv_clk to float

---

library/scripts/adi_xilinx_device_info_enc.tcl

The FPGA_TECHNOLOGY was identified as Ultrascale for VCU118 and it should be Ultrascale+.

library/scripts: Fix FPGA_TECHNOLOGY for VCU118

---

docs/regmap/adi_regmap_spi_engine.txt
library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/spi_engine_execution/Makefile
library/spi_engine/spi_engine_execution/spi_engine_execution.v
library/spi_engine/spi_engine_execution/spi_engine_execution_hw.tcl
library/spi_engine/spi_engine_execution/spi_engine_execution_ip.tcl
library/spi_engine/spi_engine_execution/spi_engine_execution_shiftreg.v

A couple of improvements to the execution module for the SPI Engine. Mostly code reorganization, but this should improve timing closure for projects using the SPI Engine. 
The changes here should not affect the functionality of the SPI Engine.
- Reorganized the counters
- Moved lower level shift register logic to separate module
- Pipelined barrel shifter on sdo path

SPI Engine: execution improvements

---

docs/projects/ad719x_asdz/index.rst
projects/ad719x_asdz/README.md
projects/ad719x_asdz/de10nano/Makefile
projects/ad719x_asdz/de10nano/system_constr.sdc
projects/ad719x_asdz/de10nano/system_project.tcl
projects/ad719x_asdz/de10nano/system_qsys.tcl
projects/ad719x_asdz/de10nano/system_top.v

Add support for the AD719x on DE10-Nano, using the SPI Controller.

Add AD719x support on DE10-Nano

---

library/axi_dmac/tb/dma_read_shutdown_tb
library/axi_dmac/tb/dma_read_tb
library/axi_dmac/tb/dma_write_shutdown_tb
library/axi_dmac/tb/dma_write_tb

Updated 4 unit level testbenches for the AXI_DMAC IP that are looking for the new files introduced by the framelock PR. 
2 of the tests are still failing, waiting for [this PR](https://github.com/analogdevicesinc/hdl/pull/1455) to be merged for the fix.

library/axi_dmac/tb: Updated unit level testbenches after framelock

---

projects/ad411x_ad717x/de10nano/system_project.tcl
projects/ad4170_asdz/de10nano/system_project.tcl
projects/ad469x_evb/de10nano/system_project.tcl
projects/ad57xx_ardz/de10nano/system_project.tcl
projects/ad7124_asdz/de10nano/system_project.tcl
projects/ad719x_asdz/de10nano/system_project.tcl
projects/ad777x_ardz/de10nano/system_project.tcl
projects/adv7513/de10nano/system_project.tcl
projects/arradio/c5soc/system_project.tcl
projects/cn0540/de10nano/system_project.tcl
projects/cn0561/de10nano/system_project.tcl
projects/cn0579/de10nano/system_project.tcl
projects/common/c5soc/system_project.tcl
projects/common/de10nano/system_project.tcl
projects/dc2677a/c5soc/system_project.tcl
scripts/adi_env.tcl

Updated Quartus Std and Pro to latest versions (23.1std.1 and 24.2)

Change the default version of Quartus Standard to 23.1std.1 and Quartus Pro 24.2

---

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl

The old formula would result in '0' quads when L was less than 4 and would not properly connect the serial lanes to the PHY.
Replacing the round with ceil fixes that.

ad9081: common: ad9081_fmca_ebz_bd: Fix number of quads calculation

---

library/xilinx/common/ad_mmcm_drp.v

Adds mmcme5 instantiation for Versal boards inside ad_mmcm_drp. This allows us to use the axi_clkgen IP on Versal FPGAs as well.

library: xilinx: common: ad_mmcm_drp: Add Versal family support

---

library/common/tb/run_tb.sh

Added SystemVerilog support breaks some of the current unit level testbenches.
Removing support for SystemVerilog, until incompatibilities between Verilog and SystemVerilog are understood and fixed.

unit_level_tb: Revert SV support

---

library/axi_ad9361/xilinx/axi_ad9361_lvds_if.v

The rx_error_r* on the axi_ad9361/xilinx/axi_ad9361_lvds_if.v were not implemented properly.
the author intended it to be the inverse of all valid frames combinations {rx_frame, rx_frame_s} but only compared against rx_frame_s.
Checking against all valid frames is also unnecessary, since checking for unequal DDR output values have the same practical effect.
It is also worth noting that at 2RX mode, a frame fulfills the 2 channels in 4 clock cycles, while  {rx_frame, rx_frame_s} looks back only 2 clock cycles.
UG-570, p95
This commit changes rx_error to be a "link stable signal".
Relevant information:
AD9361:
operates in DDR
Linux/no-os drivers set (or leave default):
*  reg 0x010 value 0xC8, bit 2 -> Rx Frame Pulse Mode : 50% duty cycle
* reg 0x011 value 0x00, bit 2 -> Invert Rx Frame : …

axi_ad9361: Fixup LVDS RX_FRAME (#916)

---

library/axi_dmac/axi_dmac_hw.tcl

Update ENABLE_FRAMELOCK to FRAMELOCK.
Update reg_defaults to defaults.
Fixup for each.

axi_dmac: Fixup _hw.tcl variables names

---

projects/dac_fmc_ebz/common/config.tcl
projects/dac_fmc_ebz/zcu102/system_bd.tcl
projects/dac_fmc_ebz/zcu102/system_constr.xdc
projects/dac_fmc_ebz/zcu102/system_top.v

- enabling custom modes trough make parameters (M L S F HD N NP)
- changing the source DMA DATA WIDTH to 128
- changing the TX_LANE_INVERT from 0x0F to 0xF0
- updating the xcvr parameters for 12.5GHz lane rate
- cosmetics on the system_constr file

Fixes for AD9164 on ZCU102

---

projects/adrv904x/common/adrv904x_bd.tcl

The util_adxcvr parameters for this project were changed by this [commit](https://github.com/analogdevicesinc/hdl/commit/c0cf6ec65eadcd040162c08506627cc97a18068f)
This change broke the project, so I changed the parameters back to their original value.

projects/adrv904x: Fix util_adxcvr parameters

---

docs/projects/ad7124_asdz/index.rst
projects/ad7124_asdz/de10nano/system_qsys.tcl
projects/ad7124_asdz/de10nano/system_top.v

Required for RDY interrupt support. Updated SPI controller refclk

Fix ad7124

---

library/intel/adi_jesd204/adi_jesd204_hw.tcl

In quartus 24.2 the 'get_part_info -sip_tile' command also returns the number of tiles which made some of the ifs that were matching on the type of tile fail.

library: intel: adi_jesd204: adi_jesd204_hw: Fix sip_tile string

---

library/axi_dmac/axi_dmac_regmap_request.v

- The Lattice Radiant in the default configuration can not automatically infer the array size at concatenation.
- I'm specifying the array size at concatenation to fix the error shown by Lattice Radiant.

axi_dmac_regmap_request.v: Updating assignment for up_dma_x_length.

---

projects/adrv9009/common/adrv9009_bd.tcl
projects/adrv9009/zc706/Makefile
projects/adrv9009/zc706/system_bd.tcl
projects/adrv9009/zc706/system_top.v
projects/adrv9009/zcu102/Makefile
projects/adrv9009/zcu102/system_bd.tcl
projects/adrv9009/zcu102/system_top.v
projects/common/zc706/zc706_plddr3_data_offload_bd.tcl

These changes integrate the Data Offload in the adrv9009 AMD/Xilinx based projects, replacing the old dacfifo IP.
In addition, a common script is used to import the MIG configuration for the zc706 PL DDR3 use case.

Data Offload Integration: adrv9009 AMD/Xilinx Projects

---

library/axi_dmac/axi_dmac_response_manager.v

This commit fixes the critical warning: "mixed_port_feed_through_mode" parameter of RAM atom cannot have value "old" when different read and write clocks are used, by adding a reset on the read side.

axi_dmac: Fix Intel RAM critical warning

---

library/scripts/adi_ip_xilinx.tcl

Creates a list for design sources and constraints and then imports all the files at once in their respective category.
A critical warning appeared when importing large amount of files into an IP one by one, as the script was working up until this point. This now creates separate lists after checking the file type and imports all of the files at once. This way the critical warning doesn't appear and the build time is faster as well.

library/scripts/adi_ip_xilinx: adi_ip_files update

---

projects/ad411x_ad717x/de10nano/Makefile
projects/ad411x_ad717x/de10nano/system_project.tcl
projects/pulsar_adc/common/pulsar_adc_pmod.txt
projects/pulsar_adc/coraz7s/Makefile
projects/pulsar_adc/coraz7s/system_project.tcl
projects/pulsar_adc/zed/Makefile
projects/pulsar_adc/zed/system_project.tcl

Fixed the project name set in Tcl and Makefile for pulsar_adc and ad411x_ad717x to match the folder name + _carrier.
pulsar_adc_pmdz_coraz7s -> pulsar_adc_coraz7s
pulsar_adc_pmdz_zed -> pulsar_adc_zed
ad411x_de10nano -> ad411x_ad717x_de10nano

projects: Fix project name for pulsar_adc and ad411x_ad717x

---

docs/projects/ad9081_fmca_ebz/index.rst

- fixes a make parameter typo that was given as an example
- adds the JESD204C lane rate formula alongside the JESD204B formula
- removes the Quartus Pro 24.1 warning requirement for Agilex

docs: projects: ad9081: Small fixes

---

docs/library/i3c_controller/i3c_controller_core.rst
docs/library/i3c_controller/interface.rst
docs/regmap/adi_regmap_i3c_controller.txt
library/i3c_controller/i3c_controller_core/i3c_controller_bit_mod.v
library/i3c_controller/i3c_controller_core/i3c_controller_core.v
library/i3c_controller/i3c_controller_core/i3c_controller_core_hw.tcl
library/i3c_controller/i3c_controller_core/i3c_controller_core_ip.tcl
library/i3c_controller/i3c_controller_core/i3c_controller_word.v
library/i3c_controller/scripts/i3c_controller_bd.tcl
library/i3c_controller/scripts/i3c_controller_qsys.tcl

Some rework to better support slow I2C devices (100kHz, 400kHz).
I2C speed can be lower than I3C open drain speed.
The new I2C_MOD allows to configure this speed.

i3c_controller: Bug fixes for I2C devices and lower sclk speed

---

docs/user_guide/build_hdl.rst

Removed sourcing recommendation of the settings64.sh, as this is for Windows command line.
Windows path contains `\`, while the Cygwin is expecting `/`.

docs: Build HDL for Windows update

---

docs/regmap/adi_regmap_spi_engine.txt
library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/spi_engine_execution/spi_engine_execution.v
library/spi_engine/spi_engine_execution/spi_engine_execution_shiftreg.v
library/spi_engine/spi_engine_offload/spi_engine_offload.v
projects/ad4052_ardz/coraz7s/system_project.tcl
projects/ad4052_ardz/de10nano/system_project.tcl

Allows spi_engine_execution get sdo data independently of the instruction command. This reduces the trigger to transfer latency, and opens the door to further pipelining this path or reducing latency even more. 
(this PR should be merged after https://github.com/analogdevicesinc/hdl/pull/1499)

SPI Engine: SDO data prefetch

---

.gitignore

Python virtual environment is used when building the documentation, in some setups. When activating it, it creates a couple of folders and a cfg file, which should be ignored by git.
- bin/
- lib/
- lib64
- pyvenv.cfg
- share/

.gitignore: Ignore folders generated by pyvenv

---

.gitignore
docs/user_guide/build_hdl.rst
projects/common/lfcpnx/lfcpnx_system_constr.pdc
projects/common/lfcpnx/lfcpnx_system_pb.tcl
projects/scripts/adi_project_lattice.tcl
projects/scripts/adi_project_lattice_pb.tcl
projects/scripts/project-lattice.mk
scripts/adi_env.tcl

- Fixes for project creation.
- Updating `.gitignore`.
- Updating `project-lattice.mk` script.
- Updates for tools version `2024.2`.
- Updating documentation for tools version `2024.2`.

Lattice tools update 2024.2

---

docs/library/axi_ad7405/axi_ad7405.svg
docs/library/axi_ad7405/index.rst
docs/library/index.rst
docs/projects/ad7405_fmc/ad7405_zed_cmos_diagram.svg
docs/projects/ad7405_fmc/ad7405_zed_lvds_diagram.svg
docs/projects/ad7405_fmc/index.rst
library/axi_ad7405/Makefile
library/axi_ad7405/axi_ad7405.v
library/axi_ad7405/axi_ad7405_constr.ttcl
library/axi_ad7405/axi_ad7405_ip.tcl
library/common/util_dec256sinc24b.v
library/util_dec256sinc24b/util_dec256sinc24b_ip.tcl
projects/ad7405_fmc/Makefile
projects/ad7405_fmc/common/ad7405_bd.tcl
projects/ad7405_fmc/zed/Makefile
projects/ad7405_fmc/zed/system_bd.tcl
projects/ad7405_fmc/zed/system_constr_cmos.xdc
projects/ad7405_fmc/zed/system_constr_lvds.xdc
projects/ad7405_fmc/zed/system_project.tcl
projects/ad7405_fmc/zed/system_top_cmos.v
projects/ad7405_fmc/zed/system_top_lvds.v

Add AXI ADC support to existing AD7405 project.
Update AD7405 project to account for the changes.

AD7405: Add AXI ADC support

---

docs/library/axi_adrv9001/axi_adrv9001.svg
docs/library/axi_adrv9001/index.rst
docs/library/axi_adrv9001/rxcomponentmodephy.svg
docs/library/axi_adrv9001/txcomponentmodephy.svg
docs/library/index.rst

Adds documentation for the axi ADRV9001 library
Please replace this comment with summary, motivation and context of the changes.
List any dependencies required for this change.
You can check the checkboxes below by inserting a 'x' between square brackets
(without any other characters or spaces) or just check them after publishing the PR.
If there is a breaking change, specify dependent PRs in description and
try to push all related PRs at the same time.

docs: add docs/library/axi_adrv9001

---

library/intel/adi_jesd204/adi_jesd204_hw.tcl
projects/ad4052_ardz/de10nano/system_project.tcl
projects/daq2/a10soc/system_project.tcl

- When Intel changed the way the sip_tile information is returned, I used a regex to extract the value and then converted it to uppercase, on a10soc, the quartus::device::get_part_info -sip_tile returns an empty string and the sip_tile variable is not initialized resulting in a build error.
- bumps the required version for ad4052_ardz to 23.1std so that it doesn't fail on  CI.
- increases the placement effort for daq2/a10soc to pass the timing on CI

[bug] Fix intel projects that are failing on CI

---

docs/library/cn0363/cn0363_dma_sequencer.rst
docs/library/cn0363/cn0363_phase_data_sync.rst
docs/library/cn0363/index.rst
docs/library/index.rst
docs/projects/cn0363/index.rst

Adds documentation for the CN0363 specific IPs:
- CN0363 DMA Sequencer;
- CN0363 Phase Data Sync.

docs: add docs/library/cn0363/* specific IPs

---

.github/scripts/gen_backstage_yaml.py

Based on this ci run: https://github.com/analogdevicesinc/hdl/actions/runs/12636173279/job/35207649065
It is required that all libraries and projects contain an overview/short-description at the beginning of the file.
Exit with a message error when it is missing and fix the IndexError.

scripts: backstage: Warn on missing description

---

library/axi_ad9963/axi_ad9963_tx_channel.v

This commit fixes the DDS config for the second tone.
Fix a copy/paste typo.
By default the DDS cores are disabled for m2k, which is the only design actively using the axi_ad9963 core. This is probably why this issue was not detected for such a long time.

axi_ad9963: Fix typo

---

library/scripts/adi_ip_xilinx.tcl

Automatic parameters from adi_xilinx_device_info_enc are injected in
adi_ip_xilinx to codegen the bd/bd.tcl files.
First, it adds the items that are lib user parameters to an array,
suffixed with backslash, then replaces the last item backslash from
info_enc with the closing double quote.
If FPGA_TECHNOLOGY is not in the IP, no double quote is inserted,
and the string is never closed on bd.tcl.
Assign the matched user parameter to an auxiliary variable and
use that on the replace instead.
`j` variable existence is ensured by the ` if { $auto_set_param ne "" }` and `if { $auto_set_overwritable_param ne "" }`, so it lacks a initial define (e.g. `""`)

scripts: adi_ip_xilinx: Fix fall through, missing close quote

---

library/axi_ad9122/axi_ad9122_channel.v

Fix copy/paste typo that affects the second tone of each channel.

axi_ad9122: Fix DDS second tone control typo

---

library/common/ad_mem.v
library/data_offload/data_offload.v
library/util_axis_fifo/util_axis_fifo.v
library/util_axis_fifo_asym/util_axis_fifo_asym.v
library/util_axis_fifo_asym/util_axis_fifo_asym_ip.tcl

Added initialization for ad_mem, which helps the testbench by automatically clearing all the FIFOs at the beginning of the simulation. 
Fixed a bug that was related to different data width on the input and output of the FIFO, when it was using asymmetric clocks. 
Added parameter to be able to set the FIFO size from the perspective of Master or Slave.
Added parameter to toggle to result in a reduced size FIFO. 
Update the affected Data Offload IP. 
Tested all of the changes in the Testbenches repository, where these IPs were used, the tests pass. 
analogdevicesinc/testbenches#77
analogdevicesinc/testbenches#161
Updated information on the FIFO here:
[Wiki](https://wiki.analog.com/resources/fpga/docs/util_axis_fifo_asym)

Util axis fifo asym

---

docs/user_guide/architecture.rst

Although 1.8V is supported on one of the FMCs, it requires a bunch of hardware changes on the FPGA and also not all the IOs have level translators so it's actually possible to burn some of them.

docs: user_guide: architecture: Remove 1.8V support from FM87

---

docs/regmap/adi_regmap_spi_engine.txt
library/spi_engine/axi_spi_engine/axi_spi_engine.v
library/spi_engine/spi_engine_execution/spi_engine_execution.v
library/spi_engine/spi_engine_execution/spi_engine_execution_shiftreg.v

This PR fixes echo_sclk transfers, which were broken for some cases. Notably, split transfers were problematic, affecting projects like the ad4630. Also fixes another issue where the first transfer would return 0.
tb: https://github.com/analogdevicesinc/testbenches/pull/190

SPI Engine: fix transfers with echo_sclk

---

projects/ad_quadmxfe1_ebz/common/ad_quadmxfe1_ebz_bd.tcl
projects/ad_quadmxfe1_ebz/vcu118/Makefile
projects/ad_quadmxfe1_ebz/vcu118/system_bd.tcl
projects/ad_quadmxfe1_ebz/vcu118/system_top.v

This commit adds support for the Data Offload IP, replacing the dacfifo/adcfifo IPs.
Must be merged after this PR: https://github.com/analogdevicesinc/hdl/pull/1573
Should include this PR as well: https://github.com/analogdevicesinc/hdl/pull/1576

ad_quadmxfe1_ebz: Switch to data_offload

---

docs/library/util_axis_fifo_asym/index.rst

Fixes ADDRESS_WIDTH parameter naming in configuration parameters.

docs/library/util_axis_fifo_asym: Fix address width naming

---

library/scripts/library.mk

Starting from when thread building was added, the libraries are only building once After the target file is created it does not go further with checking dates.
This change forces the make through a phony target to properly evaluate.

library.mk: Fix second run for dependent lib

---

library/axi_ad408x/axi_ad408x.v
library/axi_ad485x/axi_ad485x.v
library/axi_ad9265/axi_ad9265.v
library/axi_ad9361/axi_ad9361_rx.v
library/axi_ad9361/axi_ad9361_tx.v
library/axi_ad9434/axi_ad9434_core.v
library/axi_ad9467/axi_ad9467.v
library/axi_ad9684/axi_ad9684.v
library/axi_ad9963/axi_ad9963_rx.v
library/axi_adaq8092/axi_adaq8092.v
library/axi_adrv9001/axi_adrv9001_core.v
library/axi_ltc2387/axi_ltc2387.v
library/axi_pulsar_lvds/axi_pulsar_lvds.v
library/common/up_delay_cntrl.v

Add a parameter for CUSTOM_RST in up_delay_cntrl. By default, the IP will behave the same. When set to 1, the rst_async will be connected to core_rst. This will fix the ad9361 initialization/calibration issues.
Update all the libraries that use the up_delay_cntrl instance, for backwards compatibility, as a new port has been added.
Tested on hardware, using fmcomms5 on zc702 & No-OS.

up_delay_cntrl: Add core_rst

---

docs/projects/ad9656_fmc/index.rst
projects/ad9656_fmc/common/ad9656_fmc_bd.tcl

Regenerated the transceiver parameters for AD9656 on ZCU102, thus checking the old ones and adding others which were not present. This was done in order to fix a PN mismatch error, but it didn't solve the issue. The real cause of the problem was from the No-Os driver, which is also fixed and can be found here: https://github.com/analogdevicesinc/no-OS/pull/2508 (merged). Also added to the documentation one extra line specifying the line rate.

projects/ad9656_fmc: New trans. params

---

library/axi_ad485x/axi_ad485x.v
library/axi_adrv9001/axi_adrv9001_core.v

When [this PR](https://github.com/analogdevicesinc/hdl/pull/1616) has been merged, there were two up_delay_cntrl instances that were left out in the update process.
Adding the missing core_rst port to the axi_adrv9001_core & axi_ad485x.

library: Add missing core_rst for up_delay_cntrl

---

docs/projects/ad9434_fmc/index.rst
docs/projects/ad9467_fmc/index.rst
projects/ad9434_fmc/README.md
projects/ad9434_fmc/Readme.md
projects/ad9434_fmc/zc706/README.md
projects/ad9434_fmc/zed/README.md
projects/ad9467_fmc/README.md
projects/ad9467_fmc/Readme.md
projects/ad9467_fmc/kc705/README.md
projects/ad9467_fmc/zed/README.md

Update & add README files for ad9434_fmc & ad9467_fmc.
Fix the dts links in the ad9434_fmc & ad9467_fmc documentation.

projects: Add README for ad9434_fmc & ad9467_fmc

---

projects/ad4110/README.md
projects/ad4110/zed/README.md

ad4110: Update README

---

Makefile

Single/no carrier projects are not added to the SUBPROJECTS makefile.
Look for system_project.tcl at project, if it exists, it means it is a standalone project and the subproject wildcard is not needed.
SUBPROJECTS now include:
```diff
169a170,171
> jupiter_sdr
> m2k
170a173
> pluto
173a177,178
> sidekiqz2
> usrpe31x
```
Fixes https://github.com/analogdevicesinc/m2k-fw/blob/master/Makefile#L119 (broken by cb5cf61, requires m2k.standalone -> m2k) rename.

makefile: Restore/fix make standalone projects

---

docs/library/axi_ltc235x/index.rst

Due to the library being an intel part, the standard HDL- command to automate some tables do not work due to lack of component.xml. This patch manually adds the configuration parameter and interface table.

docs: axi_ltc235x: edit_tables

---

docs/projects/ad77681evb/index.rst
projects/ad77681evb/README.md
projects/ad77681evb/Readme.md
projects/ad77681evb/zed/README.md

Added the README.md for ad77681evb project.

projects/ad77681evb: Add README.md files

---

docs/projects/adrv9001/index.rst
projects/adrv9001/README.md
projects/adrv9001/Readme.md
projects/adrv9001/a10soc/README.md
projects/adrv9001/zc706/README.md
projects/adrv9001/zcu102/README.md
projects/adrv9001/zed/README.md

Added the README.md for **ADRV9001** project and modify dts links from documentation.

ADRV9001 READMEs & doc

---

docs/library/axi_pwm_gen/index.rst
docs/regmap/adi_regmap_pwm_gen.txt

- Updates on the regmap txt, because EXT_SYNC_ALIGN should actually be EXT_SYNC_PHASE_ALIGN, as well as the default values were wrongly set
- Cleanup in the rst documentation

docs: Update axi_pwm_gen regmap doc.

---

docs/projects/jupiter_sdr/index.rst
projects/jupiter_sdr/README.md
projects/jupiter_sdr/Readme.md

Added README files for **jupiter_sdr** and fixes documentation.

projects: Add jupiter_sdr README & documentation fixes

---

docs/library/axi_ada4355/index.rst
docs/regmap/adi_regmap_axi_ada4355.txt
library/axi_ada4355/Makefile
library/axi_ada4355/axi_ada4355.v
library/axi_ada4355/axi_ada4355_constr.ttcl
library/axi_ada4355/axi_ada4355_if.v
library/axi_ada4355/axi_ada4355_ip.tcl
library/axi_ada4355/axi_ada4355_regmap.v

Detect when it is encountering a frame or data error.

ada4355: Add idelay calibration functionality

---

docs/projects/ad411x_ad717x/index.rst
projects/ad411x_ad717x/README.md
projects/ad411x_ad717x/de10nano/README.md

Added the README.md and modified the links in the overview section for the **ad411x_ad717x** project.

projects/ad411x_ad717x: Add README.md files

---

projects/adrv904x/README.md
projects/adrv904x/zcu102/README.md
projects/adrv904x/zcu102/system_project.tcl

Added the README files for adrv904x project.

projects/adrv904x: Add README files

---

library/common/ad_mem.v

Updated Block RAM initialization which bypasses the default loop limit imposed by the Quartus IDE.

library/common/ad_mem: Updated RAM initialization mode for Quartus IDE

---

docs/projects/daq2/daq2_evb_block_diagram.svg
docs/projects/daq2/daq2_xilinx_block_diagram.svg
docs/projects/daq2/index.rst
docs/projects/index.rst

Added documentation for the project DAQ2

docs: add project daq2

---

docs/projects/ad4170_asdz/index.rst
docs/projects/ad7616_sdz/index.rst
docs/projects/cn0540/index.rst
docs/user_guide/releases.rst

Fixed warnings that were found at doc build and updated the Vivado version in the Releases page.

docs/projects: Fix warnings at build & update Vivado version in Releases page

---

docs/projects/adrv9009/index.rst
projects/adrv9009/common/adrv9009_bd.tcl
projects/adrv9009/kcu105/Makefile
projects/adrv9009/kcu105/system_bd.tcl
projects/adrv9009/kcu105/system_constr.xdc
projects/adrv9009/kcu105/system_project.tcl
projects/adrv9009/kcu105/system_top.v

adrv9009: Add kcu105 support

---

library/axi_clock_monitor/Makefile
library/axi_clock_monitor/axi_clock_monitor_ltt.tcl
library/axi_dmac/Makefile
library/axi_dmac/axi_dmac_ltt.tcl
library/axi_pulse_gen/Makefile
library/axi_pulse_gen/axi_pulse_gen_ltt.tcl
library/axi_pwm_gen/Makefile
library/axi_pwm_gen/axi_pwm_gen_ltt.tcl
library/interfaces_ltt/Makefile
library/interfaces_ltt/interfaces_ltt.tcl
library/spi_engine/axi_spi_engine/Makefile
library/spi_engine/axi_spi_engine/axi_spi_engine_ltt.tcl
library/spi_engine/spi_axis_reorder/Makefile
library/spi_engine/spi_axis_reorder/spi_axis_reorder_ltt.tcl
library/spi_engine/spi_engine_execution/Makefile
library/spi_engine/spi_engine_execution/spi_engine_execution_ltt.tcl
library/spi_engine/spi_engine_interconnect/Makefile
library/spi_engine/spi_engine_interconnect/spi_engine_interconnect_ltt.tcl
library/spi_engine/spi_engine_offload/Makefile
library/spi_engine/spi_engine_offload/spi_engine_offload_ltt.tcl

Adding: 
* IP scripts:
- spi_engine:
* axi_spi_engine_ltt.tcl
* spi_axis_reorder_ltt.tcl
* spi_engine_execution_ltt.tcl
* spi_engine_interconnect_ltt.tcl
* spi_engine_offload_ltt.tcl
- axi_dmac_ltt.tcl
- axi_clock_monitor_ltt.tcl
- axi_pwm_gen_ltt.tcl
- axi_pulse_gen_ltt.tcl
* Interface script interfaces_ltt/interfaces_ltt.tcl that contains the following interfaces:
- spi_master interface
- spi_engine_offload_ctrl interface
- spi_engine_ctrl interface
- fifo_rd interface for axi_dmac
- fifo_wr interface for axi_dmac
- if_framelock interface for axi_dmac
Adding/Updating related make files.

Adding initial Lattice support for spi_engine, axi_dmac, axi_pwm_gen, axi_pulse_gen and axi_clock_monitor IPs.

---

docs/library/util_axis_fifo_asym/index.rst
library/util_axis_fifo_asym/util_axis_fifo_asym.v
library/util_axis_fifo_asym/util_axis_fifo_asym_ip.tcl

Current Asymmetric FIFO parameters make it difficult to understand and properly parameterize the core.
Simplified the core parameters, while maintaining all functionality that was present up until this point.
Updated the documentation as well as the testbench, which can be found [here](https://github.com/analogdevicesinc/testbenches/pull/230).

library/util_axis_fifo_asym: Updated IP parameterization and documentation

---

projects/ad9656_fmc/README.md
projects/ad9656_fmc/zcu102/README.md

Add VADJ range and value for ad9656_fmc.

ad9656_fmc: Add VADJ value

---

projects/adv7511/README.md
projects/adv7511/zc702/README.md
projects/adv7511/zc706/README.md
projects/adv7511/zed/README.md

Added VADJ info for adV7511 project.

Update READMEs with VADJ info for adv7511

---

docs/library/i3c_controller/i3c_controller_core.rst
docs/regmap/adi_regmap_i3c_controller.txt
library/i3c_controller/i3c_controller_core/i3c_controller_bit_mod.v
library/i3c_controller/i3c_controller_core/i3c_controller_core.v
library/i3c_controller/i3c_controller_core/i3c_controller_core_hw.tcl
library/i3c_controller/i3c_controller_core/i3c_controller_core_ip.tcl
library/i3c_controller/i3c_controller_core/i3c_controller_framing.v
library/i3c_controller/i3c_controller_host_interface/i3c_controller_host_interface.v
library/i3c_controller/i3c_controller_host_interface/i3c_controller_host_interface_hw.tcl
library/i3c_controller/i3c_controller_host_interface/i3c_controller_host_interface_ip.tcl
library/i3c_controller/i3c_controller_host_interface/i3c_controller_regmap.v
library/i3c_controller/i3c_controller_host_interface/i3c_controller_regmap.vh
library/i3c_controller/scripts/i3c_controller_bd.tcl
library/i3c_controller/scripts/i3c_controller_qsys.tcl

Running the core at 50MHz, even though works, provide worst performance and improper stall times.
The target carrier, DE10Nano, can be configured to provide a clk near 100MHz without using a PLL.
Therefore, remove this option and require 100MHz input clock. Also, simplify logic to hold SDA lane always to ground during the bit, avoiding conditions where SDA rises before SCL, not yielding a proper stop bit.
Add address width parameters, because these values affect considerably the resource utilization, therefore, make them user-configurable.
non-sticky interrupt pending
Set interrupt pending on source signal rising edge, to allow clearing
it and then resolving, e.g.:
```c
static irqreturn_t adi_i3c_controller_irq(int irq, void *data)
{
struct adi_i3c_controller *controller = data;
u32 …
```

i3c_controller: Remove CLK_MOD, set SDA low at Stop, add address width parameters

---

library/xilinx/axi_selmap/Makefile
library/xilinx/axi_selmap/async_cdc_fifo.v
library/xilinx/axi_selmap/axi_selmap.v
library/xilinx/axi_selmap/axi_selmap_ip.tcl
library/xilinx/axi_selmap/axi_selmap_regmap.v
projects/scripts/adi_project_xilinx.tcl

This PR adds the selectmap IP for Xilinx boards and an environment variable that allows the .bin file to be generated during the build.

library: xilinx: Add selmap IP

---

projects/ad_quadmxfe1_ebz/common/ad_quadmxfe1_ebz_bd.tcl
projects/ad_quadmxfe1_ebz/vcu118/system_bd.tcl

This PR updates the Data Offload instances in ad_quadmxfe1_ebz to use variable sizes, derived from the [RX/TX]_KS_PER_CHANNEL values.

ad_quadmxfe1_ebz: Use variable Data Offload size

---

CONTRIBUTING.md
docs/user_guide/contributing.rst
docs/user_guide/ip_cores/creating_new_ip.rst

For historical reasons, we have been creating linux dt-bindings suffixed
with 1.00.a, because that was the default vivado set value, and what
would be outputted by
[SDTGen](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/3156475927/Overview+of+System+Device+Tree+Generator+SDTGen).
Nowadays, vivado default is 1.0 and the auto-generated devicetrees never
really matched with the actual devicetree bindings.
To improve overall coherence between hdl and linux, I propose the
following:
* semantic versioning across the board,
* dt-bindings are suffixed by `-v<major>`, and should match the filename
and compatible
* Bus connected Ips should have the IP-XACT version set to
`<major>.<minor>.<patch>` (I developed a method to autoset based on
CORE_VERSION)
* Drivers should print the version reg …

docs: creating new ip: set guidelines for core version

---

projects/ad5766_sdz/README.md
projects/ad5766_sdz/zed/README.md

Update README files to include VADJ value & flags.

ad5766_sdz: Update VADJ info

---

library/i3c_controller/i3c_controller_host_interface/i3c_controller_host_interface_ip.tcl
projects/ad4062_ardz/coraz7s/system_constr.xdc

The first was an oversight on the rename to match the common project, due to the overlay effort.
The second is due to vivado not inferring the clock that the reset is synchronous to, in this case, set it explicitly associate for the synchronous case.

project/ad4062: Resolve critical warnings

---

library/axi_hsci/Makefile
library/axi_hsci/axi4_lite.sv
library/axi_hsci/axi_hsci.sv
library/axi_hsci/axi_hsci_constr.ttcl
library/axi_hsci/axi_hsci_ip.tcl
library/axi_hsci/hsci_master_axi_slave.sv
library/axi_hsci/hsci_master_logic.sv
library/axi_hsci/hsci_master_regs_defs.vh
library/axi_hsci/hsci_master_regs_regs.sv
library/axi_hsci/hsci_master_top.sv
library/axi_hsci/hsci_mcore.v
library/axi_hsci/hsci_mdec.sv
library/axi_hsci/hsci_menc.sv
library/axi_hsci/hsci_mfrm_det.v
library/axi_hsci/hsci_mlink_ctrl.sv
library/axi_hsci/lfsr15_8.v
library/axi_hsci/pulse_sync.v

This PR introduces support for the axi_hsci IP core, which is required in AD9084 based designs.
The HSCI interface is used both as a control interface and to load firmware into the AD9084 device.

library/axi_hsci: Add HSCI IP core

---

projects/ad9081_fmca_ebz/README.md
projects/ad9081_fmca_ebz/a10soc/README.md
projects/ad9081_fmca_ebz/fm87/README.md
projects/ad9081_fmca_ebz/s10soc/README.md
projects/ad9081_fmca_ebz/vck190/README.md
projects/ad9081_fmca_ebz/vcu118/README.md
projects/ad9081_fmca_ebz/vpk180/README.md
projects/ad9081_fmca_ebz/zc706/README.md
projects/ad9081_fmca_ebz/zcu102/README.md
projects/ad9081_fmca_ebz_x_band/README.md
projects/ad9081_fmca_ebz_x_band/zcu102/README.md
projects/ad9082_fmca_ebz/README.md
projects/ad9082_fmca_ebz/vck190/README.md
projects/ad9082_fmca_ebz/vcu118/README.md
projects/ad9082_fmca_ebz/vpk180/README.md
projects/ad9082_fmca_ebz/zc706/README.md
projects/ad9082_fmca_ebz/zcu102/README.md
projects/ad9209_fmca_ebz/README.md
projects/ad9209_fmca_ebz/vck190/README.md

Added the VADJ values and ranges for the AD9081/AD9081-FMCA-EBZ-X-BAND/AD9082/AD9209 projects.

projects/ad9081/x_band/ad9082/ad9209: Update READMEs with VADJ value

---

projects/ad9208_dual_ebz/README.md
projects/ad9208_dual_ebz/vcu118/README.md

Added the VADJ value in READMEs for AD9208-DUAL-EBZ.

projects/ad9208_dual_ebz: Update READMEs with VADJ value

---

docs/projects/adrv9026/adrv9026_jesd204c_block_diagram.svg
docs/projects/adrv9026/adrv9026_nls_block_diagram.svg
docs/projects/adrv9026/index.rst
projects/adrv9026/common/adrv9026_bd.tcl
projects/adrv9026/vcu118/README.md
projects/adrv9026/vcu118/system_bd.tcl
projects/adrv9026/vcu118/system_project.tcl
projects/adrv9026/zcu102/README.md
projects/adrv9026/zcu102/system_bd.tcl
projects/adrv9026/zcu102/system_project.tcl

Add JESD204C support for adrv9026 project
Validated and documented the following configuration in hardware for zcu102 and vcu118:
```
make JESD_MODE=64B66B ORX_ENABLE=1 TX_LANE_RATE=16.22 RX_LANE_RATE=16.22 \
RX_OS_JESD_M=4 RX_OS_JESD_L=2 RX_OS_JESD_S=1 RX_OS_JESD_NP=16 RX_JESD_L=2 
```
Didn't change the default configuration (JESD204B with ORX disabled)

adrv9026: Add JESD204C support

---

projects/ad9081_fmca_ebz/a10soc/system_project.tcl
projects/ad9081_fmca_ebz/fm87/system_project.tcl
projects/ad9081_fmca_ebz/s10soc/system_project.tcl
projects/daq2/a10soc/system_project.tcl

Should fix the failed builds on Jenkins.
There are no warnings when opening the I/O pin assignments report in Quartus so it's probably a bug in the latest release.

projects: ad9081: intel: Suppress incomplete I/O assignments

---

projects/cn0506/zcu102/system_bd.tcl
projects/cn0506/zcu102/system_top_mii.v

cn0506: zcu102: Update to the latest ZynqMP's GMII Enets' design
The latest variant of ZynqMP IP (in 2025 version of Vivado suite) exposes the speed_mode ports as individual ones, different from the previous integration into GMII interface.

cn0506: zcu102: Update to the latest ZynqMP's GMII Enets' design

---

docs/regmap/adi_regmap_jesd_rx.txt
docs/regmap/adi_regmap_jesd_tx.txt

OCTETS_PER_FRAME had already been updated to 8b, but this didn't match the regmap .txt

docs/regmap/adi_regmap_jesd_*.txt: update OCTETS_PER_FRAME bit width
