projects/daq2/zcu102/system_constr.xdc
Signed-off-by: Michael Hennerich <michael.hennerich@analog.com>
=> daq2/zcu102: Pin Swap for ZCU102 Rev1.0

projects/adrv9361z7035/ccbob_cmos/Makefile, projects/adrv9361z7035/ccbob_lvds/Makefile, projects/adrv9361z7035/ccbox_lvds/Makefile, projects/adrv9361z7035/ccfmc_lvds/Makefile, projects/adrv9361z7035/ccpci_lvds/Makefile, projects/adrv9361z7035/ccusb_lvds/Makefile, projects/adrv9361z7035/common/adrv9361z7035_bd.tcl, projects/adrv9364z7020/ccbob_cmos/Makefile, projects/adrv9364z7020/ccbob_lvds/Makefile, projects/adrv9364z7020/ccbox_lvds/Makefile, projects/adrv9364z7020/ccusb_lvds/Makefile, projects/adrv9364z7020/common/adrv9364z7020_bd.tcl
=> Update ADRV936x projects to use upack2

projects/Makefile, projects/sidekiqz2/Makefile, projects/sidekiqz2/system_bd.tcl, projects/sidekiqz2/system_constr.xdc, projects/sidekiqz2/system_project.tcl, projects/sidekiqz2/system_top.v
This is the initial commit for adding support for Sidekiq Z2 platform. The project has similar capabilities with our pluto design.
Commits from 19 feb add support for Linux:
https://github.com/analogdevicesinc/linux/commits/master
=> sidekiqz2: Initial commit

README.md
This wants to be a simple effort to improve the current README.MD file. Any feedback is welcome.
=> A generic README update

library/axi_dmac/address_generator.v, library/axi_dmac/axi_dmac.v, library/axi_dmac/axi_dmac_hw.tcl, library/axi_dmac/dest_axi_mm.v, library/axi_dmac/dest_axi_stream.v, library/axi_dmac/dest_fifo_inf.v, library/axi_dmac/request_arb.v, library/axi_dmac/src_axi_mm.v
Some trivial cleanups for the DMAC.
=> dmac: Trivial cleanups

library/axi_dmac/2d_transfer.v, library/axi_dmac/address_generator.v, library/axi_dmac/axi_dmac.v, library/axi_dmac/axi_dmac_constr.ttcl, library/axi_dmac/axi_dmac_hw.tcl, library/axi_dmac/axi_dmac_ip.tcl, library/axi_dmac/dest_axi_stream.v, library/axi_dmac/request_arb.v, library/axi_dmac/request_generator.v
This pull request contains a handful of smaller cleanup changes for the DMA. This is in preparation for the larger rework. These changes do not affect functionality.
=> A few DMA cleanups

library/jesd204/jesd204_rx/jesd204_rx_lane.v
Small update to the error statistics
* Reset the counter when the core is in reset
* Reduce number of adders to reduce utilization
=> JESD204 RX error statistics update

library/axi_clkgen/axi_clkgen_ip.tcl, library/axi_i2s_adi/axi_i2s_adi_ip.tcl, library/axi_spdif_rx/axi_spdif_rx_ip.tcl, library/axi_spdif_tx/axi_spdif_tx_ip.tcl, library/scripts/adi_ip.tcl
A few minor improvements for the adi_ip.tcl script.
=> adi_ip.tcl improvments

library/common/ad_tdd_control.v
This improvements will make the design more robust from timing standpoint.
=> TDD improvements

projects/daq3/zcu102/system_constr.xdc, projects/fmcomms2/zcu102/system_constr.xdc, projects/fmcomms5/zcu102/system_constr.xdc
DIFF_TERM is not supported in UltraScale devices.
=> Fix zc102 constr warnings

library/common/ad_rst.v, library/xilinx/common/ad_rst_constr.xdc
- Add "ASYNC_REG TRUE" property to all synchronization registers.
- Delete redundant synthesis attribute from verilog code.
=> Couple of minor improvements on the ad_rst module

library/axi_hdmi_tx/axi_hdmi_tx.v, library/axi_hdmi_tx/axi_hdmi_tx_core.v, library/axi_hdmi_tx/axi_hdmi_tx_hw.tcl, library/axi_hdmi_tx/axi_hdmi_tx_ip.tcl, library/axi_hdmi_tx/axi_hdmi_tx_vdma.v, projects/adrv9361z7035/common/ccfmc_bd.tcl, projects/adv7511/zc702/Makefile, projects/adv7511/zc706/Makefile, projects/adv7511/zed/Makefile, projects/common/zc702/zc702_system_bd.tcl, projects/common/zc706/zc706_system_bd.tcl, projects/common/zed/zed_system_bd.tcl
In progress:
- The 1600x900 resolution is not working at this moment due to a bad sync between the DMA and HDMI
- Adding the ADI DMA to all ADV7511 based carrier
=> Dev adi vdma

projects/daq2/common/daq2_bd.tcl
Project build tested on daq2/zc706.
=> common/daq2: Fix typo

projects/fmcomms2/kc705/system_top.v, projects/fmcomms2/kcu105/system_top.v, projects/fmcomms2/vc707/system_top.v, projects/fmcomms2/zcu102/system_top.v
Cleanup of system_top for fmcomms2 project to avoid warnings
=> fmcomms2: cleanup system_top for kc705,kcu105, vc707 and zcu102

projects/daq2/kcu105/system_project.tcl
Use Performance_Retiming strategy to meet timing.
=> daq2_kcu105: Change implementation strategy

library/axi_ad6676/axi_ad6676.v
=> axi_ad6676 expose lane number parameter

library/jesd204/axi_jesd204_common/jesd204_up_common.v, library/jesd204/tb/axi_jesd204_rx_regmap_tb.v, library/jesd204/tb/axi_jesd204_tx_regmap_tb.v, library/jesd204/tb/loopback_tb.v, library/jesd204/tb/run_tb.sh, library/jesd204/tb/soft_pcs_8b10b_table_tb.v, library/jesd204/tb/tb_base.v
Adding support for ModelSim and Vivado Xsim.
Usage:
export SIMULATOR=modelsim
or
export SIMULATOR=xsim
=> jesd204/tb: support for ModelSim and Xsim

library/Makefile, library/axi_ad5766/axi_ad5766.v, library/axi_pulse_gen/Makefile, library/axi_pulse_gen/axi_pulse_gen.v, library/axi_pulse_gen/axi_pulse_gen_constr.ttcl, library/axi_pulse_gen/axi_pulse_gen_ip.tcl, library/axi_pulse_gen/axi_pulse_gen_regmap.v, library/common/util_pulse_gen.v, library/util_tdd_sync/util_tdd_sync.v
A configurable signal generator, which can be used to generate PWM signals, or periodic pulses.
=> AXI_PULSE_GEN

library/common/up_axi.v
Signed-off-by: Edward Kigwana <ekigwana@scires.com>
=> up_axi: Remove dead code.

library/scripts/adi_ip.tcl, projects/adrv9361z7035/ccbob_cmos/system_project.tcl, projects/adrv9361z7035/common/adrv9361z7035_constr_cmos.xdc, projects/adrv9361z7035/common/adrv9361z7035_constr_lvds.xdc, projects/adrv9364z7020/common/adrv9364z7020_constr_cmos.xdc, projects/adrv9364z7020/common/adrv9364z7020_constr_lvds.xdc, projects/common/vc707/vc707_system_bd.tcl, projects/fmcomms5/zc702/system_constr.xdc, projects/fmcomms5/zc706/system_constr.xdc, projects/fmcomms5/zcu102/system_constr.xdc, projects/scripts/adi_project.tcl, projects/scripts/adi_project_alt.tcl
Update for tool versions
Vivado 2018.3
Quartus 18.1
=> Tools upgrade

library/axi_fan_control/Makefile, library/axi_fan_control/axi_fan_control.v, library/axi_fan_control/axi_fan_control_ip.tcl, library/axi_fan_control/readme.rst
version 00.01.00 of  axi_fan_control IP core
=> axi_fan_control

library/altera/avl_dacfifo/avl_dacfifo_hw.tcl, library/axi_dmac/axi_dmac.v, library/axi_dmac/axi_dmac_hw.tcl, library/axi_dmac/axi_dmac_ip.tcl, library/util_adcfifo/util_adcfifo_hw.tcl, library/util_dacfifo/util_dacfifo_hw.tcl, library/util_pack/util_upack2/util_upack2_hw.tcl, projects/adrv9009/common/adrv9009_qsys.tcl, projects/adrv9371x/common/adrv9371x_qsys.tcl, projects/arradio/common/arradio_qsys.tcl, projects/daq2/common/daq2_qsys.tcl, projects/daq3/common/daq3_qsys.tcl
Tested on HW:  DAQ2 + A10SoC
Compiled:  all Intel projects.
=> Bundle AXI Stream signals for Intel projects

library/jesd204/jesd204_common/pipeline_stage.v, library/jesd204/jesd204_rx/jesd204_rx.v, library/jesd204/jesd204_rx/jesd204_rx_hw.tcl, projects/ad9208_dual_ebz/common/dual_ad9208_bd.tcl, projects/ad9208_dual_ebz/vcu118/Makefile, projects/ad9208_dual_ebz/vcu118/system_bd.tcl, projects/ad9208_dual_ebz/vcu118/system_constr.xdc, projects/ad9208_dual_ebz/vcu118/system_project.tcl, projects/ad9208_dual_ebz/vcu118/system_top.v
Add support for the dual AD9208-DUAL-EBZ board.
Tested on VCU118
=> Ad9208 dual ebz

projects/fmcomms11/common/fmcomms11_bd.tcl
Because the AD9162 will run in M=2 mode, we have to put a upack module between the TPL and FIFO/DMA.
=> fmcomms11: Add a upack module into the TX path

library/axi_dmac/axi_dmac_regmap.v, library/axi_dmac/axi_dmac_regmap_request.v, library/axi_dmac/axi_dmac_response_manager.v, library/axi_dmac/data_mover.v, library/axi_dmac/request_arb.v, library/axi_dmac/request_generator.v
This PR contains bugfixes for: 
- partial transfers 
- transfer length reporting 
- transfer start synchronization
Tested on DAQ3 - ZC706 ; 
DAQ2 - ZC706
=> DMAC patches

library/util_adcfifo/util_adcfifo.v, library/util_adcfifo/util_adcfifo_constr.sdc, library/util_adcfifo/util_adcfifo_constr.xdc, library/util_adcfifo/util_adcfifo_hw.tcl, library/util_adcfifo/util_adcfifo_ip.tcl
There were several issues with this module which were fixed by this patch. The read and write address generation were redesigned.
=> Fix util adcfifo

library/scripts/adi_ip.tcl, library/scripts/adi_ip_alt.tcl, projects/scripts/adi_board.tcl, projects/scripts/adi_project.tcl, projects/scripts/adi_project_alt.tcl
An effort to improve our documentation. Also, tried to delete all the useless processes.
NOTE: comments are [Doxygen](http://www.doxygen.nl/manual/docblocks.html#tclblocks) compatible.
=> Add comments to the Tcl scripts

library/axi_ad9361/altera/axi_ad9361_cmos_if.v, library/axi_ad9361/altera/axi_ad9361_lvds_if.v
Fix axi_ad9361 interface, for Intel devices.
- add MIMO enable support parameter
- Update values for technology parameter
=> Fix altera axi ad9361

library/axi_ad5766/axi_ad5766.v, library/axi_ad7616/axi_ad7616.v, library/axi_adc_decimate/axi_adc_decimate.v, library/axi_adc_trigger/axi_adc_trigger.v, library/axi_dac_interpolate/axi_dac_interpolate.v, library/axi_dmac/axi_dmac_regmap.v, library/axi_fan_control/axi_fan_control.v, library/axi_logic_analyzer/axi_logic_analyzer.v, library/axi_pulse_gen/axi_pulse_gen.v, library/common/up_axi.v, library/intel/axi_adxcvr/axi_adxcvr.v, library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_regmap.v, library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v, library/jesd204/axi_jesd204_rx/axi_jesd204_rx.v, library/jesd204/axi_jesd204_tx/axi_jesd204_tx.v, library/spi_engine/axi_spi_engine/axi_spi_engine.v, library/xilinx/axi_adxcvr/axi_adxcvr.v, library/xilinx/axi_xcvrlb/axi_xcvrlb.v
ADDRESS_WIDTH parameter is now a localparam derived from AXI_ADDRESS_WIDTH
=> up_axi.v update

library/axi_ad9162/axi_ad9162_ip.tcl, library/axi_ad9434/axi_ad9434_ip.tcl, library/axi_ad9625/axi_ad9625_ip.tcl, library/axi_hdmi_tx/axi_hdmi_tx_ip.tcl
- axi_ad9162
- axi_ad9434
- axi_ad9625
- axi_hdmi_tx
=> Fix copy-paste typo in *_ip.tcl

library/xilinx/axi_dacfifo/axi_dacfifo_rd.v, library/xilinx/axi_dacfifo/axi_dacfifo_wr.v, projects/adrv9009_zu11eg_som/system_constr.xdc
Fix axi_dacfifo IP so that the constraints are applied correctly.
Added SPI clock constraint for adrv_zu11eg_som project.
=> Fix axi dacfifo

library/axi_dmac/axi_dmac.v, library/axi_dmac/axi_dmac_hw.tcl, library/axi_dmac/axi_dmac_regmap.v, library/common/up_axi.v
fixed axi_dma_regmap.v bus width missmatch
=> up_axi.v: fixed bus width definition

library/axi_generic_adc/axi_generic_adc_ip.tcl
Please merge. I use this IP a lot.
=> axi_generic_adc: infer clock for input adc_clk

library/axi_ad7616/axi_ad7616_control.v
fixed axi lite read data multiplexation
=> ad7616_bugfix

library/axi_adc_trigger/axi_adc_trigger.v, library/axi_adc_trigger/axi_adc_trigger_reg.v, library/axi_logic_analyzer/axi_logic_analyzer.v, library/axi_logic_analyzer/axi_logic_analyzer_reg.v, library/axi_logic_analyzer/axi_logic_analyzer_trigger.v, library/util_extract/util_extract.v, projects/m2k/common/m2k_bd.tcl, projects/m2k/standalone/system_constr.xdc
[axi_adc_trigger_org_plus.pdf](https://github.com/analogdevicesinc/hdl/files/2957523/axi_adc_trigger_org_plus.pdf)
=> Dev m2k add cascade support

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Minor attempt to improve our community standards. Any feedback is welcome.
=> template: Add a bug report and feature request template

projects/scripts/adi_board.tcl
made error checking more general
=> sys_id: added catch to git status check

projects/scripts/adi_project_xilinx.tcl
Add constraint files to constr_1 file set
=> Improve adi_project_xilinx.tcl script

library/axi_sysid/axi_sysid.v
ip patch version changed from h00 to h61
=> sys_id: version fix

library/axi_laser_driver/axi_laser_driver_regmap.v
Define up_pulse_s wire in register map.
=> axi_laser_driver: None functional change

projects/m2k/standalone/system_bd.tcl, projects/pluto/system_bd.tcl
Clean the old interrupt connections style.
Build tested on m2k and pluto.
=> Clean bd pluto and m2k

library/axi_dac_interpolate/axi_dac_interpolate.v, library/axi_dac_interpolate/axi_dac_interpolate_constr.xdc, library/axi_dac_interpolate/axi_dac_interpolate_filter.v, library/axi_dac_interpolate/axi_dac_interpolate_ip.tcl, library/axi_dac_interpolate/axi_dac_interpolate_reg.v, projects/m2k/common/m2k_bd.tcl
Add DAC trigger feature.
Tested on M2k.
=> Dev m2k dac trigger

projects/scripts/adi_board.tcl
Allow custom connections between axi_adxcvr and util_adxcvr
=> scripts: adi_board.tcl: Update the axi_adxcvr to util_adxcvr connections

.gitignore
Clean the noise from the git status
=> .gitignore: add simulation outputs and misc files to the list

library/axi_adc_trigger/axi_adc_trigger.v, library/axi_adc_trigger/axi_adc_trigger_reg.v
Dynamically set the out pin hold period in axi_adc_trigger regmap.
=> Adc trigger pin out hold

projects/ad7134_fmc/zed/system_constr.xdc
Fix IO definitions for SDI lines
=> ad7134_fmc quick fix

projects/adrv9009zu11eg/adrv2crr_fmc/system_project.tcl, projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl
Update the project to correspond to the production  version of the SOM
=> adv9009zu11eg: Update FPGA to -2. Update DDR4 clock frequency

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_ip.tcl, library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_regmap.v, library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl, library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_regmap.v, library/jesd204/jesd204_rx/jesd204_rx_ip.tcl, library/jesd204/jesd204_tx/jesd204_tx_ip.tcl, library/jesd204/scripts/jesd204.tcl
This series of changes adds support for L=16 and M=32 for the JESD framework.
=> Dev more lanes and converters

projects/ad_fmclidar1_ebz/README.md
Add  description of the power-up issue and its solution.
=> ad_fmclidar1_ebz/README: Add Known Issues section

library/xilinx/axi_xcvrlb/axi_xcvrlb.v, library/xilinx/axi_xcvrlb/axi_xcvrlb_1.v, library/xilinx/axi_xcvrlb/axi_xcvrlb_ip.tcl
added PLL locked reg to axi regmap; IP now recognizez xcvr type
automatically
=> axi_xcvrlb: Added new parameters to IP

library/axi_generic_adc/axi_generic_adc_ip.tcl
ad_rst.v module was missing the xdc
=> Axi generic adc fix

library/axi_fan_control/axi_fan_control.v, projects/adrv9009zu11eg/common/adrv2crr_fmc_bd.tcl
IP now has temp_in port to allow connection to System Management Wizzard IP (temp_out).
IP is more configurable, several registers were added for more flexibility.
=> Axi fan control update

library/axi_ad9361/axi_ad9361.v, library/axi_ad9361/axi_ad9361_hw.tcl, library/axi_ad9361/axi_ad9361_ip.tcl, library/axi_ad9361/intel/axi_ad9361_lvds_if.v, library/axi_ad9361/intel/axi_ad9361_lvds_if_10.v, library/axi_ad9361/xilinx/axi_ad9361_lvds_if.v, library/intel/common/intel_serdes/intel_serdes_hw.tcl, projects/fmcomms2/a10soc/Makefile, projects/fmcomms2/a10soc/system_constr.sdc, projects/fmcomms2/a10soc/system_project.tcl, projects/fmcomms2/a10soc/system_qsys.tcl, projects/fmcomms2/a10soc/system_top.v, projects/fmcomms2/common/fmcomms2_qsys.tcl
=> fmcomms2 support on a10soc

projects/ad7768evb/common/ad7768_if.v, projects/ad7768evb/common/ad7768evb_bd.tcl, projects/ad7768evb/zed/system_top.v
fixed sync inside ad7768_if module; connected sync signal to DMA;
=> ad7768_evb_sync: Fixed sync issue

library/jesd204/jesd204_rx/jesd204_rx_ip.tcl
=> jesd204_rx: fix critical warning for undriven input

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_ip.tcl, library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl
=> Fix GUI and FPGA info population  for TPL cores

projects/ad_fmclidar1_ebz/common/ad_fmclidar1_ebz_qsys.tcl
Fix the SPI interface configuration for the AFE's ADC.
=> LiDAR A10SOC: Fix AFE's SPI interface

projects/dac_fmc_ebz/a10soc/system_project.tcl, projects/dac_fmc_ebz/a10soc/system_top.v
This patch should fix the compilation issues for the dac_fmc_ebz@a10soc project.
=> Fix dac_fmc_ebz@a10soc

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl, projects/ad9081_fmca_ebz/vcu118/system_project.tcl, projects/ad9081_fmca_ebz/zcu102/system_project.tcl
This series of patches contains minor improvements to the single MxFE project. 
Tested in simulation and implementation.
=> Single MxFE improvements

library/axi_fan_control/axi_fan_control.v
Fixes bug where ip was apparently held in reset.
=> axi_fan_control: Fixed reset bug

library/axi_ad7616/axi_ad7616.v, projects/ad7616_sdz/common/ad7616_bd.tcl, projects/ad7616_sdz/zc706/serial_if_constr.xdc, projects/ad7616_sdz/zc706/system_top_si.v, projects/ad7616_sdz/zed/serial_if_constr.xdc, projects/ad7616_sdz/zed/system_top_si.v
This update was overlooked at the SPI Engine SDI port merge patch.
=> ad7616_sdz: Fix the project, after SDI ports were merged

library/jesd204/axi_jesd204_rx/axi_jesd204_rx.v, library/jesd204/axi_jesd204_rx/axi_jesd204_rx_constr.xdc, library/jesd204/axi_jesd204_rx/axi_jesd204_rx_hw.tcl, library/jesd204/axi_jesd204_rx/axi_jesd204_rx_ip.tcl, library/jesd204/axi_jesd204_rx/jesd204_up_rx.v, library/jesd204/axi_jesd204_rx/jesd204_up_rx_lane.v, library/jesd204/interfaces/interfaces_ip.tcl, library/jesd204/jesd204_rx/jesd204_rx.v, library/jesd204/jesd204_rx/jesd204_rx_ctrl_64b.v, library/jesd204/jesd204_rx/jesd204_rx_frame_align_monitor.v, library/jesd204/jesd204_rx/jesd204_rx_frame_mark.v, library/jesd204/jesd204_rx/jesd204_rx_hw.tcl, library/jesd204/jesd204_rx/jesd204_rx_ip.tcl, library/jesd204/jesd204_rx/jesd204_rx_lane.v, library/jesd204/jesd204_rx_static_config/jesd204_rx_static_config.v, library/jesd204/jesd204_rx_static_config/jesd204_rx_static_config_ip.tcl, library/jesd204/tb/frame_align_tb, library/jesd204/tb/frame_align_tb.v, library/jesd204/tb/run_tb.sh, library/jesd204/tb/tb_base.v, library/xilinx/axi_adxcvr/axi_adxcvr_up.v
- support for frame alignment check
- support for interrupt on frame alignment error
- support for interrupt on unexpected lane status error
- version update for Rx core (1.04a)
Tested on Talise SOM + FMCOMMS8
=> JESD improvements part 1 

library/axi_dac_interpolate/axi_dac_interpolate_filter.v
Fix axi_dac_interpolate interpolation ratio by 2.
Tested on m2k
=> Fix axi dac interp oversamp

library/common/ad_dds.v
Fix typo. Only Intel projects are affected by this issue.
=> ad_dds: Fix typo

library/spi_engine/spi_engine_interconnect/spi_engine_interconnect_ip.tcl
Before:
After:
NOTE: This commit does not change the functionality of the IP.
=> SPI Engine interconnect: Update IPXACT GUI layout

library/spi_engine/spi_engine_execution/spi_engine_execution_ip.tcl
Before:
After:
NOTE: This commit does not change the functionality of the IP.
=> SPI Engine execution: Update IPXACT GUI layout

library/spi_engine/axi_spi_engine/axi_spi_engine_ip.tcl
Before:
After:
NOTE: This commit does not introduce any functional changes to the IP.
=> AXI SPI Engine : Update IPXACT GUI layout

library/axi_i2s_adi/axi_i2s_adi_ip.tcl
axi_i2s_adi_ip.tcl has been modified to provide a friendly environment to the editor of a block design
=> axi_i2s_adi: create friendly xgui files

library/spi_engine/spi_engine_offload/spi_engine_offload.v
spi_engine_offload: Start offload when DMA is ready
=> spi_engine_offload: Start offload when DMA is ready

library/common/ad_tdd_control.v, library/common/up_dac_common.v, projects/arradio/c5soc/system_project.tcl, projects/arradio/c5soc/system_top.v
Fix arradio warnings related to data width and to unused signals/pins.
Build tested.
=> Fix arradio warnings

projects/fmcomms8/common/fmcomms8_spi.v, projects/fmcomms8/zcu102/system_constr.xdc, projects/fmcomms8/zcu102/system_top.v
Cleanup of the FMCOMMS8 + ZCU102
=> Fix fmcomms8 zcu102

library/spi_engine/scripts/spi_engine.tcl
spi_engine.tcl contains a process used to build the spi engine bd hierarchy
=> spi_engine: Add spi_engine.tcl

library/jesd204/axi_jesd204_common/jesd204_up_common.v, library/jesd204/axi_jesd204_common/jesd204_up_sysref.v, library/jesd204/axi_jesd204_rx/axi_jesd204_rx.v, library/jesd204/axi_jesd204_rx/jesd204_up_rx.v, library/jesd204/axi_jesd204_rx/jesd204_up_rx_lane.v, library/jesd204/axi_jesd204_tx/axi_jesd204_tx.v, library/jesd204/axi_jesd204_tx/jesd204_up_tx.v, library/jesd204/jesd204_common/jesd204_lmfc.v, library/jesd204/jesd204_common/jesd204_scrambler.v, library/jesd204/jesd204_rx/align_mux.v, library/jesd204/jesd204_rx/jesd204_ilas_monitor.v, library/jesd204/jesd204_rx/jesd204_rx.v, library/jesd204/jesd204_rx/jesd204_rx_ctrl.v, library/jesd204/jesd204_rx/jesd204_rx_frame_align_monitor.v, library/jesd204/jesd204_rx/jesd204_rx_lane.v, library/jesd204/jesd204_soft_pcs_rx/jesd204_8b10b_decoder.v, library/jesd204/jesd204_soft_pcs_rx/jesd204_pattern_align.v, library/jesd204/jesd204_soft_pcs_tx/jesd204_8b10b_encoder.v, library/jesd204/jesd204_tx/jesd204_tx_lane.v
- JESD link statistic counter for link enable, interrupt sources 
- fix deglitch mechanism durin link bringup in Rx peripheral
Tested with ADRV9009 + ZC706
=> JESD improvements

projects/cn0506_mii/common/cn0506_bd.tcl, projects/cn0506_rgmii/common/cn0506_bd.tcl
These two projects were originally missed by the find/replace command
=> sysid: Remove cstring init string

projects/ad77681evb/common/ad77681evb_bd.tcl
spi_clk changed from 40MHz to 80MHz
fixed data loss issue
=> ad77681: Add axi_clkgen ip for spi engine

library/util_sigma_delta_spi/util_sigma_delta_spi.v
Syntax was not following coding guidelines and was causing warnings
=> util_sigma_delta_spi: Fix syntax

projects/daq3/common/daq3_bd.tcl, projects/daq3/common/daq3_qsys.tcl
Use generic JESD204B TPL instead of specific device IPs
Tested on ZC706 and ZCU102
=> daq3: Update projects to the new TPL

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_hw.tcl, library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_hw.tcl, projects/common/a10soc/a10soc_system_qsys.tcl, projects/fmcomms8/a10soc/Makefile, projects/fmcomms8/a10soc/system_constr.sdc, projects/fmcomms8/a10soc/system_project.tcl, projects/fmcomms8/a10soc/system_qsys.tcl, projects/fmcomms8/a10soc/system_top.v, projects/fmcomms8/common/fmcomms8_qsys.tcl
Port fmcomms8 to A10SOC.
The project was tested
=> Fmcomms8 a10soc

library/axi_ad7616/axi_ad7616_control.v, library/common/ad_edge_detect.v, projects/ad469x_fmc/common/ad469x_bd.tcl, projects/ad469x_fmc/zed/system_bd.tcl
fix critical warnings related to invalid port names
=> Fix port names

library/common/up_dac_common.v, library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_core.v, projects/adrv9009zu11eg/adrv2crr_fmcomms8/fmcomms8_constr.xdc
Update the TX (DAC) application layer synchronization mechanism to be more like the RX (ADC) synchronization mechanism
=> Fix tx sync

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl, projects/ad9081_fmca_ebz/zc706/Makefile, projects/ad9081_fmca_ebz/zc706/system_bd.tcl, projects/ad9081_fmca_ebz/zc706/system_constr.xdc, projects/ad9081_fmca_ebz/zc706/system_project.tcl, projects/ad9081_fmca_ebz/zc706/system_top.v, projects/ad9081_fmca_ebz/zc706/timing_constr.xdc, projects/ad9081_fmca_ebz/zcu102/system_bd.tcl
Tested in hardware with ZC706 and AD9081-FMC-EBZ
=> MxFE support on ZC706

projects/ad9081_fmca_ebz/zcu102/system_project.tcl
Allow setting project parameters from the environment.
Tested with MxFE:ZCU102
=> ad9081:zcu102: Expose parameters to environment

library/axi_adrv9001/axi_adrv9001.v, library/axi_adrv9001/axi_adrv9001_core.v, library/axi_adrv9001/axi_adrv9001_hw.tcl, library/axi_adrv9001/axi_adrv9001_ip.tcl, library/axi_adrv9001/axi_adrv9001_tdd.v, library/axi_adrv9001/axi_adrv9001_tx.v, library/common/ad_tdd_control.v, library/common/up_tdd_cntrl.v, projects/adrv9001/common/adrv9001_bd.tcl, projects/adrv9001/zcu102/system_constr.xdc, projects/adrv9001/zcu102/system_top.v, projects/adrv9001/zed/system_constr.xdc, projects/adrv9001/zed/system_top.v
=> TDD support for ADRV9001

projects/cn0501/coraz7s/system_bd.tcl
=> cn0501/coraz7s: Fix sysid

projects/ad9081_fmca_ebz/a10soc/Makefile, projects/ad9081_fmca_ebz/a10soc/system_constr.sdc, projects/ad9081_fmca_ebz/a10soc/system_project.tcl, projects/ad9081_fmca_ebz/a10soc/system_qsys.tcl, projects/ad9081_fmca_ebz/a10soc/system_top.v, projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_qsys.tcl, projects/common/a10soc/a10soc_system_qsys.tcl, projects/common/intel/adcfifo_qsys.tcl
=> Dev mxfe a10soc

library/util_axis_fifo/util_axis_fifo.v
Add axis_tlast support for the util_axis_fifo. Also add a unit level test bench for the IP.
Note: The make file of the test bench is not integrated into the main makefile framework. That can be done in an another task.
=> Add TLAST support for util_axis_fifo

library/util_axis_fifo/util_axis_fifo_ip.tcl
Some minor fixes for the util_axis_fifo.
=> Fix util_axis_fifo IP Tcl file

library/util_axis_fifo/util_axis_fifo.v, library/util_axis_fifo/util_axis_fifo_address_generator.v
Add almost empty and almost full indicators to the util_axis_fifo.
=> util_axis_fifo: Add almost empty and almost full support

library/jesd204/jesd204_tx/jesd204_tx.v
This commit will help software to identify the hardware capabilities. 
This already exists on the Rx core.
=> jesd204/jesd204_tx: Expose character replacement capability

library/axi_ad9361/axi_ad9361_constr.xdc, library/axi_adrv9001/axi_adrv9001_constr.sdc, library/axi_adrv9001/axi_adrv9001_constr.xdc, library/axi_adrv9001/axi_adrv9001_core.v, library/axi_adrv9001/axi_adrv9001_hw.tcl, library/axi_adrv9001/axi_adrv9001_tx.v, projects/adrv9001/zcu102/cmos_constr.xdc, projects/fmcomms2/zed/system_bd.tcl
Some Navassa related fixes got introduced to 2019_R2 after it got branched from master. 
Put the same fixes into the master.
=> Integrate 2019 r2 changes to master

library/util_axis_fifo/util_axis_fifo.v, library/util_axis_fifo/util_axis_fifo_address_generator.v
FIFO is full signal had a delay of one clock cycle, this patch will make it synchronous with the actual state of the FIFO. Plus a cosmetic change to make easier to debug the data flow in a wave viewer.
=> Fix util_axis_fifo full signaling

projects/adrv9009zu11eg/adrv2crr_fmc/system_top.v, projects/adrv9009zu11eg/common/adrv2crr_fmc_constr.xdc
Added 2 more CS signals to the P25 connector by M.Bancisor and sw team's request
=> Rfsom carrier spi

library/axi_adrv9001/adrv9001_aligner4.v, library/axi_adrv9001/adrv9001_aligner8.v, library/axi_adrv9001/adrv9001_pack.v, library/axi_adrv9001/adrv9001_rx.v, library/axi_adrv9001/adrv9001_rx_link.v, library/axi_adrv9001/adrv9001_tx.v, library/axi_adrv9001/axi_adrv9001.v, library/axi_adrv9001/axi_adrv9001_core.v, library/axi_adrv9001/axi_adrv9001_if.v, library/axi_adrv9001/axi_adrv9001_rx.v, library/axi_adrv9001/axi_adrv9001_rx_channel.v, library/axi_adrv9001/axi_adrv9001_tdd.v, library/axi_adrv9001/axi_adrv9001_tx.v, library/axi_adrv9001/intel/adrv9001_rx.v, library/axi_adrv9001/intel/adrv9001_tx.v, library/common/up_dac_common.v, projects/adrv9001/a10soc/Makefile, projects/adrv9001/a10soc/system_constr.sdc, projects/adrv9001/a10soc/system_project.tcl, projects/adrv9001/a10soc/system_qsys.tcl, projects/adrv9001/a10soc/system_top.v, projects/adrv9001/common/adrv9001_qsys.tcl, projects/adrv9001/zcu102/cmos_constr.xdc, projects/adrv9001/zcu102/system_bd.tcl
These series of changes introduce:
- A10SoC support
- various fixes from hdl_2019_r2
=> Dev adrv9001 a10soc zc706

projects/ad469x_fmc/zed/Makefile, projects/ad469x_fmc/zed/system_project.tcl
=> ad469x: Clean system_project.tcl

library/intel/adi_jesd204/adi_jesd204_hw.tcl, library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_hw.tcl, library/jesd204/axi_jesd204_rx/axi_jesd204_rx_hw.tcl, library/jesd204/axi_jesd204_tx/axi_jesd204_tx_hw.tcl, library/jesd204/jesd204_rx/jesd204_rx_hw.tcl, library/jesd204/jesd204_tx/jesd204_tx_hw.tcl
Tested with Dual AD9213 project
=> adi_jesd204: Add support of 16 lanes

library/Makefile, library/util_axis_fifo_asym/Makefile, library/util_axis_fifo_asym/util_axis_fifo_asym.v, library/util_axis_fifo_asym/util_axis_fifo_asym_ip.tcl, library/util_fifo2axi_bridge/Makefile, library/util_fifo2axi_bridge/util_fifo2axi_bridge.v, library/util_fifo2axi_bridge/util_fifo2axi_bridge_constr.xdc, library/util_fifo2axi_bridge/util_fifo2axi_bridge_ip.tcl
The IP is responsible to transfer data between a data_offload controller and MIG instance.
NOTE: Should be merged after #656
=> util_fifo2axi bridge

projects/pluto/system_bd.tcl
Adding pluto fix also for the 2019_r2 branch
=> pluto: Fix dunf connection

library/axi_adrv9001/axi_adrv9001_hw.tcl, projects/scripts/adi_project_intel.tcl
Update quartus compilation tools from 20.1 to 20.4.
Remove hardcoded version from axi_adrv9001 ip.
=> Update Quartus version to 20.4

projects/ad40xx_fmc/common/ad40xx_bd.tcl, projects/ad40xx_fmc/zed/system_bd.tcl, projects/ad40xx_fmc/zed/system_project.tcl
Changed the parameters for environment variables. Added these to the system ID.
=> ad400xx_fmc: Parametrize board select, sampling rate and adc resolution

library/axi_pwm_gen/axi_pwm_gen.v, library/axi_pwm_gen/axi_pwm_gen_1.v, library/axi_pwm_gen/axi_pwm_gen_regmap.v
Some scenarios require configuration of the pwm_gen in software reset.
Tested in test bench.
=> axi_pwm_gen: Add config in soft reset option

projects/scripts/adi_project_intel.tcl
Update Quartus version to 21.2.0.
=> adi_project_intel.tcl: update quartus to 21.2

projects/ad9213_dual_ebz/Makefile, projects/ad9213_dual_ebz/common/ad9213_dual_qsys.tcl, projects/ad9213_dual_ebz/s10soc/Makefile, projects/ad9213_dual_ebz/s10soc/system_constr.sdc, projects/ad9213_dual_ebz/s10soc/system_project.tcl, projects/ad9213_dual_ebz/s10soc/system_qsys.tcl, projects/ad9213_dual_ebz/s10soc/system_top.v, projects/common/s10soc/s10soc_system_qsys.tcl, projects/scripts/adi_project_intel.tcl
Initial commit for the AD9213 project.
It needs to be retested in hardware.
This updates also the S10SOC base design from the ES version to the production H-Tile version.
=> Ad9213 dual ebz

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_ip.tcl, library/jesd204/ad_ip_jesd204_tpl_dac/ad_ip_jesd204_tpl_dac_ip.tcl
=> jesd204/ad_ip_jesd204_tpl : Add support for 6 and 12 lanes

projects/ad9082_fmca_ebz/Readme.md, projects/ad9208_dual_ebz/Readme.md, projects/ad9213_dual_ebz/Readme.md
Fix incorrect product pages for the dual AD9208 and AD9213 boards, 
Fix AD9082 project part
=> Fix readmes

projects/ad4630_fmc/Readme.md
=> ad463x: Fix readme

projects/ad9081_fmca_ebz/vcu128/Makefile, projects/ad9081_fmca_ebz/vcu128/system_bd.tcl, projects/ad9081_fmca_ebz/vcu128/system_constr.xdc, projects/ad9081_fmca_ebz/vcu128/system_project.tcl, projects/ad9081_fmca_ebz/vcu128/system_top.v, projects/ad9081_fmca_ebz/vcu128/timing_constr.xdc, projects/common/vcu128/vcu128_system_bd.tcl, projects/common/vcu128/vcu128_system_constr.xdc, projects/scripts/adi_board.tcl, projects/scripts/adi_project_xilinx.tcl
=> Add support for VCU128 and MxFE on VCU128

projects/pulsar_adc_pmdz/Makefile, projects/pulsar_adc_pmdz/Readme.md, projects/pulsar_adc_pmdz/common/pulsar_adc_pmdz_bd.tcl, projects/pulsar_adc_pmdz/coraz7s/Makefile, projects/pulsar_adc_pmdz/coraz7s/system_bd.tcl, projects/pulsar_adc_pmdz/coraz7s/system_constr.xdc, projects/pulsar_adc_pmdz/coraz7s/system_project.tcl, projects/pulsar_adc_pmdz/coraz7s/system_top.v
Add reference design for pulsar adc pmods
=> Add support for pulsar adc pmdz

library/axi_ad7616/axi_ad7616.v, projects/ad7616_sdz/common/ad7616_bd.tcl, projects/ad7616_sdz/zc706/system_project.tcl, projects/ad7616_sdz/zed/system_project.tcl
Fixed sync connection, updated build scripts
=> Ad7616 dev

projects/fmcjesdadc1/common/fmcjesdadc1_bd.tcl
=> Fix fmcjesdadc1

projects/fmcadc2/common/fmcadc2_bd.tcl, projects/fmcadc2/vc707/Makefile, projects/fmcadc2/vc707/system_project.tcl, projects/fmcadc2/vc707/system_top.v, projects/fmcadc2/zc706/Makefile, projects/fmcadc2/zc706/system_project.tcl, projects/fmcadc2/zc706/system_top.v
Updated the JESD204B transport layer instance to instantiate the new TPL IP
module.
=> fmcadc2: Update JESD204 TPL instance

projects/adrv9361z7035/common/ccfmc_constr.xdc
=> adrc9361_ccfmc: Fix SFP pin locations

library/jesd204/jesd204_common/pipeline_stage.v
Initialized this register for TPL Error found in the ADRV9009 test bench.
=> library/jesd204/jesd204_common/pipeline_stage.v: Initialize pipeline stage register

projects/adrv9371x/common/adrv9371x_bd.tcl, projects/adrv9371x/kcu105/system_project.tcl, projects/adrv9371x/zc706/system_project.tcl, projects/adrv9371x/zcu102/system_project.tcl
=> adrv9371x: Parameterize JESD204 configuration values

projects/adrv9009/common/adrv9009_bd.tcl, projects/adrv9009/zc706/system_project.tcl, projects/adrv9009/zcu102/system_project.tcl
=> adrv9009: Parameterize JESD204 configuration values

projects/ad6676evb/common/ad6676evb_bd.tcl, projects/ad6676evb/vc707/Makefile, projects/ad6676evb/vc707/system_project.tcl, projects/ad6676evb/vc707/system_top.v, projects/ad6676evb/zc706/Makefile, projects/ad6676evb/zc706/system_project.tcl, projects/ad6676evb/zc706/system_top.v
1. Updated the JESD204 TPL instantation of the design.
2. Added the capability to set the JESD204 configuration values from a single
line for the Xilinx FPGAs in the project.
=> Ad6676: Update JESD204 TPL instantiation and parameterize JESD204 configuration values

projects/ad77681evb/common/ad77681evb_bd.tcl
spi engine irq signal was overwriting fmc iic irq
=> ad77681evb: Fix irq overlap

library/Makefile, library/util_mii_to_rmii/Makefile, library/util_mii_to_rmii/mac_phy_link.v, library/util_mii_to_rmii/phy_mac_link.v, library/util_mii_to_rmii/util_mii_to_rmii.v, library/util_mii_to_rmii/util_mii_to_rmii_ip.tcl, projects/cn0506_rmii/zc706/Makefile, projects/cn0506_rmii/zc706/system_bd.tcl, projects/cn0506_rmii/zc706/system_constr.xdc, projects/cn0506_rmii/zcu102/Makefile, projects/cn0506_rmii/zcu102/system_bd.tcl, projects/cn0506_rmii/zed/Makefile, projects/cn0506_rmii/zed/system_bd.tcl, projects/cn0506_rmii/zed/system_constr.xdc
util_mii_to_rmii IP: 70a665c
util_mii_to_rmii IP added to cn0506_rmii project: d87c95c
=> util_mii_to_rmii: Add MII to RMII Converter IP

projects/dac_fmc_ebz/vcu118/system_top.v, projects/dac_fmc_ebz/zc706/system_top.v, projects/dac_fmc_ebz/zcu102/system_top.v
Bugfix for dac_fmc_ebz projects
=> dac_fmc_ebz: NUM_LINKS added to system_top.v

projects/scripts/gtwiz_parser.pl, projects/scripts/gtwizard_generator.tcl
This pull request is for testing, there needs to be done some beautification within the code.
To test the scripts:
1. Open a project
2. run the command: source ../../scripts/gtwizard_generator.tcl
3. run the command with desired parameters: get_diff_params lane_rate pll_type ref_clk
(ex: get_diff_params 15.4 QPLL0 385)
It will print the path to generated files. The most relevant one is *_cfng.txt. where it specifies the parameters that need to be changed for the wanted configuration.
=> projects/scripts: Add gtwizard scripts

projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/Makefile, projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_bd.tcl, projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_constr.xdc, projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_project.tcl, projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_top.v
Initial commit for the fmcxmwbr1 fmc bridge on adrv9009zu11eg.
=> Add support for fmcxmwbr1

projects/pluto_ng/Readme.md
Add Readme.md file to pluto_ng project.
=> pluto_ng: Add Readme.md file

library/util_mii_to_rmii/mac_phy_link.v, library/util_mii_to_rmii/phy_mac_link.v
This PR will fix 100 Mbps configuration functionality and remove unused code from **util_mii_to_rmii** IP files.
=> util_mii_to_rmii: Fix 100 Mbps configuration functionality

.github/scripts/check_for_missing_readme_md.sh, .github/workflows/test_n_lint.yml
No functional changes.
Signed-off-by: Robin Getz <robin.getz@analog.com>
=> Add small check to make sure readme.md files are in projects

library/Makefile, library/axi_clock_monitor/Makefile, library/axi_clock_monitor/README.md, library/axi_clock_monitor/axi_clock_monitor.v, library/axi_clock_monitor/axi_clock_monitor_hw.tcl, library/axi_clock_monitor/axi_clock_monitor_ip.tcl
Added axi_clock_monitor ip core to library folder
=> library: Adding axi_clock_monitor ip core

projects/adrv9009zu11eg/adrv2crr_fmc/system_top.v, projects/adrv9009zu11eg/adrv2crr_fmcomms8/system_top.v, projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_top.v, projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_top.v, projects/adrv9009zu11eg/common/adrv2crr_fmc_constr.xdc
This should integrate seamlessly with SYNCHRONA14
=> adrv9009zu11eg: Added additional GPIOs and CS to the GPIO expander

projects/arradio/c5soc/Makefile, projects/arradio/c5soc/system_project.tcl, projects/arradio/c5soc/system_top.v, projects/common/c5soc/c5soc_system_qsys.tcl
V4 Modified with ad_dma_interconnect.
=> arradio_c5soc: axi_hdmi_tx as framereader

projects/ad9695_fmc/Makefile, projects/ad9695_fmc/Readme.md, projects/ad9695_fmc/common/ad9695_fmc_bd.tcl, projects/ad9695_fmc/zcu102/Makefile, projects/ad9695_fmc/zcu102/system_bd.tcl, projects/ad9695_fmc/zcu102/system_constr.xdc, projects/ad9695_fmc/zcu102/system_project.tcl, projects/ad9695_fmc/zcu102/system_top.v
Add ad9695_fmc_zcu102 project.
=> ad9695: Add reference design for ad9596 eval board

library/Makefile, library/axi_adaq8092/Makefile, library/axi_adaq8092/axi_adaq8092.v, library/axi_adaq8092/axi_adaq8092_apb_decode.v, library/axi_adaq8092/axi_adaq8092_channel.v, library/axi_adaq8092/axi_adaq8092_if.v, library/axi_adaq8092/axi_adaq8092_ip.tcl, library/axi_adaq8092/axi_adaq8092_rand_decode.v, library/common/up_adc_common.v, projects/adaq8092_fmc/Makefile, projects/adaq8092_fmc/Readme.md, projects/adaq8092_fmc/common/adaq8092_bd.tcl, projects/adaq8092_fmc/zed/Makefile, projects/adaq8092_fmc/zed/system_bd.tcl, projects/adaq8092_fmc/zed/system_constr.xdc, projects/adaq8092_fmc/zed/system_project.tcl, projects/adaq8092_fmc/zed/system_top.v
V1 for ADAQ8092 with LVDS output mode support project.
=> Adaq8092 on ZedBoard LVDS output mode 

library/axi_dmac/axi_dmac_regmap.v
Added the BYTES_PER_BURST_WIDTH interface parameter in INTERFACE_DESCRIPTION
=> axi_dmac_regmap update

projects/scripts/adi_board.tcl
- On designs where the GT channels are not mapped in order, supporting less lanes than max is an issue from QPLL perspective.   Suppose max number of lanes is 16 and we use only 4 of them, but these are mapped to different quads.  The **ad_xcvrcon** will hook up only a single quad cm_  DRP port, so only one lane from four could operate. 
- The current approach for solving this bug is by connecting the maximum number of lanes between **util_xcvr** and **axi_adxcvr** by respecting the initial lane map. The actual number of used lanes, are connected between **jesd_xcvr** and **util_xcvr** using a reduced lane map that is provided through the new **partial_lane_map** parameter in the **ad_xcvrcon** procedure.
=> projects/scripts/adi_board: Add support for sparse channel maping

projects/cn0561/Makefile, projects/cn0561/Readme.md, projects/cn0561/common/cn0561_bd.tcl, projects/cn0561/coraz7s/Makefile, projects/cn0561/coraz7s/system_bd.tcl, projects/cn0561/coraz7s/system_constr.xdc, projects/cn0561/coraz7s/system_project.tcl, projects/cn0561/coraz7s/system_top.v, projects/cn0561/zed/Makefile, projects/cn0561/zed/system_bd.tcl, projects/cn0561/zed/system_constr.xdc, projects/cn0561/zed/system_project.tcl, projects/cn0561/zed/system_top.v
Add cn0561 project for coraz7s and zed
=> Cn0561 dev

docs/hdl_coding_guideline.md
Add HDL coding guideline file in /docs.
=> docs: Add HDL coding guideline

projects/ad9083_evb/common/ad9083_evb_bd.tcl
Allow external parameters and a more flexible configuration.
This will help with the code reusability.
Built tested on zcu102.
=> ad9083_evb_bd: make the project more generic

projects/ad9213_dual_ebz/s10soc/system_constr.sdc, projects/ad9213_dual_ebz/s10soc/system_top.v
Cleaned up constraints and added possibility to switch the order of the channels through an GPIO
Tested in hardware
=> Dual ad9213 update

library/Makefile, library/axi_ltc2387/Makefile, library/axi_ltc2387/axi_ltc2387.v, library/axi_ltc2387/axi_ltc2387_channel.v, library/axi_ltc2387/axi_ltc2387_if.v, library/axi_ltc2387/axi_ltc2387_ip.tcl, projects/cn0577/Makefile, projects/cn0577/Readme.md, projects/cn0577/common/cn0577_bd.tcl, projects/cn0577/zed/Makefile, projects/cn0577/zed/system_bd.tcl, projects/cn0577/zed/system_constr.xdc, projects/cn0577/zed/system_project.tcl, projects/cn0577/zed/system_top.v
- Add axi_ltc2387
- Add cn0577/zed
=> Add CN0577 support on Zedboard

projects/common/vcu118/vcu118_system_bd.tcl
**Tested on hardware with ad9081_fmca_ebz project!**
Worked well with ad_quadmxfe1_ebz project with a reduce clock frequency of 188 Mhz!
**Tested on hardware for the quadmxfe1_ebz project**
=> vcu118: Increase Microblaze performance and clock frequency

projects/ad_quadmxfe1_ebz/vcu118/system_bd.tcl
This PR is based on https://github.com/analogdevicesinc/hdl/pull/928
=> ad_quadmxfe1_ebz/vcu118: Change DRP clock source used for jesd204_phy

projects/daq2/common/daq2_bd.tcl
(\ character has to be removed or a blank line inserted before ad_ip_parameter)
Fix for : 0b8585a6f commit.
=> projects:daq2:common: fix adi_tpl_jesd204_rx_create error.

projects/ad_quadmxfe1_ebz/vcu118/system_project.tcl
=> ad_quadmxfe1_ebz/vcu118/system_project.tcl: Update  comments

library/data_offload/data_offload.v, library/util_axis_fifo_asym/util_axis_fifo_asym.v, library/util_do_ram/util_do_ram.v
=> Fix data offload block RAM and bypass modes 2021 r1

library/data_offload/data_offload.v, projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl, projects/ad9081_fmca_ebz/vck190/Makefile, projects/ad9081_fmca_ebz/vcu118/Makefile, projects/ad9081_fmca_ebz/vcu128/Makefile, projects/ad9081_fmca_ebz/zc706/Makefile, projects/ad9081_fmca_ebz/zcu102/Makefile, projects/ad9082_fmca_ebz/zc706/Makefile, projects/ad9082_fmca_ebz/zcu102/Makefile
=> Minor MxFE data offload fixes

projects/ad9082_fmca_ebz/vcu118/system_project.tcl, projects/ad9082_fmca_ebz/zc706/system_project.tcl, projects/ad9082_fmca_ebz/zcu102/system_project.tcl
Tested on ZCU102 + AD9082 which goes to the SDCARD.
=> AD9082 project parameter fixes

library/data_offload/data_offload.v, projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl, projects/ad9081_fmca_ebz/vck190/Makefile, projects/ad9081_fmca_ebz/vcu118/Makefile, projects/ad9081_fmca_ebz/vcu128/Makefile, projects/ad9081_fmca_ebz/zc706/Makefile, projects/ad9081_fmca_ebz/zcu102/Makefile, projects/ad9082_fmca_ebz/zc706/Makefile, projects/ad9082_fmca_ebz/zcu102/Makefile
Same changes entered in 2021_r1
=> Fix ad9081 do master

projects/ad9082_fmca_ebz/vcu118/system_project.tcl, projects/ad9082_fmca_ebz/zc706/system_project.tcl, projects/ad9082_fmca_ebz/zcu102/system_project.tcl
These changes are done and tested in 2021_r1. apply them also here.
=> Ad9082 fixes for master

library/data_offload/data_offload.v, library/util_axis_fifo_asym/util_axis_fifo_asym.v, library/util_do_ram/util_do_ram.v
=> Fix data offload block RAM and bypass modes

library/Makefile, library/axi_ad777x/Makefile, library/axi_ad777x/axi_ad777x.v, library/axi_ad777x/axi_ad777x_hw.tcl, library/axi_ad777x/axi_ad777x_if.v, library/axi_ad777x/axi_ad777x_ip.tcl, library/common/up_adc_channel.v, library/common/up_adc_common.v, projects/ad777x_ardz/Makefile, projects/ad777x_ardz/Readme.md, projects/ad777x_ardz/common/ad777x_ardz_bd.tcl, projects/ad777x_ardz/common/ad777x_ardz_qsys.tcl, projects/ad777x_ardz/de10nano/Makefile, projects/ad777x_ardz/de10nano/system_constr.sdc, projects/ad777x_ardz/de10nano/system_project.tcl, projects/ad777x_ardz/de10nano/system_qsys.tcl, projects/ad777x_ardz/de10nano/system_top.v, projects/ad777x_ardz/zed/Makefile, projects/ad777x_ardz/zed/system_bd.tcl, projects/ad777x_ardz/zed/system_constr.xdc, projects/ad777x_ardz/zed/system_project.tcl, projects/ad777x_ardz/zed/system_top.v
V1 with ts=th=50ns for DE10Nano
=> AD777x support for ZedBoard and DE10Nano

projects/ad9082_fmca_ebz/vcu118/Makefile, projects/dac_fmc_ebz/vcu118/Makefile
- ad9082_fmca_ebz/vcu118
- dac_fmc_ebz/vcu118
=> projects: Fix some Makefiles

library/common/tb/ad_pack_tb.v
=> common/tb/ad_pack_tb: Add non random scenario as first test for debug

.github/scripts/check_for_missing_readme_md.sh
Changed the search for README.md file to be case insensitive
=> scripts/check_readme: Change search to be case insensitive

projects/cn0540/common/cn0540_bd.tcl, projects/cn0561/common/cn0561_bd.tcl, projects/pulsar_adc_pmdz/common/pulsar_adc_pmdz_bd.tcl
=> The memory interconnect fix for all Coraz7s projects

projects/adrv9009zu11eg/adrv2crr_fmc/system_project.tcl, projects/adrv9009zu11eg/adrv2crr_fmcomms8/system_bd.tcl, projects/adrv9009zu11eg/adrv2crr_fmcomms8/system_project.tcl, projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/system_project.tcl, projects/adrv9009zu11eg/adrv2crr_xmicrowave/system_project.tcl, projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl
expose jesd parameters to make, and add FMCOMMS8 parameter to determine the max number of lanes for the system
=> projects/adrv9009zu11eg: expose jesd params to make 

library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc.v, library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_channel.v, library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_core.v, library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_hw.tcl, library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_ip.tcl, library/jesd204/ad_ip_jesd204_tpl_adc/ad_ip_jesd204_tpl_adc_pnmon.v
V1: Added PN7 and PN15 PRBS capabilities. Tested on AD9083EVB+ZCU102.
=> library/jesd204/ad_ip_jesd204_tpl_adc: Added support for PN7 and PN15

projects/cn0506/README.md
Update project's directory name in the README file: [commit](a3494a82681e5002c077b814303428db2f3e656e);
=> cn0506: Update project's directory name in the README file

projects/ad9083_evb/common/ad9083_evb_bd.tcl, projects/ad9083_evb/zcu102/system_bd.tcl, projects/ad9083_evb/zcu102/system_project.tcl, projects/ad9083_vna/common/ad9083_vna_bd.tcl, projects/ad9083_vna/zcu102/system_bd.tcl, projects/ad9083_vna/zcu102/system_project.tcl
=> Ad9083 jesd config

projects/ad9081_fmca_ebz_x_band/Makefile, projects/ad9081_fmca_ebz_x_band/Readme.md, projects/ad9081_fmca_ebz_x_band/zcu102/Makefile, projects/ad9081_fmca_ebz_x_band/zcu102/system_bd.tcl, projects/ad9081_fmca_ebz_x_band/zcu102/system_project.tcl, projects/ad9081_fmca_ebz_x_band/zcu102/system_top.v, projects/ad9081_fmca_ebz_x_band/zcu102/xband_constr.xdc
HDL project for Stingray: X/Ku Band Phased Array Prototyping System
=> ad9081_fmca_ebz_x_band:zcu102: X band project initial version

library/axi_ad7768/axi_ad7768_if.v, library/common/up_adc_channel.v
=> axi_ad7768: modified adc_format values and crc_err flag has to be RW1C

projects/ad9081_fmca_ebz/a10soc/system_project.tcl, projects/adrv9009/a10soc/system_project.tcl, projects/dac_fmc_ebz/a10soc/system_project.tcl, projects/fmcomms8/a10soc/system_project.tcl
adrv9009, dac_fmc_ebz, ad9081_fmca_ebz, fmcomms8:
Increased PLACEMENT_EFFORT_MULTIPLIER global parameter to 1.2 for increased quality of placements
=> projects: Fix intermitent timing violation on a10soc

projects/common/vcu118/vcu118_system_bd.tcl
Add new interrupt to support more devices connected to Microblaze
=> vcu118_system_bd.tcl: Additional microblaze interrupt for VCU118

projects/fmcomms8/common/fmcomms8_bd.tcl
Signed-off-by: LIacob106 <liviu.iacob@analog.com>
=> projects/fmcomms8: Interconnect m_axi port for rx_xcvr

projects/adrv9009/common/adrv9009_bd.tcl, projects/adrv9009/zc706/system_bd.tcl, projects/scripts/adi_board.tcl
Signed-off-by: LIacob106 <liviu.iacob@analog.com>
=> projects/adrv9009: JESD support for 1, 2 TX_L and 1 RX/ORX_L

projects/adrv9009zu11eg/common/adrv9009zu11eg_bd.tcl
Adrv9009zu11eg jesd support for more configurations
=> Adrv9009zu11 rebase master

library/axi_pwm_gen/Makefile, library/axi_pwm_gen/axi_pwm_gen_hw.tcl
Signed-off-by: Jem Geronimo <johnerasmusmari.geronimo@analog.com>
=> axi_pwm_gen: add: intel support

projects/cn0579/Makefile, projects/cn0579/Readme.md, projects/cn0579/common/cn0579_bd.tcl, projects/cn0579/common/cn0579_qsys.tcl, projects/cn0579/coraz7s/Makefile, projects/cn0579/coraz7s/system_bd.tcl, projects/cn0579/coraz7s/system_constr.xdc, projects/cn0579/coraz7s/system_project.tcl, projects/cn0579/coraz7s/system_top.v, projects/cn0579/de10nano/Makefile, projects/cn0579/de10nano/system_constr.sdc, projects/cn0579/de10nano/system_project.tcl, projects/cn0579/de10nano/system_qsys.tcl, projects/cn0579/de10nano/system_top.v
Added support for CN0579 on Coraz7S and DE10Nano.
=> projects/cn0579: Initial commit for Coraz7s and DE10Nano

docs/regmap/adi_regmap_adc.txt, library/common/up_adc_channel.v, library/common/up_adc_common.v
- needed on #1082 
Signed-off-by: John Erasmus Mari Geronimo <Johnerasmusmari.Geronimo@analog.com>
=> add: softspan support in adc channel regmap

projects/common/kc705/kc705_system_bd.tcl, projects/common/vc707/vc707_system_bd.tcl
V1: Tested on VC707, KC705 with PetaLinux.
=> kc705 vc707: Increase linear flash capacity

projects/ad9081_fmca_ebz/common/ad9081_fmca_ebz_bd.tcl, projects/ad9081_fmca_ebz/common/versal_transceiver.tcl, projects/ad9081_fmca_ebz/vck190/system_top.v
* Fixes the TX link that didn't work at higher lanerates
=> Proper reset sequence for versal quads

projects/adrv9009/zc706/system_project.tcl, projects/adrv9009/zcu102/system_project.tcl, projects/adrv9009zu11eg/adrv2crr_fmc/system_project.tcl, projects/adrv9009zu11eg/adrv2crr_fmcomms8/system_project.tcl, projects/fmcomms8/zcu102/system_project.tcl
Add a list with make commands with the proper parameters for each devicetree availible at the moment.
Signed-off-by: LIacob106 <liviu.iacob@analog.com>
=> projects: 9009: system_project.tcl: List configs as comments

projects/common/kv260/Makefile, projects/common/kv260/kv260_system_bd.tcl, projects/common/kv260/kv260_system_constr.xdc, projects/common/kv260/system_bd.tcl, projects/common/kv260/system_project.tcl, projects/common/kv260/system_top.v, projects/scripts/adi_project_xilinx.tcl
- Add template constraints and bd files for kv260 Vision AI kit, the evaluation board of the K26SOM;
=> template_kv260: Add template design for kv260 evaluation board

docs/hdl_pr_process.md
Added in /docs the Pull Request process that the HDL team is following
=> docs: Add HDL PR process documentation

.gitignore
Added CODEOWNERS file and the PR template file to .gitignore
=> .gitignore: Ignore CODEOWNERS and PR template

docs/regmap/adi_regmap_dac.txt
-Updated description of some fields of these registers: REG_CHAN_CNTRL_1, REG_CHAN_CNTRL_2, REG_CHAN_CNTRL_3, REG_CHAN_CNTRL_4, REG_USR_CNTRL_4, and REG_USR_CNTRL_5
-Added two new registers, both with their own fields and description: REG_CHAN_CNTRL_9 and REG_CHAN_CNTRL_10
=> docs/regmap/adi_regmap_dac.txt : Update and add registers

library/common/up_dac_channel.v
Cosmetic change.
Fix up_dac_channel indentation.
=> up_dac_channel: Cosmetics - fix indentation

docs/index.rst, docs/projects/ad7616_sdz/index.rst, docs/projects/images/ad7616_sdz/ad7616_parallel_hdl.svg, docs/projects/images/ad7616_sdz/ad7616_serial_hdl.svg
Add support for ad7616 documentation.
=> docs: Add ad7616 documentation

docs/user_guide/build_hdl.rst
Edits on the Build an HDL Project section of the [user guide documentation](https://wiki.analog.com/resources/fpga/docs/hdl)
=> docs: Edits on Build an HDL Project section of the user guide documentation

docs/index.rst, docs/projects/adaq7980_sdz/adaq7980_sdz_hdl.svg, docs/projects/adaq7980_sdz/index.rst
=> docs: Add adaq7980 documentation

docs/projects/ad7616_sdz/index.rst, docs/projects/ad9081_fmca_ebz/index.rst, docs/projects/common/support.rst, docs/projects/template/index.rst
Minor changes to keep tables consistency, fix indentation, remove the "main" branch from support.rst as we want to use the default main branch.
Doesn't affect functionality.
=> docs: Fix tables consistency and minor cosmetic changes

docs/index.rst, docs/projects/ad469x_fmc/ad469x_hdl.svg, docs/projects/ad469x_fmc/index.rst
=> docs: Add ad469x_fmc doc

docs/index.rst, docs/projects/ad5766_sdz/ad5766_spi_engine_hdl.svg, docs/projects/ad5766_sdz/index.rst
docs/projects/ad5766_sdz: Add ad5766_sdz project documentation
=> docs: Add ad5766 documentation

docs/index.rst, docs/projects/ad738x_fmc/ad738x_spi_engine_hdl.svg, docs/projects/ad738x_fmc/index.rst
docs/projects/ad738x_fmc: Add ad738x_fmc project documentation
=> docs: Add ad738x documentation

library/spi_engine/spi_engine_offload/spi_engine_offload.v
Previous level-based trigger could cause issues in some low sampling rate setups. This changes it to edge-based.
=> SPI Engine: edge-based trigger

docs/conf.py, docs/library/spi_engine/axi_spi_engine.rst, docs/user_guide/build_hdl.rst
docs: user_guide: Parallelization + readability
docs: Remove legacy code
docs: spi_engine: Improve formatting of interrupts
=> Update user guide, remove legacy code

docs/index.rst, docs/projects/cn0540/cn0540_hdl.svg, docs/projects/cn0540/index.rst
docs/projects/cn0540: Add cn0540 project documentation
=> docs: Add cn0540 documentation

docs/regmap/adi_regmap_pwm_gen.txt
Update the pwm_gen regmap's registers related to period/width/offset.
=> docs/regmap: Update pwm_gen regmap

docs/projects/ad9434_fmc/index.rst
This PR fixes some mistakes from documentations
=> docs: Fix mistakes in documentations

docs/index.rst, docs/projects/cn0363/cn0363_hdl_block_diagram.svg, docs/projects/cn0363/index.rst
docs/projects/cn0363: Add cn0363_pmdz project documentation
=> docs: Add cn0363_pmdz project documentation

docs/user_guide/hdl_coding_guideline.rst
Since parameters/local parameters can be involved in the declaration of registers/wires, it is best practice to declare them first.
=> doc: Update hdl coding guidelines

docs/regmap/adi_regmap_axi_ad7616.txt
Added register map file for axi_ad7616
=> Add axi_ad7616 regmap

docs/projects/ad7768evb/ad7768evb_fmc_hdl.svg, docs/projects/ad7768evb/index.rst, docs/projects/index.rst
docs/projects/ad7768evb: Add ad7768 project documentation
=> docs: Add ad7768 documentation

docs/projects/index.rst, docs/projects/pulsar_lvds/index.rst, docs/projects/pulsar_lvds/pulsar_lvds_block_diagram.svg
docs/projects/pulsar_lvds: Add pulsar_lvds project documentation
=> docs: Add pulsar_lvds project documentation

library/axi_dac_interpolate/axi_dac_interpolate_filter.v, library/axi_dac_interpolate/axi_dac_interpolate_reg.v
Fix dac interpolate control.
This bug only affected the Network Analyzer instrument.
=> Fix m2k interpolate sm

library/axi_logic_analyzer/axi_logic_analyzer.v
1. Add intermediary data_src_select register to control output selection between DMA and RAW. The switch RAW->DMA is not made until DMA has valid data; the switch DMA->RAW is not made until overwrite_enable is 1 regardless of dac_valid.
2. When overwrite is enabled, set the intermediary DMA register data_r to the RAW value.
This fixes an issue of the logic analizer that caused the last sample of a DMA
transfer to be visible at the next DMA transfer.
If the following pattern wanted to be obtained:
- start low
- has a few transitions
- then idle high
The M2K would display for a brief period the last sample of the previous DMA
transfer when switching overwrite_enable from 1 to 0. This would cause an
undesired transition from LOW to HIGH before the transfer began.
This pull request fixes this …
=> axi_logic_analyzer: Improve overwrite control logic

docs/library/axi_ad7606x/block_diagram.svg, docs/library/axi_ad7606x/index.rst
docs: Add axi_ad7606x IP core
[Note: initial doc commit's content + updated diagram]
=> docs: Add axi_ad7606x IP core

.github/workflows/check_for_guideline_rules.yml
Updated the guideline checker GitHub action, as the version of the used repos were outdated and errors were returned.
=> Update guideline checker action

docs/library/common/ad_dds/ad_dds_1.svg, docs/library/common/ad_dds/dds_basic.svg, docs/library/common/ad_dds/dds_clk_ratio_4.svg, docs/library/common/ad_dds/dds_dual_tone.svg, docs/library/common/ad_dds/dds_in_dac_core.svg, docs/library/common/ad_dds/fw_sync_basics.svg, docs/library/common/ad_dds/index.rst, docs/library/util_extract/index.rst, docs/library/util_var_fifo/index.rst, docs/library/util_wfifo/index.rst
Cherry-picked from the doc-ips branch
b09fecdc0 docs: Add common/ad_dds IP core
4cd49679e docs: Add util_wfifo IP core
dd87ffb81 docs: Add util_var_fifo IP core
456b04da0 docs: Add util_extract IP core
These IPs are not owned by anyone.
=> docs: Add ad_dds, util_wfifo, util_var_fifo util_extract IP Cores

docs/user_guide/architecture.rst, docs/user_guide/build_hdl.rst, docs/user_guide/index.rst, docs/user_guide/porting_project.rst, projects/common/lfcpnx/Makefile, projects/common/lfcpnx/lfcpnx_system_constr.pdc, projects/common/lfcpnx/lfcpnx_system_pb.tcl, projects/common/lfcpnx/system_pb.tcl, projects/common/lfcpnx/system_project.tcl, projects/common/lfcpnx/system_project_pb.tcl, projects/common/lfcpnx/system_top.v, projects/scripts/adi_lattice_dev_select.tcl, projects/scripts/adi_project_lattice.tcl, projects/scripts/adi_project_lattice_pb.tcl, projects/scripts/project-lattice.mk, scripts/adi_env.tcl
Content of request:
* Build scripts:
- projects/scripts/adi_lattice_dev_select.tcl
- projects/scripts/adi_project_lattice_bd.tcl (for Propel Builder block design projects)
- projects/scripts/adi_project_lattice.tcl (for Radiant projects)
- projects/scripts/project-lattice.mk
* Project files:
- projects/common/ctpnxe/Makefile
- projects/common/ctpnxe/system_project_bd.tcl (for Propel Builder block design build)
- projects/common/ctpnxe/system_project.tcl (for Radiant project build)
- projects/common/ctpnxe/system_bd.tcl
- projects/common/ctpnxe/system_top.v
- projects/common/ctpnxe/ctpnxe_system_constr.pdc
- projects/common/ctpnxe/ctpnxe_system_bd_mc.tcl (design with riscv-mc cpu)
- projects/common/ctpnxe/ctpnxe_system_bd_rx.tcl (design with riscv-rx cpu)
=> Build scripts for Lattice projects and base designs for Lattice Certus Pro NX Evaluation Board.

projects/ad7606x_fmc/common/ad7606x_bd.tcl
Fix the issue that caused a bug in the serial configuration build.
- [x ] I have compiled all hdl projects and libraries affected by this PR
=> ad7606x: Fix serial bug

library/spi_engine/spi_engine_execution/spi_engine_execution_constr.ttcl, library/spi_engine/spi_engine_offload/spi_engine_offload_constr.ttcl, library/spi_engine/spi_engine_offload/spi_engine_offload_ip.tcl
Related to release bug https://jira.analog.com/browse/SDGHDL-1262
The offload ttcl changes are needed because of this commit https://github.com/analogdevicesinc/hdl/commit/5aa0fdea6f4ea9c19f28e0e615fab5887bd3c7f9
The execution ttcl changes are needed because depending on the build sometimes the original version did not cover all the cdc that was happening inside the core
=> Fix spi engine timing

docs/library/axi_pwm_gen/index.rst
Fix/clarify bits of the timing diagrams of the axi_pwm_gen.
=> docs/library/axi_pwm_gen: Updates and corrections

projects/adrv9026/a10soc/system_project.tcl
Timing optimization for the adrv9026 with a10soc, because the CI builds were failing.
=> adrv9026/a10soc: Timing optimization

projects/ad9081_fmca_ebz/common/ad9081_fmc.txt
ad9081_fmc.txt :
- Fix spi0 pinout
- Add missing clkin8
=> ad9081_fmca_ebz: Fix ad9081_fmc.txt

docs/projects/ad4170_asdz/ad417x_hdl.svg, docs/projects/ad4170_asdz/index.rst, docs/projects/index.rst, projects/ad4170_asdz/Makefile, projects/ad4170_asdz/Readme.md, projects/ad4170_asdz/common/ad4170_ardz.txt, projects/ad4170_asdz/common/ad4170_asdz_bd.tcl, projects/ad4170_asdz/common/ad4170_asdz_qsys.tcl, projects/ad4170_asdz/coraz7s/Makefile, projects/ad4170_asdz/coraz7s/system_bd.tcl, projects/ad4170_asdz/coraz7s/system_constr.xdc, projects/ad4170_asdz/coraz7s/system_project.tcl, projects/ad4170_asdz/coraz7s/system_top.v, projects/ad4170_asdz/de10nano/Makefile, projects/ad4170_asdz/de10nano/system_constr.sdc, projects/ad4170_asdz/de10nano/system_project.tcl, projects/ad4170_asdz/de10nano/system_qsys.tcl, projects/ad4170_asdz/de10nano/system_top.v
Initial version of ad4170 (oasis) for de10nano and coraz7s carriers
=> AD4170 for de10nano and coraz7s

library/spi_engine/spi_engine_execution/spi_engine_execution_constr.ttcl, library/spi_engine/spi_engine_offload/spi_engine_offload_constr.ttcl, library/spi_engine/spi_engine_offload/spi_engine_offload_ip.tcl, projects/adrv9026/a10soc/system_project.tcl
Fixes for adrv9026/a10soc and ad4630_fmc/zed were implemented on the main branch. Cherry-pick fixing commits to next_stable for release.
=> Bring fixes for adrv9026/a10soc and ad4630_fmc/zed from the main branch

docs/projects/ad7124_asdz/ad7124_hdl.svg, docs/projects/ad7124_asdz/index.rst, docs/projects/index.rst, projects/ad7124_asdz/Makefile, projects/ad7124_asdz/de10nano/Makefile, projects/ad7124_asdz/de10nano/system_constr.sdc, projects/ad7124_asdz/de10nano/system_project.tcl, projects/ad7124_asdz/de10nano/system_qsys.tcl, projects/ad7124_asdz/de10nano/system_top.v
Initial version with SPI for AD7124_asdz
=> Initial version with SPI for AD7124_asdz

docs/projects/ad411x_ad717x/index.rst, docs/projects/ad4134_fmc/index.rst, docs/projects/ad4170_asdz/index.rst, docs/projects/ad4630_fmc/index.rst, docs/projects/ad469x_fmc/index.rst, docs/projects/ad485x_fmcz/index.rst, docs/projects/ad5766_sdz/index.rst, docs/projects/ad7124_asdz/index.rst, docs/projects/ad7134_fmc/index.rst, docs/projects/ad719x_asdz/index.rst, docs/projects/ad738x_fmc/index.rst, docs/projects/ad7606x_fmc/index.rst, docs/projects/ad7616_sdz/index.rst, docs/projects/ad7768evb/index.rst, docs/projects/ad9081_fmca_ebz/index.rst, docs/projects/ad9434_fmc/index.rst, docs/projects/ad9783_ebz/index.rst, docs/projects/adaq7980_sdz/index.rst, docs/projects/adrv9026/index.rst, docs/projects/adrv904x/index.rst, docs/projects/cn0363/index.rst, docs/projects/cn0540/index.rst, docs/projects/cn0561/index.rst, docs/projects/cn0585/index.rst, docs/projects/pulsar_adc/index.rst, docs/projects/pulsar_lvds/index.rst, docs/projects/template/index.rst, docs/user_guide/build_hdl.rst
Update the generic text from the build section of all pages, to specify that we do distribute the binary files.
=> doc: Update generic text in build section

library/axi_ad5766/axi_ad5766.v, library/axi_ad5766/axi_ad5766_ip.tcl, projects/ad3552r_evb/common/ad3552r_evb_bd.tcl, projects/ad3552r_evb/zed/system_bd.tcl, projects/ad7616_sdz/zed/system_bd.tcl
Fixing some issues reported by the devops team. Two projects are failing due to the sysid update and one is failing because of a missing connection to an input signal
=> Fix sysid params

projects/adrv9371x/common/adrv9371x_bd.tcl, projects/adrv9371x/kcu105/system_bd.tcl, projects/adrv9371x/kcu105/system_project.tcl
Fixed timing for adrv9371_kcu105 project.
Ran 8 consecutive successful builds.
=> adrv9371_kcu105: Fix timing

projects/ad7606x_fmc/Readme.md
Quick fix in the ad7606 Readme.md file, to reflect the build parameters change.
=> ad7606: Fix Readme.md

docs/projects/ad9739a_fmc/ad9739a_fmc_card_1.svg, docs/projects/ad9739a_fmc/ad9739a_fmc_xilinx.svg, docs/projects/ad9739a_fmc/index.rst, docs/projects/index.rst
This PR is made for the AD9739A- FMC (https://wiki.analog.com/resources/fpga/xilinx/fmc/ad9739a & https://wiki.analog.com/resources/fpga/xilinx/interposer/ad9739a) HDL documentation migration for GitHubIO.
Edited the wiki page and added the warning about the migration of the documentation.
=> docs/projects/ad9739a_fmc: Migrate documentation

docs/projects/index.rst, docs/projects/max96724/index.rst, docs/projects/max96724/max96724_hdl.svg
docs: Add MAX96724-related project page
=> docs: Add MAX96724-related project page

docs/library/corundum/index.rst, docs/library/index.rst
Adds the corundum IP Core doc page.
=> docs: Add Corundum IP Core

docs/projects/cn0506/cn0506_mii.svg, docs/projects/cn0506/cn0506_rgmii.svg, docs/projects/cn0506/cn0506_rmii.svg, docs/projects/cn0506/index.rst, docs/projects/index.rst
docs: Add CN0506-related project page
=> docs: Add CN0506-related project page

docs/projects/ad9265_fmc/ad9265_fmc_block_diagram.svg, docs/projects/ad9265_fmc/index.rst, docs/projects/index.rst, projects/ad9265_fmc/zed/Makefile, projects/ad9265_fmc/zed/system_bd.tcl, projects/ad9265_fmc/zed/system_constr.xdc, projects/ad9265_fmc/zed/system_project.tcl, projects/ad9265_fmc/zed/system_top.v
Cherry-pick AD9265-FMC to Zed from 'main' to 'next_stable'
(cherry picked from commit 2a54babb43d776ddd222bd0cc12d39fe05386498)
=> [next_stable] Cherry-pick AD9265-FMC to Zed on next_stable

docs/projects/adv7511/adv7511_bd.svg, docs/projects/adv7511/adv7511_internal.svg, docs/projects/adv7511/index.rst, docs/projects/index.rst, projects/adv7511/Readme.md
docs: Add ADV7511-related project page
=> docs: Add ADV7511-related project page

docs/projects/ad9467_fmc/ad9467_fmc_block_diagram.svg, docs/projects/ad9467_fmc/ad9467_fmc_card.svg, docs/projects/ad9467_fmc/index.rst, docs/projects/index.rst
Added the documentation for AD9467-FMC-250EBZ with Zedboard and KC705.
=> docs/projects/ad9467_fmc: Migrate documentation

docs/projects/ad4110/ad4110_block_diagram.svg, docs/projects/ad4110/index.rst, docs/projects/index.rst, projects/ad4110/zed/system_constr.xdc
=> AD4110 documentation

docs/projects/ad3552r_evb/ad3552r_evb_zed_block_diagram.svg, docs/projects/ad3552r_evb/index.rst, docs/projects/index.rst
Adding project documentation for EVAL-AD3552R.
=> docs/projects: Adding documentation for EVAL-AD3552R board

docs/projects/cn0579/cn0579_block_diagram.svg, docs/projects/cn0579/cn0579_clock_diagram.svg, docs/projects/cn0579/index.rst, docs/projects/index.rst
Adding project documentation for the CN0579 project.
=> docs/projects: Adding documentation for CN0579

docs/projects/adaq8092_fmc/adaq8092_clock_scheme.svg, docs/projects/adaq8092_fmc/adaq8092_zed_hdl_block_diagram.svg, docs/projects/adaq8092_fmc/index.rst, docs/projects/index.rst
Adding the HDL project documentation for the EVAL-ADAQ8092.
=> docs/projects: Adding ADAQ8092-FMC HDL project documentation.

library/common/ad_pack.v, library/common/tb/ad_pack_tb.v
Adding ALIGN_TO_MSB parameter for the ad_pack module and updating the testbench.
=> library/common/ad_pack: Add MSB aligned option

docs/library/index.rst, docs/library/util_sigma_delta_spi/index.rst
docs/library/util_sigma_delta_spi: Add documentation
=> docs/library/util_sigma_delta_spi: Add documentation

docs/projects/ad9081_fmca_ebz_x_band/ad9081_x_band_M8L4.svg, docs/projects/ad9081_fmca_ebz_x_band/index.rst, docs/projects/index.rst, projects/ad9081_fmca_ebz_x_band/Readme.md
This commit adds the documentation for the ad9081_fmca_ebz_x_band project.
=> docs/projects: Add documentation for Stingray project

docs/projects/ad469x_fmc/ad469x_hdl.svg, docs/projects/ad469x_fmc/index.rst, projects/ad469x_fmc/common/ad469x_bd.tcl, projects/ad469x_fmc/zed/system_top.v
Add GPIO control for CNV. Requested by BayLibre.
=> ad469x_zed: Use GPIO to drive CNV

docs/user_guide/build_intel_boot_bin.rst, docs/user_guide/build_intel_boot_image.rst, docs/user_guide/index.rst
New page that describes the workflow used in building the HDL Intel projects & the files that are involved in the process. This page is just a prototype, one more project needs to be included (Stratix10), but only after the major changes are made, if there will be any.
=> [Doc] New section regarding Intel projects workflow

docs/projects/adv7513/adv7513_bd.svg, docs/projects/adv7513/index.rst, docs/projects/index.rst
docs/projects: Add adv7513 page
=> docs/projects: Add adv7513 page

docs/user_guide/releases.rst
Update the Releases page contents to include the HDL_2023_R2.
Made minor fixes for Release notes links.
=> docs: Update releases page

docs/projects/ad6676evb/ad6676evb_block_diagram.svg, docs/projects/ad6676evb/index.rst, docs/projects/index.rst, projects/ad6676evb/common/ad6676evb_bd.tcl, projects/ad6676evb/vc707/system_constr.xdc
* Added the doc. for AD6676EVB
* Clarified the FMC port used in the VC707 design (constraints)
=> docs: Add AD6676EVB documentation

docs/projects/imageon/imageon_bd.svg, docs/projects/imageon/imageon_func_diagram.svg, docs/projects/imageon/index.rst, docs/projects/index.rst
=> docs: Add Imageon page

projects/ad77681evb/zed/system_top.v
Require for GPIO IRQ support using RDY
=> ad77681/zed: Connect RDY to GPIO

docs/user_guide/build_boot_bin.rst, docs/user_guide/build_intel_boot_image.rst
- docs: user_guide: build_boot_bin: Added Versal section
- docs: user_guide: build_intel_boot_image: Added Agilex 7 section
=> [doc] Versal and Agilex boot image flow

docs/projects/ad411x_ad717x/index.rst
Remove all ad4113 mentions, because it is not a released part.
=> docs: Update AD411x/AD717x documentation

docs/projects/ad9208_dual_ebz/ad9208_dual_ebz_block_diagram.svg, docs/projects/ad9208_dual_ebz/ad9208_dual_ebz_clock_scheme.svg, docs/projects/ad9208_dual_ebz/index.rst, docs/projects/index.rst
Add AD9208-DUAL-EBZ documentation
=> docs/projects: Add AD9208-DUAL-EBZ doc.

docs/projects/ad9694_fmc/ad9694_fmc_block_diagram.svg, docs/projects/ad9694_fmc/index.rst, docs/projects/ad9695_fmc/index.rst, docs/projects/index.rst
Add documentation for AD9694-FMC.
Add missing details to AD9695-1300EBZ documentation.
=> docs: Add AD9694-FMC documentation

projects/fmcomms2/kcu105/system_project.tcl
Currently it fails on CI with timing violation, this one passes locally.
=> fmcomms2: kcu105: system_project: Change implementation strategy

docs/conf.py, docs/projects/ad9209_fmca_ebz/ad9209_clocking_scheme.svg, docs/projects/ad9209_fmca_ebz/ad9209_jesd_datapath.svg, docs/projects/ad9209_fmca_ebz/index.rst, docs/projects/index.rst
Adds documentation for the AD9209 project.
=> docs: projects: ad9209_fmca_ebz: initial commit

docs/projects/ad4052_ardz/index.rst, docs/projects/ad408x_fmc_evb/index.rst, docs/projects/ad485x_fmcz/index.rst, docs/projects/ad9208_dual_ebz/index.rst, docs/projects/index.rst, docs/user_guide/build_hdl.rst
* ad9208_dual_ebz: Add no-OS support links
* index.rst: Reorder projects in list
* ad4052_ardz: Add missing block diagram section
* Add missing build instructions
* ad408x_fmc_evb
* ad485x_fmcz
* user_guide/build_hdl: Add more details on building using WSL
=> docs: Fixes on projects and Build HDL

docs/projects/adrv9009/adrv9009_jesd204b.svg, docs/projects/adrv9009/index.rst, docs/projects/adrv9009zu11eg/adrv9009_zu11eg_hdl.svg, docs/projects/adrv9009zu11eg/adrv9009_zu11eg_jesd204b.svg, docs/projects/adrv9009zu11eg/index.rst, docs/projects/adrv9371x/adrv9371_jesd204b.svg, docs/projects/adrv9371x/index.rst, docs/projects/fmcomms8/fmcomms8_jesd204b.svg, docs/projects/fmcomms8/index.rst, docs/projects/index.rst
Create documentation pages for:
- adrv9009
- adrv9371x
- fmcomms8
- adrv9009zu11eg
=> docs: Add ADRV9009/ADRV9371x/FMCOMMS8/ADRV9009ZU11EG docs

docs/projects/ad9213_dual_ebz/ad9213_dual_ebz_block_diagram.svg, docs/projects/ad9213_dual_ebz/ad9213_dual_ebz_clocks.svg, docs/projects/ad9213_dual_ebz/index.rst, docs/projects/index.rst
Ports the documentation for the AD9213_DUAL_EBZ HDL Reference Design over from the wiki.
=> docs/projects: port ad9213_dual_ebz doc

docs/projects/ad9083_evb/ad9083_evb_a10soc_block_diagram.svg, docs/projects/ad9083_evb/ad9083_evb_zcu102_block_diagram.svg, docs/projects/ad9083_evb/index.rst, docs/projects/index.rst
Add documentation for AD9083-EVB.
=> docs/projects/ad9083_evb: Add doc.

docs/user_guide/architecture.rst
Adds details about the FMC+ connectors and the supported VADJ values
=> user_guide: architecture: Add FM87 details

docs/library/axi_ad35xxr/block_diagram.svg, docs/library/axi_ad35xxr/detailed_architecture.svg, docs/library/axi_ad35xxr/index.rst, docs/projects/ad35xxr_evb/ad35xxr_evb_zed_block_diagram.svg, docs/projects/ad35xxr_evb/index.rst, docs/projects/cn0585/cn0585_zed_block_diagram.svg, docs/projects/cn0585/index.rst, docs/user_guide/git_repository.rst, projects/cn0585/common/cn0585_bd.tcl, projects/cn0585/zed/Makefile
Project failing because of a library change
AXI_AD3552R changed to AXI_AD35XXR
=> Fix cn0585 lib

docs/projects/fmcomms11/fmcomms11_block_diagram.svg, docs/projects/fmcomms11/index.rst, docs/projects/index.rst, projects/fmcomms11/common/fmcomms11_bd.tcl
Added FMCOMMS11 project documentation.
Update DAC DMA source bus width from 256 to 64 bits, as 64 is the Zynq PS limitation.
=> docs/projects/fmcomms11: Add doc.

docs/projects/adrv9364z7020/adrv9364z7020_block_diagram.svg, docs/projects/adrv9364z7020/index.rst, docs/projects/index.rst
Add ADRV9364Z7020 documentation.
=> docs: Add adrv9364z7020 doc

docs/projects/arradio/arradio_block_diagram.svg, docs/projects/arradio/index.rst, docs/projects/index.rst
Add arradio project documentation.
=> docs: Add arradio doc

docs/projects/adrv9361z7035/adrv9361z7035_block_diagram.svg, docs/projects/adrv9361z7035/index.rst, docs/projects/index.rst
Add adrv9361z7035 documentation.
=> docs: Add adrv9361z7035 doc

docs/projects/pulsar_adc/index.rst
Update link for ad40xx /adaq40xx driver and added new ones for devicetree files.
=> docs/pulsar_adc: Update documentation

docs/projects/ad353xr/index.rst, projects/ad353xr/Readme.md
Adding support for AD3531 and AD3531R on existing ad353xr project.
No code changes, more documentation related to show support for AD3531
=> project: ad353xr: add support ad3531

projects/ad9783_ebz/README.md, projects/ad9783_ebz/Readme.md, projects/ad9783_ebz/zcu102/README.md
Added the README.md for ad9873_ebz project.
=> projects/ad9783_ebz: Add README.md files

projects/fmcomms2/README.md, projects/fmcomms2/Readme.md, projects/fmcomms2/kc705/README.md, projects/fmcomms2/kcu105/README.md, projects/fmcomms2/vc707/README.md, projects/fmcomms2/zc702/README.md, projects/fmcomms2/zc706/README.md, projects/fmcomms2/zcu102/README.md, projects/fmcomms2/zed/README.md
Added the README.md for **FMCOMMS2** project.
=> projects/fmcomms2: Add READMEs

docs/library/axi_ada4355/axi_ada4355.svg, docs/library/axi_ada4355/index.rst, docs/library/index.rst, docs/projects/ada4355_fmc/ada4355_fmc_zed_block_diagram.svg, docs/projects/ada4355_fmc/index.rst, docs/projects/index.rst, library/axi_ada4355/Makefile, library/axi_ada4355/axi_ada4355.v, library/axi_ada4355/axi_ada4355_if.v, library/axi_ada4355/axi_ada4355_ip.tcl, projects/ada4355_fmc/Makefile, projects/ada4355_fmc/README.md, projects/ada4355_fmc/common/ada4355_fmc_bd.tcl, projects/ada4355_fmc/zed/Makefile, projects/ada4355_fmc/zed/README.md, projects/ada4355_fmc/zed/system_bd.tcl, projects/ada4355_fmc/zed/system_constr.xdc, projects/ada4355_fmc/zed/system_project.tcl, projects/ada4355_fmc/zed/system_top.v
Create support for ADA4355 project.
Create the axi_ada4355 interface IP.
Generic AXI ADC framework is used.
Create documentation for both IP and HDL project.
=> ADA4355: Add HDL support

library/axi_adrv9001/Makefile, library/axi_adrv9001/adrv9001_rx.v, library/axi_adrv9001/adrv9001_rx_link.v, library/axi_adrv9001/adrv9001_tx.v, library/axi_adrv9001/axi_adrv9001.v, library/axi_adrv9001/axi_adrv9001_constr.ttcl, library/axi_adrv9001/axi_adrv9001_constr.xdc, library/axi_adrv9001/axi_adrv9001_core.v, library/axi_adrv9001/axi_adrv9001_if.v, library/axi_adrv9001/axi_adrv9001_ip.tcl, library/axi_adrv9001/axi_adrv9001_rx.v, library/axi_adrv9001/axi_adrv9001_sync.v, library/axi_adrv9001/axi_adrv9001_sync_ctrl.v, library/axi_adrv9001/axi_adrv9001_tx.v, library/axi_adrv9001/axi_adrv9001_tx_channel.v, projects/adrv9001/common/adrv9001_bd.tcl, projects/adrv9001/zc706/system_constr.xdc, projects/adrv9001/zc706/system_top.v, projects/adrv9001/zcu102/lvds_constr.xdc, projects/adrv9001/zcu102/system_bd.tcl, projects/adrv9001/zcu102/system_constr.xdc, projects/adrv9001/zcu102/system_top.v, projects/adrv9001/zed/system_constr.xdc, projects/adrv9001/zed/system_top.v, projects/jupiter_sdr/system_bd.tcl, projects/jupiter_sdr/system_constr.xdc, projects/jupiter_sdr/system_project.tcl, projects/jupiter_sdr/system_top.v
Add MCS sync support.
Documentation will be added in a separate PR
=> Dev ADRV9001 MCS sync update

projects/adaq7980_sdz/README.md, projects/adaq7980_sdz/Readme.md, projects/adaq7980_sdz/zed/README.md
=> projects/adaq7980_sdz: Add README

projects/arradio/README.md, projects/arradio/Readme.md, projects/arradio/c5soc/README.md
=> projects/arradio: Add README

projects/ad7124_asdz/README.md, projects/ad7124_asdz/de10nano/README.md
=> projects/ad7124_asdz: Add README

projects/cn0577/Readme.md
=> projects/cn0577: Remove old Readme.md

docs/projects/index.rst, docs/projects/jupiter_sdr/index.rst, docs/projects/jupiter_sdr/jupiter_sdr_diagram.svg
=> Add jupiter_sdr documentation

projects/fmcomms5/README.md, projects/fmcomms5/Readme.md, projects/fmcomms5/zc702/README.md, projects/fmcomms5/zc706/README.md, projects/fmcomms5/zcu102/README.md
Added the README.md for fmcomms5 project.
=> projects/fmcomms5: Add README.md files

docs/projects/cn0579/index.rst, projects/cn0579/README.md, projects/cn0579/Readme.md, projects/cn0579/coraz7s/README.md, projects/cn0579/de10nano/README.md
Added the README.md for CN0579 project.
=> projects/cn0579:Add README.md files.

docs/projects/ad4134_fmc/index.rst, projects/ad4134_fmc/README.md, projects/ad4134_fmc/Readme.md, projects/ad4134_fmc/zed/README.md
Added the README.md for ad4134_fmc project.
=> projects/ad4134_fmc: Add READMEs

projects/cn0363/README.md, projects/cn0363/Readme.md, projects/cn0363/zed/README.md
Add README files for cn0363 project.
=> projects/cn0363:Add READMEs.

docs/projects/fmcomms8/index.rst, projects/fmcomms8/README.md, projects/fmcomms8/Readme.md, projects/fmcomms8/a10soc/README.md, projects/fmcomms8/zcu102/README.md
Added README files and some documentation fixes for the fmcomms8 project.
=> Add fmcomms8 READMEs and doc.

projects/cn0577/README.md, projects/fmcomms2/README.md
Fix READMEs title section for fmcomms2 and cn0577 projects.
=> projects/fmcomms2 & cn0577:Fix READMEs title

projects/daq2/kcu105/system_project.tcl
Fix timing issue on daq2+kcu105
Waiting for CI builds to confirm the fix
=> daq2_kcu105: Fix timing

docs/projects/ad7134_fmc/index.rst, projects/ad7134_fmc/README.md, projects/ad7134_fmc/Readme.md, projects/ad7134_fmc/zed/README.md
Added the README.md for ad7134_fmc project and modify GitHub documentation.
=> Ad7134 readme

docs/projects/adv7511/index.rst, projects/adv7511/README.md, projects/adv7511/Readme.md, projects/adv7511/zc702/README.md, projects/adv7511/zc706/README.md, projects/adv7511/zed/README.md
Added the README.md for **adv7511** project and fixed dts and dtsi links.
=> projects/adv7511: Add README.md files & doc

docs/projects/ad408x_fmc_evb/index.rst, projects/ad408x_fmc_evb/README.md, projects/ad408x_fmc_evb/zed/README.md
Added the README.md and fix dts link for **ad408x_fmc_evb** project.
=> projects/ad408x_fmc_evb: Added READMEs & fix dts links

docs/projects/adv7513/index.rst, projects/adv7513/README.md, projects/adv7513/Readme.md, projects/adv7513/de10nano/README.md
Added the README.md for the adv7513 project and fixed software related in GitHub doc.
=> projects/adv7513: Add README files

projects/adrv9026/vcu118/system_project.tcl
Fix timing issue on adrv9026+vcu118
Waiting for CI builds to confirm the fix
=> adrv9026_vcu118: Fix timing

projects/ad9082_fmca_ebz/README.md, projects/ad9082_fmca_ebz/Readme.md, projects/ad9082_fmca_ebz/vck190/README.md, projects/ad9082_fmca_ebz/vcu118/README.md, projects/ad9082_fmca_ebz/vpk180/README.md, projects/ad9082_fmca_ebz/zc706/README.md, projects/ad9082_fmca_ebz/zcu102/README.md
Add README for ad9082_fmca_ebz projects.
=> projects/ad9082_fmca_ebz: Add READMEs

projects/ad9081_fmca_ebz/a10soc/README.md, projects/ad9081_fmca_ebz/fm87/README.md, projects/ad9081_fmca_ebz/s10soc/README.md, projects/ad9081_fmca_ebz/vck190/README.md, projects/ad9081_fmca_ebz/vcu118/README.md, projects/ad9081_fmca_ebz/vcu128/README.md, projects/ad9081_fmca_ebz/vpk180/README.md, projects/ad9081_fmca_ebz/zc706/README.md, projects/ad9081_fmca_ebz/zcu102/README.md, projects/common/README.md
- Added README for the ad9081_fmca_ebz projects
- Added more example parameters in the template README
=> projects/ad9081_fmca_ebz: Add READMEs

docs/projects/ad6676evb/index.rst, projects/ad6676evb/README.md, projects/ad6676evb/Readme.md, projects/ad6676evb/vc707/README.md, projects/ad6676evb/zc706/README.md
Added the README.md for the ad6676evb project and fixed dts.
=> projects/ad6676evb: Add README files

docs/projects/ad4170_asdz/index.rst, projects/ad4170_asdz/README.md
This PR adds support to the recently released part AD4190. The add support scheme follows similary to how linux does it.
All codes are untouched and only documentation files are edited to show the support for AD4190.
Copyright dates retained, not sure if required to change from '2024' to '2024-2025'.
=> project: ad4170_asdz: add support of ad4190_ardz

docs/projects/ad4630_fmc/index.rst, projects/ad4630_fmc/README.md, projects/ad4630_fmc/Readme.md, projects/ad4630_fmc/zed/README.md
Updated AD4630 READMEs & fixed a link from documentation.
=> projects/ad4630_fmc: Update READMEs

docs/user_guide/architecture.rst
I updated the list of AMD FPGAs in the User Guide and added a new table listing discontinued AMD FPGA platforms
=> docs/user_guide/architecture.rst: Update AMD platforms status

docs/projects/ad9081_fmca_ebz/ad9081_204b_M8L4.svg, docs/projects/ad9081_fmca_ebz/index.rst, projects/ad9081_fmca_ebz/zcu102/README.md
- Restructured the AD9081 M8 L4 block diagram to the new format
- Updated the commands format in ZCU102 README
=> ad9081_fmca_ebz: Add restructured ZCU102 diagram & update README

docs/projects/ad4170_asdz/index.rst
Fixed documentation and removed not yet released parts
=> docs: ad4170_asdz: Fixed documentation

.github/CODEOWNERS
=> .github/CODEOWNERS: Update owners

projects/ad9208_dual_ebz/README.md, projects/ad9208_dual_ebz/Readme.md, projects/ad9208_dual_ebz/common/ad9208_dual_ebz_bd.tcl, projects/ad9208_dual_ebz/vcu118/Makefile, projects/ad9208_dual_ebz/vcu118/README.md, projects/ad9208_dual_ebz/vcu118/system_bd.tcl, projects/common/README.md
Added READMEs and renamed the common folder to comply with the naming standards.
Replaced all the occurrences for _dual_ad9208_ebz_bd.tcl_ to _ad9208_dual_ebz_bd.tcl_.
=> projects/ad9208_dual_ebz: Add READMEs

docs/projects/ad9467_fmc/index.rst
Fixed the broken links to schematics.
=> docs/projects/ad9467_fmc: Fix broken links to schematics

projects/cn0585/README.md, projects/cn0585/zed/README.md
=> projects/cn0585: Added README files

projects/adrv9009zu11eg/README.md, projects/adrv9009zu11eg/Readme.md, projects/adrv9009zu11eg/adrv2crr_fmc/README.md, projects/adrv9009zu11eg/adrv2crr_fmcomms8/README.md, projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/README.md
Updated README files of the project.
=> projects/adrv9009zu11eg: Updated README files

docs/projects/ad9209_fmca_ebz/index.rst, projects/ad9209_fmca_ebz/README.md, projects/ad9209_fmca_ebz/Readme.md, projects/ad9209_fmca_ebz/vck190/README.md, projects/ad9209_fmca_ebz/vck190/system_project.tcl
- Added READMEs
- Updated the evaluation board links in doc, as there is no AD9209 evaluation board, but the AD9081 eval board is used, in RX only mode
=> projects/ad9209_fmca_ebz: Add READMEs & update eval board links in doc

docs/projects/ad9694_fmc/index.rst, projects/ad9694_fmc/README.md, projects/ad9694_fmc/Readme.md, projects/ad9694_fmc/zcu102/README.md, projects/ad9694_fmc/zcu102/system_project.tcl
- Added READMEs
- Clean-up in documentation
=> projects/ad9694_fmc: Add READMEs

docs/projects/ad9213_dual_ebz/index.rst, projects/ad9213_dual_ebz/README.md, projects/ad9213_dual_ebz/Readme.md, projects/ad9213_dual_ebz/s10soc/README.md
- Added READMEs
- Fixed some calculations in the documentation
=> projects/ad9213_dual_ebz: Add READMEs

projects/cn0561/README.md, projects/cn0561/Readme.md, projects/cn0561/coraz7s/README.md, projects/cn0561/de10nano/README.md, projects/cn0561/zed/README.md
Updated README files of the project.
=> projects/cn0561: Updated README files

projects/ad35xxr_evb/README.md, projects/ad35xxr_evb/zed/README.md
projects/ad35xxr_evb: Update READMEs with VADJ info.
=> projects/ad35xxr_evb: Update READMEs with VADJ info

projects/ad7405_fmc/README.md, projects/ad7405_fmc/zed/README.md
Add VADJ value in **ad7405_fmc** README.
=> projects/ad7405_fmc: Add VADJ value

projects/ad7124_asdz/README.md, projects/ad7124_asdz/de10nano/README.md
Add VADJ value in ad7124 README.
=> ad7124: Add VADJ value in README

projects/adv7513/README.md, projects/adv7513/de10nano/README.md
Add VADJ value in **ADV7513** project.
=> projects/adv7513: Add VADJ range

projects/adrv9009zu11eg/README.md, projects/adrv9009zu11eg/adrv2crr_fmc/README.md, projects/adrv9009zu11eg/adrv2crr_fmcomms8/README.md, projects/adrv9009zu11eg/adrv2crr_fmcomms8/system_project.tcl, projects/adrv9009zu11eg/adrv2crr_fmcxmwbr1/README.md
Add VADJ values in **ADRV9009ZU11EG** README.
=> projects/adrv9009zu11eg:Update READMEs with VADJ

projects/adrv9371x/README.md, projects/adrv9371x/a10soc/README.md, projects/adrv9371x/kcu105/README.md, projects/adrv9371x/zc706/README.md, projects/adrv9371x/zcu102/README.md
=> projects/adrv9371x: Update READMEs with VADJ info

projects/cn0540/README.md, projects/cn0540/coraz7s/README.md, projects/cn0540/de10nano/README.md
Add VADJ value in cn0540 README.
=> cn0540: Add VADJ value in README

projects/ad9265_fmc/README.md, projects/ad9265_fmc/zc706/README.md, projects/ad9265_fmc/zed/README.md
Add VADJ values n ad9265_fmc README.
=> ad9265_fmc: Add VADJ in README

projects/ad57xx_ardz/README.md, projects/ad57xx_ardz/coraz7s/README.md, projects/ad57xx_ardz/de10nano/README.md
Added VIO info for ad57xx_ardz project.
=> Update READMEs with VIO info for ad57xx_ardz

docs/projects/ad9467_fmc/index.rst, projects/ad9467_fmc/README.md, projects/ad9467_fmc/kc705/README.md, projects/ad9467_fmc/zed/README.md
Add VADJ values for ad9467 README.
=> ad9467: Add VADJ value to README

projects/cn0577/README.md, projects/cn0577/zed/README.md
=> cn0577: Add VADJ value

projects/ad4052_ardz/README.md, projects/ad4052_ardz/coraz7s/README.md, projects/ad4052_ardz/de10nano/README.md
=> projects/ad4052_ardz: Add VIO

projects/ad5758_sdz/README.md, projects/ad5758_sdz/zed/README.md
Added VADJ to ad5758_sdz READMEs.
=> projects/ad5758_sdz: Add VADJ value

projects/ad469x_evb/README.md, projects/ad469x_evb/coraz7s/README.md, projects/ad469x_evb/de10nano/README.md, projects/ad469x_evb/zed/README.md
Added VADJ/VIO info for ad469x_evb project.
=> Update READMEs with VADJ/VIO info for ad469x_evb

projects/adrv904x/README.md, projects/adrv904x/zcu102/README.md
Added VADJ info in READMEs for adrv904x project.
=> Update READMEs with VADJ info for adrv904x project

projects/ad4170_asdz/README.md, projects/ad4170_asdz/coraz7s/README.md, projects/ad4170_asdz/de10nano/README.md
Added VIO to ad4170_asdz READMEs.
=> projects/ad4170_asdz: Add VIO value

projects/cn0585/README.md, projects/cn0585/zed/README.md
Update README files to include VADJ info & flags for cn0585.
=> cn0585: Add VADJ info

projects/ad408x_fmc_evb/README.md, projects/ad408x_fmc_evb/zed/README.md
Add VADJ value & flags for ad408x_fmc_evb.
=> ad408x_fmc_evb: Add VADJ value

.github/scripts/README.md, docs/projects/ad9081_fmca_ebz/index.rst, docs/projects/ad9209_fmca_ebz/index.rst, docs/projects/ad9467_fmc/ad9467_fmc_block_diagram.svg, docs/projects/ad9467_fmc/index.rst, docs/user_guide/architecture.rst, docs/user_guide/build_boot_bin.rst, docs/user_guide/build_hdl.rst, projects/ad9082_fmca_ebz/zcu102/README.md
Multiple doc and README fixes.
=> Documentation and README fixes

docs/user_guide/releases.rst
Update the documentation to reflect the changes from PR https://github.com/analogdevicesinc/hdl/pull/1802
=> docs/user_guide/releases: Update tools versions

docs/projects/pulsar_adc/index.rst
Updated the code sections, added the missing information, and corrected the mistakes that were noticed.
=> docs/projects/pulsar_adc: Fix HDL Documentation

projects/scripts/adi_project_xilinx.tcl
Versal boards do not support generating .bin files, in order for Vivado to not fail when ADI_GENERATE_BIN is set we must skip the .bin generation if the project is targetting a Versal FPGA even if the variable exists.
=> adi_project_xilinx: Skip .bin file generation for Versal projects when ADI_GENERATE_BIN is set

.github/scripts/README.md, .github/scripts/check_readme.sh, .github/workflows/readme_checker.yaml, projects/ad4110/zed/README.md, projects/ad6676evb/README.md, projects/ad6676evb/zc706/README.md, projects/ad7405_fmc/zed/README.md, projects/ad7616_sdz/zed/README.md, projects/ad77681evb/README.md, projects/ad77681evb/zed/README.md, projects/ad9083_evb/a10soc/README.md, projects/ad9083_evb/zcu102/README.md, projects/ad9213_evb/vcu118/README.md, projects/ad_quadmxfe1_ebz/README.md, projects/ad_quadmxfe1_ebz/vcu118/README.md, projects/adrv9009zu11eg/README.md, projects/adrv904x/README.md, projects/adrv904x/zcu102/README.md, projects/jupiter_sdr/README.md, projects/m2k/README.md, projects/pulsar_lvds_adc/zed/README.md
Final update for the .github/scripts/check_readme.md (previously named check_for_missing_readme_md.sh). Added the flag checking mechanism, so now the script doesn't throw errors where it shouldn't because some sections are missing (there're cases where certain sections can't be included). This script checks for all the README.md files from projects/. Now it will return 0, causing the CI pipeline responsible for this workflow to fail, thus alerting the PR owner, in the case that a new README.md file is added, that it's not correct and should be fixed before merging into main. Also renamed the workflow, it's more intuitive now. These details were added in the .github/scripts/README.md, where the script is described.
=> .github: Updated the README script and it's workflow

projects/ad488x_fmc_evb/README.md, projects/ad488x_fmc_evb/zed/README.md, projects/admx6001_ebz/README.md, projects/admx6001_ebz/vcu118/README.md
Added the VADJ values and labels in the README files of AD488X and ADMX6001.
=> projects: Update AD488X & ADMX6001 READMEs with VADJ value and labels

projects/ad738x_fmc/zed/system_bd.tcl
Fix system ID to reflect the actual build parameters
=> projects: ad738x_fmc: Fix system ID to reflect the actual build parameters
